In [ ]:
!pip install biopython

Collecting biopython
  Downloading biopython-1.88-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from biopython) (2.1.3)
Downloading biopython-1.88-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 11.7 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.88

In [ ]:
# @title
# ============================================================
# PART 11A.1
# DOWNLOAD AND INSPECT THE VIM-2 PDB STRUCTURE
# ============================================================

import os
import pandas as pd
import numpy as np

from Bio.PDB import PDBParser


# ============================================================
# DOWNLOAD VIM-2 STRUCTURE FROM RCSB PDB
# ============================================================

PDB_ID = "4NQ2"
PDB_FILE = f"{PDB_ID}.pdb"

!wget -q https://files.rcsb.org/download/4NQ2.pdb


# ============================================================
# CHECK THAT THE PDB FILE WAS DOWNLOADED
# ============================================================

if not os.path.exists(PDB_FILE):

    raise FileNotFoundError(
        f"Could not download {PDB_FILE}"
    )


print(
    f"Structure downloaded successfully: {PDB_FILE}"
)


# ============================================================
# LOAD PDB STRUCTURE
# ============================================================

parser = PDBParser(QUIET=True)

structure = parser.get_structure(
    "VIM2",
    PDB_FILE
)


# ============================================================
# INSPECT AVAILABLE MODELS AND CHAINS
# ============================================================

print("\n" + "=" * 70)
print("PART 11A.1 — VIM-2 PDB STRUCTURE INSPECTION")
print("=" * 70)

models = list(structure.get_models())

print(
    f"\nNumber of models: {len(models)}"
)

for model in structure:

    print(
        f"\nModel ID: {model.id}"
    )

    for chain in model:

        residues = [
            residue
            for residue in chain
            if residue.id[0] == " "
        ]

        print(
            f"Chain {chain.id}: "
            f"{len(residues)} standard amino-acid residues"
        )


# ============================================================
# SELECT CHAIN A
# ============================================================

TARGET_CHAIN = "A"

model = structure[0]

if TARGET_CHAIN not in model:

    raise ValueError(
        f"\nChain '{TARGET_CHAIN}' was not found.\n"
        f"Available chains: "
        f"{[chain.id for chain in model]}"
    )

chain = model[TARGET_CHAIN]


# ============================================================
# EXTRACT STANDARD AMINO-ACID RESIDUES
# ============================================================

standard_residues = []

for residue in chain:

    if residue.id[0] == " ":

        standard_residues.append(
            {
                "PDB_Residue_Name": residue.get_resname(),
                "PDB_Residue_Number": residue.id[1],
                "Insertion_Code": residue.id[2]
            }
        )


residue_df = pd.DataFrame(
    standard_residues
)


# ============================================================
# RESIDUE NUMBERING SUMMARY
# ============================================================

first_residue = residue_df[
    "PDB_Residue_Number"
].min()

last_residue = residue_df[
    "PDB_Residue_Number"
].max()

total_residues = len(
    residue_df
)


print("\n" + "=" * 70)
print("RESIDUE NUMBERING SUMMARY")
print("=" * 70)

print(
    f"\nTarget chain: {TARGET_CHAIN}"
)

print(
    f"First residue number: {first_residue}"
)

print(
    f"Last residue number: {last_residue}"
)

print(
    f"Total standard residues: {total_residues}"
)


# ============================================================
# DISPLAY FIRST AND LAST RESIDUES
# ============================================================

print("\n" + "=" * 70)
print("FIRST 15 RESIDUES")
print("=" * 70)

display(
    residue_df.head(15)
)


print("\n" + "=" * 70)
print("LAST 15 RESIDUES")
print("=" * 70)

display(
    residue_df.tail(15)
)


# ============================================================
# CHECK FOR MISSING RESIDUE NUMBERS
# ============================================================

all_numbers = residue_df[
    "PDB_Residue_Number"
].tolist()

expected_numbers = list(
    range(
        first_residue,
        last_residue + 1
    )
)

missing_numbers = sorted(
    set(expected_numbers) -
    set(all_numbers)
)


print("\n" + "=" * 70)
print("MISSING RESIDUE NUMBER CHECK")
print("=" * 70)

if len(missing_numbers) == 0:

    print(
        "\nNo missing residue numbers detected "
        "between the first and last resolved residues."
    )

else:

    print(
        f"\nNumber of missing residue positions: "
        f"{len(missing_numbers)}"
    )

    print(
        "Missing residue numbers:"
    )

    print(
        missing_numbers
    )


# ============================================================
# CHECK KEY BIOLOGICAL RESIDUES
# ============================================================

key_residues = [

    # Metal-coordinating residues
    114,
    116,
    118,
    179,
    198,
    240,

    # Active-site pocket residues
    61,
    67,
    87,
    233,

    # L3 loop boundaries
    60,
    68,

    # L10 loop boundaries
    201,
    214
]


available_residue_numbers = set(
    residue_df[
        "PDB_Residue_Number"
    ]
)


print("\n" + "=" * 70)
print("KEY RESIDUE AVAILABILITY CHECK")
print("=" * 70)

for position in key_residues:

    if position in available_residue_numbers:

        residue_name = residue_df.loc[
            residue_df[
                "PDB_Residue_Number"
            ] == position,

            "PDB_Residue_Name"
        ].iloc[0]

        print(
            f"Residue {position}: "
            f"FOUND ({residue_name})"
        )

    else:

        print(
            f"Residue {position}: "
            f"NOT FOUND"
        )


# ============================================================
# FINAL STATUS
# ============================================================

print("\n" + "=" * 70)
print("PART 11A.1 COMPLETE")
print("=" * 70)

print(
    "\nNext: exact sequence-to-PDB mapping validation."
)

Structure downloaded successfully: 4NQ2.pdb

======================================================================
PART 11A.1 — VIM-2 PDB STRUCTURE INSPECTION
======================================================================

Number of models: 1

Model ID: 0
Chain A: 230 standard amino-acid residues

======================================================================
RESIDUE NUMBERING SUMMARY
======================================================================

Target chain: A
First residue number: 32
Last residue number: 261
Total standard residues: 230

======================================================================
FIRST 15 RESIDUES
======================================================================

   PDB_Residue_Name  PDB_Residue_Number Insertion_Code
0               GLU                  32
1               TYR                  33
2               PRO                  34
3               THR                  35
4               VAL                  36
5               SER                  37
6               GLU                  38
7               ILE                  39
8               PRO                  40
9               VAL                  41
10              GLY                  42
11              GLU                  43
12              VAL                  44
13              ARG                  45
14              LEU                  46

======================================================================
LAST 15 RESIDUES
======================================================================

    PDB_Residue_Name  PDB_Residue_Number Insertion_Code
215              ASP                 247
216              LEU                 248
217              LEU                 249
218              LYS                 250
219              HIS                 251
220              THR                 252
221              THR                 253
222              ASN                 254
223              VAL                 255
224              VAL                 256
225              LYS                 257
226              ALA                 258
227              HIS                 259
228              THR                 260
229              ASN                 261

======================================================================
MISSING RESIDUE NUMBER CHECK
======================================================================

No missing residue numbers detected between the first and last resolved residues.

======================================================================
KEY RESIDUE AVAILABILITY CHECK
======================================================================
Residue 114: FOUND (HIS)
Residue 116: FOUND (HIS)
Residue 118: FOUND (ASP)
Residue 179: FOUND (HIS)
Residue 198: FOUND (CYS)
Residue 240: FOUND (HIS)
Residue 61: FOUND (SER)
Residue 67: FOUND (TYR)
Residue 87: FOUND (TRP)
Residue 233: FOUND (ALA)
Residue 60: FOUND (GLN)
Residue 68: FOUND (PRO)
Residue 201: FOUND (TYR)
Residue 214: FOUND (ALA)

======================================================================
PART 11A.1 COMPLETE
======================================================================

Next: exact sequence-to-PDB mapping validation.

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving VIM2_Part12H_Final_ML_Sanity_Check.csv to VIM2_Part12H_Final_ML_Sanity_Check.csv

In [ ]:
# ============================================================
# DOWNLOAD 4NQ2 PDB FILE
# ============================================================

import os

PDB_FILE = "4NQ2.pdb"

!wget -q https://files.rcsb.org/download/4NQ2.pdb -O 4NQ2.pdb

if os.path.exists(PDB_FILE):
    print(f"SUCCESS: {PDB_FILE} downloaded.")
    print(f"File size: {os.path.getsize(PDB_FILE):,} bytes")
else:
    raise FileNotFoundError(
        f"Could not download {PDB_FILE}"
    )

SUCCESS: 4NQ2.pdb downloaded.
File size: 351,297 bytes

In [ ]:
# @title
# ============================================================
# PART 11A.2
# EXACT DATASET-TO-PDB SEQUENCE VALIDATION
# ============================================================

import pandas as pd
import numpy as np
import re

from Bio.PDB import PDBParser
from Bio.SeqUtils import seq1


# ============================================================
# USER SETTINGS
# ============================================================

# Use the original mutation feature dataset because it contains
# the complete mutation identities required for sequence validation.
DATA_FILE = "VIM2_Part9_Mutation_Features.csv"

# PDB structure downloaded in Part 11A.1
PDB_FILE = "4NQ2.pdb"

# Target chain
TARGET_CHAIN = "A"


# ============================================================
# LOAD DATASET
# ============================================================

df = pd.read_csv(DATA_FILE)

print("=" * 70)
print("PART 11A.2 — DATASET-TO-PDB SEQUENCE VALIDATION")
print("=" * 70)

print(f"\nDataset rows: {len(df)}")
print(f"Dataset columns: {len(df.columns)}")


# ============================================================
# IDENTIFY THE MUTATION COLUMN
# ============================================================

possible_mutation_columns = [
    "Mutation",
    "mutation",
    "Mutant",
    "mutant",
    "Variant",
    "variant"
]

mutation_column = None

for col in possible_mutation_columns:

    if col in df.columns:

        mutation_column = col
        break


if mutation_column is None:

    raise ValueError(
        "\nCould not automatically identify the mutation column.\n"
        f"Available columns:\n{df.columns.tolist()}"
    )


print(f"\nMutation column detected: {mutation_column}")


# ============================================================
# PARSE MUTATION NOTATION
# ============================================================

# Expected mutation format:
# Example: R205T
# Wild-type residue = R
# Position = 205
# Mutant residue = T

mutation_pattern = re.compile(
    r"^([A-Z])(\d+)([A-Z])$"
)


parsed_mutations = []

for mutation in df[mutation_column].dropna().astype(str):

    match = mutation_pattern.match(
        mutation.strip()
    )

    if match:

        wt_residue = match.group(1)
        position = int(match.group(2))
        mutant_residue = match.group(3)

        parsed_mutations.append(
            {
                "Mutation": mutation,
                "WT_Residue": wt_residue,
                "Position": position,
                "Mutant_Residue": mutant_residue
            }
        )


mutation_info = pd.DataFrame(
    parsed_mutations
)


if mutation_info.empty:

    raise ValueError(
        "\nNo mutations could be parsed using the expected "
        "format, such as R205T."
    )


print(
    f"\nSuccessfully parsed mutations: "
    f"{len(mutation_info)}"
)


# ============================================================
# RECONSTRUCT WILD-TYPE RESIDUE IDENTITY BY POSITION
# ============================================================

wt_by_position = (
    mutation_info
    .groupby("Position")["WT_Residue"]
    .agg(
        lambda x: sorted(set(x))
    )
    .reset_index()
)


# Check whether each position has exactly one wild-type residue.
ambiguous_positions = wt_by_position[
    wt_by_position["WT_Residue"].apply(
        lambda x: len(x) != 1
    )
]


if len(ambiguous_positions) > 0:

    print("\nWARNING:")
    print(
        "Some positions have inconsistent wild-type identities."
    )

    display(
        ambiguous_positions.head(20)
    )

else:

    print(
        "\nWild-type identity is internally consistent "
        "across all mutation positions."
    )


# Convert list to single-letter residue.
wt_by_position["WT_Residue"] = (
    wt_by_position["WT_Residue"]
    .apply(
        lambda x: x[0]
    )
)


# ============================================================
# DATASET NUMBERING RANGE
# ============================================================

dataset_first_position = (
    wt_by_position["Position"].min()
)

dataset_last_position = (
    wt_by_position["Position"].max()
)

dataset_total_positions = len(
    wt_by_position
)


print("\n" + "=" * 70)
print("DATASET MUTATION NUMBERING SUMMARY")
print("=" * 70)

print(
    f"\nFirst mutated position: "
    f"{dataset_first_position}"
)

print(
    f"Last mutated position: "
    f"{dataset_last_position}"
)

print(
    f"Unique residue positions represented: "
    f"{dataset_total_positions}"
)


# ============================================================
# LOAD PDB STRUCTURE
# ============================================================

parser = PDBParser(QUIET=True)

structure = parser.get_structure(
    "VIM2",
    PDB_FILE
)

model = structure[0]

if TARGET_CHAIN not in model:

    raise ValueError(
        f"\nChain {TARGET_CHAIN} was not found."
    )


chain = model[TARGET_CHAIN]


# ============================================================
# EXTRACT PDB SEQUENCE
# ============================================================

pdb_residue_records = []

for residue in chain:

    # Keep standard amino-acid residues only.
    if residue.id[0] == " ":

        try:

            one_letter = seq1(
                residue.get_resname()
            )

            pdb_residue_records.append(
                {
                    "PDB_Position": residue.id[1],
                    "PDB_Residue": one_letter,
                    "PDB_Residue_Name": residue.get_resname()
                }
            )

        except Exception:

            pass


pdb_sequence_df = pd.DataFrame(
    pdb_residue_records
)


pdb_sequence = "".join(
    pdb_sequence_df[
        "PDB_Residue"
    ].tolist()
)


print("\n" + "=" * 70)
print("PDB CHAIN A SUMMARY")
print("=" * 70)

print(
    f"\nPDB residues: "
    f"{len(pdb_sequence_df)}"
)

print(
    f"First PDB residue number: "
    f"{pdb_sequence_df['PDB_Position'].min()}"
)

print(
    f"Last PDB residue number: "
    f"{pdb_sequence_df['PDB_Position'].max()}"
)


# ============================================================
# DIRECT NUMBERING COMPARISON
# ============================================================

# Compare every dataset wild-type identity with the PDB residue
# carrying the same numerical position.

direct_comparison = wt_by_position.merge(
    pdb_sequence_df,
    left_on="Position",
    right_on="PDB_Position",
    how="left"
)


direct_comparison["Direct_Match"] = (
    direct_comparison["WT_Residue"] ==
    direct_comparison["PDB_Residue"]
)


matched_positions = (
    direct_comparison["Direct_Match"]
    .sum()
)

compared_positions = (
    direct_comparison["PDB_Residue"]
    .notna()
    .sum()
)


print("\n" + "=" * 70)
print("DIRECT NUMBERING VALIDATION")
print("=" * 70)

print(
    f"\nPositions present in both dataset and PDB: "
    f"{compared_positions}"
)

print(
    f"Exact wild-type residue matches: "
    f"{matched_positions}"
)

if compared_positions > 0:

    direct_match_percent = (
        matched_positions /
        compared_positions *
        100
    )

    print(
        f"Direct numbering match rate: "
        f"{direct_match_percent:.2f}%"
    )


# ============================================================
# SHOW DIRECT MISMATCHES
# ============================================================

mismatches = direct_comparison[
    direct_comparison["PDB_Residue"].notna() &
    (~direct_comparison["Direct_Match"])
].copy()


print("\n" + "=" * 70)
print("DIRECT NUMBERING MISMATCHES")
print("=" * 70)

print(
    f"\nNumber of mismatches: "
    f"{len(mismatches)}"
)

if len(mismatches) > 0:

    display(
        mismatches[
            [
                "Position",
                "WT_Residue",
                "PDB_Position",
                "PDB_Residue",
                "PDB_Residue_Name"
            ]
        ].head(30)
    )


# ============================================================
# CHECK KEY LITERATURE RESIDUES
# ============================================================

# These are the residue identities currently supported by
# the literature-based feature design.

key_residues = {

    "F61": ("F", 61),
    "Y67": ("Y", 67),
    "W87": ("W", 87),

    "H114": ("H", 114),
    "H116": ("H", 116),
    "D118": ("D", 118),
    "H179": ("H", 179),
    "C198": ("C", 198),

    "N233": ("N", 233),
    "H240": ("H", 240)
}


key_check_results = []

for residue_label, (
    expected_residue,
    expected_position
) in key_residues.items():

    dataset_match = wt_by_position[
        wt_by_position["Position"] ==
        expected_position
    ]

    pdb_match = pdb_sequence_df[
        pdb_sequence_df["PDB_Position"] ==
        expected_position
    ]


    dataset_residue = (
        dataset_match["WT_Residue"].iloc[0]
        if len(dataset_match) > 0
        else None
    )

    pdb_residue = (
        pdb_match["PDB_Residue"].iloc[0]
        if len(pdb_match) > 0
        else None
    )


    key_check_results.append(
        {
            "Literature_Residue": residue_label,
            "Expected_WT": expected_residue,
            "Expected_Position": expected_position,
            "Dataset_WT": dataset_residue,
            "PDB_WT_Same_Number": pdb_residue,
            "Dataset_Match": (
                dataset_residue == expected_residue
            ),
            "PDB_Direct_Match": (
                pdb_residue == expected_residue
            )
        }
    )


key_check_df = pd.DataFrame(
    key_check_results
)


print("\n" + "=" * 70)
print("KEY LITERATURE RESIDUE VALIDATION")
print("=" * 70)

display(
    key_check_df
)


# ============================================================
# CHECK L3 AND L10 LOOP NUMBERING
# ============================================================

print("\n" + "=" * 70)
print("ACTIVE-SITE LOOP VALIDATION")
print("=" * 70)

loop_positions = list(
    range(60, 69)
) + list(
    range(201, 215)
)


loop_check = direct_comparison[
    direct_comparison["Position"].isin(
        loop_positions
    )
].copy()


print(
    "\nL3 loop positions checked: 60-68"
)

print(
    "L10 loop positions checked: 201-214"
)


loop_match_rate = (
    loop_check["Direct_Match"]
    .mean() *
    100
)


print(
    f"\nDirect identity match rate across "
    f"L3 + L10 loop positions: "
    f"{loop_match_rate:.2f}%"
)


display(
    loop_check[
        [
            "Position",
            "WT_Residue",
            "PDB_Position",
            "PDB_Residue",
            "Direct_Match"
        ]
    ]
)


# ============================================================
# FINAL DECISION SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 11A.2 — DECISION SUMMARY")
print("=" * 70)

if compared_positions > 0 and direct_match_percent >= 99:

    print(
        "\nDIRECT NUMBERING APPEARS HIGHLY CONSISTENT."
    )

    print(
        "The same numerical residue positions can likely "
        "be used for structural feature calculation."
    )

else:

    print(
        "\nDIRECT NUMBERING IS NOT SUFFICIENTLY VALIDATED."
    )

    print(
        "We will perform explicit sequence alignment before "
        "calculating any structure-based distances."
    )


print(
    "\nNo structural ML features have been calculated yet."
)

print(
    "This step is strictly a validation checkpoint."
)

======================================================================
PART 11A.2 — DATASET-TO-PDB SEQUENCE VALIDATION
======================================================================

Dataset rows: 5016
Dataset columns: 39

Mutation column detected: Mutation

Successfully parsed mutations: 5016

Wild-type identity is internally consistent across all mutation positions.

======================================================================
DATASET MUTATION NUMBERING SUMMARY
======================================================================

First mutated position: 1
Last mutated position: 266
Unique residue positions represented: 266

======================================================================
PDB CHAIN A SUMMARY
======================================================================

PDB residues: 230
First PDB residue number: 32
Last PDB residue number: 261

======================================================================
DIRECT NUMBERING VALIDATION
======================================================================

Positions present in both dataset and PDB: 230
Exact wild-type residue matches: 229
Direct numbering match rate: 99.57%

======================================================================
DIRECT NUMBERING MISMATCHES
======================================================================

Number of mismatches: 1

     Position WT_Residue  PDB_Position PDB_Residue PDB_Residue_Name
184       185          I         185.0           V              VAL

======================================================================
KEY LITERATURE RESIDUE VALIDATION
======================================================================

,Literature_Residue,Expected_WT,Expected_Position,Dataset_WT,PDB_WT_Same_Number,Dataset_Match,PDB_Direct_Match
0,F61,F,61,S,S,False,False
1,Y67,Y,67,Y,Y,True,True
2,W87,W,87,W,W,True,True
3,H114,H,114,H,H,True,True
4,H116,H,116,H,H,True,True
5,D118,D,118,D,D,True,True
6,H179,H,179,H,H,True,True
7,C198,C,198,C,C,True,True
8,N233,N,233,A,A,False,False
9,H240,H,240,H,H,True,True

======================================================================
ACTIVE-SITE LOOP VALIDATION
======================================================================

L3 loop positions checked: 60-68
L10 loop positions checked: 201-214

Direct identity match rate across L3 + L10 loop positions: 100.00%

     Position WT_Residue  PDB_Position PDB_Residue  Direct_Match
59         60          Q          60.0           Q          True
60         61          S          61.0           S          True
61         62          F          62.0           F          True
62         63          D          63.0           D          True
63         64          G          64.0           G          True
64         65          A          65.0           A          True
65         66          V          66.0           V          True
66         67          Y          67.0           Y          True
67         68          P          68.0           P          True
200       201          Y         201.0           Y          True
201       202          E         202.0           E          True
202       203          L         203.0           L          True
203       204          S         204.0           S          True
204       205          R         205.0           R          True
205       206          T         206.0           T          True
206       207          S         207.0           S          True
207       208          A         208.0           A          True
208       209          G         209.0           G          True
209       210          N         210.0           N          True
210       211          V         211.0           V          True
211       212          A         212.0           A          True
212       213          D         213.0           D          True
213       214          A         214.0           A          True

======================================================================
PART 11A.2 — DECISION SUMMARY
======================================================================

DIRECT NUMBERING APPEARS HIGHLY CONSISTENT.
The same numerical residue positions can likely be used for structural feature calculation.

No structural ML features have been calculated yet.
This step is strictly a validation checkpoint.

In [ ]:
# @title
# ============================================================
# PART 11B
# STRUCTURAL FEATURE ENGINEERING:
# DISTANCE TO METAL-BINDING SITE
#
# This script calculates the minimum three-dimensional distance
# between each mutated residue and the validated VIM-2 metal-
# binding site using the 4NQ2 crystal structure.
#
# Structural reference:
# PDB ID: 4NQ2
# Chain: A
#
# Validated metal-coordinating residues:
# H114, H116, D118, H179, C198, H240
#
# Distance definition:
# Minimum Euclidean distance between the C-alpha atom of the
# mutated residue and the C-alpha atom of any metal-site residue.
#
# Residues without resolved coordinates in 4NQ2 are assigned NaN.
# No artificial structural values are imputed.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os
import re
import numpy as np
import pandas as pd

from Bio.PDB import PDBParser


# ============================================================
# 2. USER SETTINGS
# ============================================================

# Input dataset containing mutation-level features.
INPUT_FILE = "VIM2_Part9_Mutation_Features.csv"

# Output dataset with the new structural feature.
OUTPUT_FILE = "VIM2_Part11B_Metal_Site_Distance.csv"

# Validated VIM-2 structural reference.
PDB_FILE = "4NQ2.pdb"

# Target protein chain.
TARGET_CHAIN = "A"

# Column containing mutation notation.
MUTATION_COLUMN = "Mutation"


# ============================================================
# 3. DEFINE THE VALIDATED METAL-BINDING SITE
# ============================================================

# These residues coordinate the binuclear metal center of VIM-2.
# Residue numbering was validated directly against both the
# mutation dataset and the resolved 4NQ2 structure.

METAL_SITE_RESIDUES = [
    114,  # His114
    116,  # His116
    118,  # Asp118
    179,  # His179
    198,  # Cys198
    240   # His240
]


# ============================================================
# 4. VALIDATE INPUT FILES
# ============================================================

print("=" * 70)
print("PART 11B — DISTANCE TO METAL-BINDING SITE")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        f"\nInput dataset was not found:\n{INPUT_FILE}"
    )


if not os.path.exists(PDB_FILE):

    raise FileNotFoundError(
        f"\nPDB structure was not found:\n{PDB_FILE}\n\n"
        "Download the structure before running this script."
    )


print(f"\nInput dataset found: {INPUT_FILE}")
print(f"PDB structure found: {PDB_FILE}")


# ============================================================
# 5. LOAD THE MUTATION DATASET
# ============================================================

df = pd.read_csv(INPUT_FILE)


print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)

print(f"\nTotal mutation rows: {len(df)}")
print(f"Total columns: {len(df.columns)}")


if MUTATION_COLUMN not in df.columns:

    raise ValueError(
        f"\nRequired mutation column '{MUTATION_COLUMN}' "
        "was not found.\n\n"
        f"Available columns:\n{df.columns.tolist()}"
    )


print(f"\nMutation column: {MUTATION_COLUMN}")


# ============================================================
# 6. PARSE MUTATION POSITIONS
# ============================================================

# Expected mutation format:
# A123V
#
# Group 1 = wild-type amino acid
# Group 2 = residue position
# Group 3 = mutant amino acid

mutation_pattern = re.compile(
    r"^([A-Z])(\d+)([A-Z])$"
)


def extract_mutation_position(mutation):
    """
    Extract the numerical residue position from standard
    single-amino-acid substitution notation.

    Example:
    H114A -> 114
    """

    if pd.isna(mutation):
        return np.nan

    mutation = str(mutation).strip()

    match = mutation_pattern.match(
        mutation
    )

    if match:

        return int(
            match.group(2)
        )

    return np.nan


# Create a temporary residue-position column.

df["Structural_Residue_Position"] = (
    df[MUTATION_COLUMN]
    .apply(extract_mutation_position)
)


# Validate mutation parsing.

unparsed_mutations = df[
    df["Structural_Residue_Position"].isna()
]


print("\n" + "=" * 70)
print("MUTATION POSITION PARSING")
print("=" * 70)

print(
    f"\nSuccessfully parsed mutations: "
    f"{df['Structural_Residue_Position'].notna().sum()}"
)

print(
    f"Unparsed mutations: "
    f"{len(unparsed_mutations)}"
)


if len(unparsed_mutations) > 0:

    print(
        "\nExamples of unparsed mutations:"
    )

    print(
        unparsed_mutations[
            MUTATION_COLUMN
        ].head(10).tolist()
    )


# ============================================================
# 7. LOAD THE 4NQ2 STRUCTURE
# ============================================================

parser = PDBParser(
    QUIET=True
)

structure = parser.get_structure(
    "VIM2",
    PDB_FILE
)


model = structure[0]


if TARGET_CHAIN not in model:

    available_chains = [
        chain.id
        for chain in model
    ]

    raise ValueError(
        f"\nTarget chain '{TARGET_CHAIN}' was not found.\n"
        f"Available chains: {available_chains}"
    )


chain = model[TARGET_CHAIN]


print("\n" + "=" * 70)
print("STRUCTURE SUMMARY")
print("=" * 70)

print(f"\nPDB ID: 4NQ2")
print(f"Target chain: {TARGET_CHAIN}")


# ============================================================
# 8. EXTRACT RESOLVED C-ALPHA COORDINATES
# ============================================================

# A dictionary will map:
#
# PDB residue number
#       ->
# 3D coordinates of its C-alpha atom

ca_coordinates = {}

residue_names = {}


for residue in chain:

    # Keep standard amino-acid residues only.
    if residue.id[0] != " ":
        continue

    residue_number = residue.id[1]

    # Only use residues with a resolved C-alpha atom.
    if "CA" not in residue:
        continue

    ca_coordinates[
        residue_number
    ] = residue["CA"].coord.astype(
        float
    )

    residue_names[
        residue_number
    ] = residue.get_resname()


print(
    f"\nResidues with resolved C-alpha coordinates: "
    f"{len(ca_coordinates)}"
)


# ============================================================
# 9. VALIDATE METAL-SITE RESIDUES
# ============================================================

print("\n" + "=" * 70)
print("METAL-SITE RESIDUE VALIDATION")
print("=" * 70)


metal_site_coordinates = {}

missing_metal_residues = []


for position in METAL_SITE_RESIDUES:

    if position not in ca_coordinates:

        missing_metal_residues.append(
            position
        )

        print(
            f"Residue {position}: "
            f"NOT AVAILABLE"
        )

    else:

        metal_site_coordinates[
            position
        ] = ca_coordinates[
            position
        ]

        print(
            f"Residue {position}: "
            f"FOUND "
            f"({residue_names[position]})"
        )


if len(missing_metal_residues) > 0:

    raise ValueError(
        "\nOne or more validated metal-site residues "
        "do not have resolved C-alpha coordinates.\n\n"
        f"Missing residues: {missing_metal_residues}"
    )


print(
    f"\nAll {len(METAL_SITE_RESIDUES)} metal-site residues "
    "were successfully validated."
)


# ============================================================
# 10. CALCULATE MINIMUM DISTANCE TO THE METAL SITE
# ============================================================

def calculate_distance_to_metal_site(
    residue_position
):
    """
    Calculate the minimum C-alpha distance between one residue
    and the validated VIM-2 metal-binding site.

    Parameters
    ----------
    residue_position : int
        Residue position in VIM-2 numbering.

    Returns
    -------
    float
        Minimum Euclidean distance in Angstroms.

    np.nan
        Returned when the residue is not structurally resolved
        in the 4NQ2 reference structure.
    """

    # Return NaN for missing or invalid positions.
    if pd.isna(residue_position):

        return np.nan


    residue_position = int(
        residue_position
    )


    # Structural coordinates are unavailable for residues that
    # are not resolved in the PDB structure.
    if residue_position not in ca_coordinates:

        return np.nan


    mutation_coordinate = ca_coordinates[
        residue_position
    ]


    # Calculate the distance from the mutated residue to every
    # validated metal-site residue.
    distances = []

    for metal_position, metal_coordinate in (
        metal_site_coordinates.items()
    ):

        distance = np.linalg.norm(
            mutation_coordinate -
            metal_coordinate
        )

        distances.append(
            distance
        )


    # Return the minimum distance to the metal-binding site.
    return float(
        np.min(distances)
    )


# ============================================================
# 11. IDENTIFY THE NEAREST METAL-SITE RESIDUE
# ============================================================

def identify_nearest_metal_site_residue(
    residue_position
):
    """
    Identify which validated metal-site residue is structurally
    closest to the mutated residue.

    This auxiliary annotation is useful for quality control and
    future biological interpretation. It is retained separately
    from the primary distance feature.
    """

    if pd.isna(residue_position):

        return np.nan


    residue_position = int(
        residue_position
    )


    if residue_position not in ca_coordinates:

        return np.nan


    mutation_coordinate = ca_coordinates[
        residue_position
    ]


    distance_dict = {}


    for metal_position, metal_coordinate in (
        metal_site_coordinates.items()
    ):

        distance_dict[
            metal_position
        ] = np.linalg.norm(
            mutation_coordinate -
            metal_coordinate
        )


    nearest_position = min(
        distance_dict,
        key=distance_dict.get
    )


    return nearest_position


# ============================================================
# 12. CALCULATE THE STRUCTURAL FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING METAL-SITE DISTANCES")
print("=" * 70)


df["Distance_to_Metal_Site"] = (
    df["Structural_Residue_Position"]
    .apply(
        calculate_distance_to_metal_site
    )
)


# The nearest metal-site residue is retained as an auxiliary
# biological annotation. It may be useful later for analysis,
# visualization, and model interpretation.

df["Nearest_Metal_Site_Residue"] = (
    df["Structural_Residue_Position"]
    .apply(
        identify_nearest_metal_site_residue
    )
)


# ============================================================
# 13. REMOVE THE TEMPORARY PARSING COLUMN
# ============================================================

# The temporary position column was used only internally for
# structural mapping and is not required in the final dataset.

df.drop(
    columns=[
        "Structural_Residue_Position"
    ],
    inplace=True
)


# ============================================================
# 14. QUALITY CONTROL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("FEATURE QUALITY CONTROL")
print("=" * 70)


resolved_count = (
    df["Distance_to_Metal_Site"]
    .notna()
    .sum()
)


unresolved_count = (
    df["Distance_to_Metal_Site"]
    .isna()
    .sum()
)


print(
    f"\nMutations with structural distance available: "
    f"{resolved_count}"
)

print(
    f"Mutations without resolved structural coordinates: "
    f"{unresolved_count}"
)


if resolved_count > 0:

    print(
        f"\nMinimum distance: "
        f"{df['Distance_to_Metal_Site'].min():.3f} Å"
    )

    print(
        f"Maximum distance: "
        f"{df['Distance_to_Metal_Site'].max():.3f} Å"
    )

    print(
        f"Mean distance: "
        f"{df['Distance_to_Metal_Site'].mean():.3f} Å"
    )

    print(
        f"Median distance: "
        f"{df['Distance_to_Metal_Site'].median():.3f} Å"
    )


# ============================================================
# 15. VALIDATE THE METAL-SITE RESIDUES THEMSELVES
# ============================================================

print("\n" + "=" * 70)
print("METAL-SITE DISTANCE SANITY CHECK")
print("=" * 70)


for position in METAL_SITE_RESIDUES:

    matching_rows = df[
        df[MUTATION_COLUMN]
        .astype(str)
        .str.match(
            rf"^[A-Z]{position}[A-Z]$"
        )
    ]


    if len(matching_rows) > 0:

        distance_values = matching_rows[
            "Distance_to_Metal_Site"
        ].dropna()


        if len(distance_values) > 0:

            print(
                f"\nPosition {position}:"
            )

            print(
                f"Minimum mutation distance: "
                f"{distance_values.min():.6f} Å"
            )

            print(
                "Expected behavior: approximately 0 Å "
                "because the mutated position itself belongs "
                "to the metal-binding site."
            )


# ============================================================
# 16. CHECK FOR UNEXPECTED NEGATIVE VALUES
# ============================================================

negative_distances = df[
    df["Distance_to_Metal_Site"] < 0
]


if len(negative_distances) > 0:

    raise ValueError(
        "\nNegative structural distances were detected. "
        "Euclidean distances cannot be negative."
    )


print(
    "\nNo negative distance values detected."
)


# ============================================================
# 17. DISPLAY EXAMPLE RESULTS
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE STRUCTURAL FEATURES")
print("=" * 70)


display(
    df[
        [
            MUTATION_COLUMN,
            "Distance_to_Metal_Site",
            "Nearest_Metal_Site_Residue"
        ]
    ].head(20)
)


# ============================================================
# 18. METAL-SITE DISTANCE DISTRIBUTION BY POSITION
# ============================================================

position_distance_summary = (
    df[
        [
            MUTATION_COLUMN,
            "Distance_to_Metal_Site",
            "Nearest_Metal_Site_Residue"
        ]
    ]
    .copy()
)


position_distance_summary["Residue_Position"] = (
    position_distance_summary[
        MUTATION_COLUMN
    ]
    .apply(
        extract_mutation_position
    )
)


position_distance_summary = (
    position_distance_summary
    .dropna(
        subset=[
            "Distance_to_Metal_Site"
        ]
    )
    .groupby(
        "Residue_Position",
        as_index=False
    )
    .agg(
        Distance_to_Metal_Site=(
            "Distance_to_Metal_Site",
            "first"
        ),
        Nearest_Metal_Site_Residue=(
            "Nearest_Metal_Site_Residue",
            "first"
        )
    )
)


print(
    f"\nUnique residue positions with calculated "
    f"metal-site distances: "
    f"{len(position_distance_summary)}"
)


# ============================================================
# 19. SAVE THE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


print("\n" + "=" * 70)
print("PART 11B COMPLETE")
print("=" * 70)

print(
    f"\nOutput file saved successfully:\n{OUTPUT_FILE}"
)

print(
    f"\nFinal dataset rows: {len(df)}"
)

print(
    f"Final dataset columns: {len(df.columns)}"
)

print(
    "\nNew primary feature:"
)

print(
    "  Distance_to_Metal_Site"
)

print(
    "\nNew auxiliary annotation:"
)

print(
    "  Nearest_Metal_Site_Residue"
)

print(
    "\nDistance unit: Angstrom (Å)"
)

print(
    "\nStructural reference:"
)

print(
    "  PDB: 4NQ2"
)

print(
    "  Chain: A"
)

print(
    "\nValidated metal-binding residues:"
)

print(
    "  H114, H116, D118, H179, C198, H240"
)

print(
    "\nResidues without resolved coordinates remain NaN."
)

print(
    "\nNext step:"
)

print(
    "  Part 11C — Distance to the validated active-site pocket."
)

======================================================================
PART 11B — DISTANCE TO METAL-BINDING SITE
======================================================================

Input dataset found: VIM2_Part9_Mutation_Features.csv
PDB structure found: 4NQ2.pdb

======================================================================
DATASET SUMMARY
======================================================================

Total mutation rows: 5016
Total columns: 39

Mutation column: Mutation

======================================================================
MUTATION POSITION PARSING
======================================================================

Successfully parsed mutations: 5016
Unparsed mutations: 0

======================================================================
STRUCTURE SUMMARY
======================================================================

PDB ID: 4NQ2
Target chain: A

Residues with resolved C-alpha coordinates: 230

======================================================================
METAL-SITE RESIDUE VALIDATION
======================================================================
Residue 114: FOUND (HIS)
Residue 116: FOUND (HIS)
Residue 118: FOUND (ASP)
Residue 179: FOUND (HIS)
Residue 198: FOUND (CYS)
Residue 240: FOUND (HIS)

All 6 metal-site residues were successfully validated.

======================================================================
CALCULATING METAL-SITE DISTANCES
======================================================================

======================================================================
FEATURE QUALITY CONTROL
======================================================================

Mutations with structural distance available: 4335
Mutations without resolved structural coordinates: 681

Minimum distance: 0.000 Å
Maximum distance: 26.687 Å
Mean distance: 12.238 Å
Median distance: 12.090 Å

======================================================================
METAL-SITE DISTANCE SANITY CHECK
======================================================================

Position 114:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because the mutated position itself belongs to the metal-binding site.

Position 116:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because the mutated position itself belongs to the metal-binding site.

Position 118:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because the mutated position itself belongs to the metal-binding site.

Position 179:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because the mutated position itself belongs to the metal-binding site.

Position 198:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because the mutated position itself belongs to the metal-binding site.

Position 240:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because the mutated position itself belongs to the metal-binding site.

No negative distance values detected.

======================================================================
EXAMPLE STRUCTURAL FEATURES
======================================================================

   Mutation  Distance_to_Metal_Site  Nearest_Metal_Site_Residue
0       M1A                     NaN                         NaN
1       M1C                     NaN                         NaN
2       M1D                     NaN                         NaN
3       M1E                     NaN                         NaN
4       M1F                     NaN                         NaN
5       M1G                     NaN                         NaN
6       M1H                     NaN                         NaN
7       M1I                     NaN                         NaN
8       M1K                     NaN                         NaN
9       M1L                     NaN                         NaN
10      M1N                     NaN                         NaN
11      M1P                     NaN                         NaN
12      M1Q                     NaN                         NaN
13      M1R                     NaN                         NaN
14      M1S                     NaN                         NaN
15      M1T                     NaN                         NaN
16      M1V                     NaN                         NaN
17      M1W                     NaN                         NaN
18      M1Y                     NaN                         NaN
19      F2A                     NaN                         NaN

Unique residue positions with calculated metal-site distances: 230

======================================================================
PART 11B COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part11B_Metal_Site_Distance.csv

Final dataset rows: 5016
Final dataset columns: 41

New primary feature:
  Distance_to_Metal_Site

New auxiliary annotation:
  Nearest_Metal_Site_Residue

Distance unit: Angstrom (Å)

Structural reference:
  PDB: 4NQ2
  Chain: A

Validated metal-binding residues:
  H114, H116, D118, H179, C198, H240

Residues without resolved coordinates remain NaN.

Next step:
  Part 11C — Distance to the validated active-site pocket.

In [ ]:
# @title
# ============================================================
# PART 11C
# STRUCTURAL FEATURE ENGINEERING:
# DISTANCE TO THE VALIDATED ACTIVE-SITE POCKET
#
# This script calculates the minimum three-dimensional distance
# between each mutated residue and the validated core active-site
# pocket of VIM-2 using the 4NQ2 crystal structure.
#
# Structural reference:
# PDB ID: 4NQ2
# Chain: A
#
# Validated core active-site pocket residues:
# F62, Y67, W87, H114, H116, D118, H179, C198, H240
#
# Distance definition:
# Minimum Euclidean distance between the C-alpha atom of the
# mutated residue and the C-alpha atom of any validated
# active-site pocket residue.
#
# Residues without resolved coordinates in 4NQ2 are assigned NaN.
# No artificial structural values are imputed.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os
import re
import numpy as np
import pandas as pd

from Bio.PDB import PDBParser


# ============================================================
# 2. USER SETTINGS
# ============================================================

# Input dataset generated in Part 11B.
INPUT_FILE = "VIM2_Part11B_Metal_Site_Distance.csv"

# Output dataset containing the new active-site pocket feature.
OUTPUT_FILE = "VIM2_Part11C_Active_Site_Pocket_Distance.csv"

# Validated structural reference.
PDB_FILE = "4NQ2.pdb"

# Target protein chain.
TARGET_CHAIN = "A"

# Column containing mutation notation.
MUTATION_COLUMN = "Mutation"


# ============================================================
# 3. DEFINE THE VALIDATED CORE ACTIVE-SITE POCKET
# ============================================================

# The residue set below was selected as the sequence-validated
# core active-site pocket representation for VIM-2.
#
# The positions were validated against:
# 1. The mutation dataset wild-type sequence
# 2. Direct residue numbering in 4NQ2
# 3. Resolved structural coordinates in chain A
#
# Aromatic / pocket-shaping residues:
# F62, Y67, W87
#
# Catalytic / metal-center residues:
# H114, H116, D118, H179, C198, H240

ACTIVE_SITE_POCKET_RESIDUES = [
    62,   # Phe62
    67,   # Tyr67
    87,   # Trp87
    114,  # His114
    116,  # His116
    118,  # Asp118
    179,  # His179
    198,  # Cys198
    240   # His240
]


# Expected one-letter identities for quality control.
EXPECTED_POCKET_IDENTITIES = {
    62: "F",
    67: "Y",
    87: "W",
    114: "H",
    116: "H",
    118: "D",
    179: "H",
    198: "C",
    240: "H"
}


# ============================================================
# 4. VALIDATE INPUT FILES
# ============================================================

print("=" * 70)
print("PART 11C — DISTANCE TO THE ACTIVE-SITE POCKET")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        f"\nInput dataset was not found:\n{INPUT_FILE}"
    )


if not os.path.exists(PDB_FILE):

    raise FileNotFoundError(
        f"\nPDB structure was not found:\n{PDB_FILE}"
    )


print(f"\nInput dataset found: {INPUT_FILE}")
print(f"PDB structure found: {PDB_FILE}")


# ============================================================
# 5. LOAD THE DATASET
# ============================================================

df = pd.read_csv(INPUT_FILE)


print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)

print(f"\nTotal mutation rows: {len(df)}")
print(f"Total columns: {len(df.columns)}")


if MUTATION_COLUMN not in df.columns:

    raise ValueError(
        f"\nRequired mutation column '{MUTATION_COLUMN}' "
        "was not found.\n\n"
        f"Available columns:\n{df.columns.tolist()}"
    )


# ============================================================
# 6. PARSE MUTATION POSITIONS
# ============================================================

# Expected standard mutation format:
# A123V
#
# Group 1: wild-type residue
# Group 2: residue position
# Group 3: mutant residue

mutation_pattern = re.compile(
    r"^([A-Z])(\d+)([A-Z])$"
)


def extract_mutation_position(mutation):
    """
    Extract the numerical residue position from standard
    amino-acid substitution notation.
    """

    if pd.isna(mutation):

        return np.nan

    mutation = str(mutation).strip()

    match = mutation_pattern.match(mutation)

    if match:

        return int(match.group(2))

    return np.nan


def extract_wild_type_residue(mutation):
    """
    Extract the wild-type amino-acid identity from a mutation.
    """

    if pd.isna(mutation):

        return np.nan

    mutation = str(mutation).strip()

    match = mutation_pattern.match(mutation)

    if match:

        return match.group(1)

    return np.nan


# Create temporary structural mapping columns.

df["Structural_Residue_Position"] = (
    df[MUTATION_COLUMN]
    .apply(extract_mutation_position)
)


df["Structural_WT_Residue"] = (
    df[MUTATION_COLUMN]
    .apply(extract_wild_type_residue)
)


# ============================================================
# 7. LOAD THE 4NQ2 STRUCTURE
# ============================================================

parser = PDBParser(QUIET=True)

structure = parser.get_structure(
    "VIM2",
    PDB_FILE
)


model = structure[0]


if TARGET_CHAIN not in model:

    available_chains = [
        chain.id
        for chain in model
    ]

    raise ValueError(
        f"\nTarget chain '{TARGET_CHAIN}' was not found.\n"
        f"Available chains: {available_chains}"
    )


chain = model[TARGET_CHAIN]


print("\n" + "=" * 70)
print("STRUCTURE SUMMARY")
print("=" * 70)

print("\nStructural reference: 4NQ2")
print(f"Target chain: {TARGET_CHAIN}")


# ============================================================
# 8. EXTRACT RESOLVED C-ALPHA COORDINATES
# ============================================================

# Dictionary structure:
#
# Residue position
#       ->
# C-alpha coordinate

ca_coordinates = {}

pdb_residue_names = {}


for residue in chain:

    # Retain standard amino-acid residues only.
    if residue.id[0] != " ":

        continue


    residue_position = residue.id[1]


    # A residue must have a resolved C-alpha atom.
    if "CA" not in residue:

        continue


    ca_coordinates[residue_position] = (
        residue["CA"]
        .coord
        .astype(float)
    )


    pdb_residue_names[residue_position] = (
        residue.get_resname()
    )


print(
    f"\nResidues with resolved C-alpha coordinates: "
    f"{len(ca_coordinates)}"
)


# ============================================================
# 9. VALIDATE ACTIVE-SITE POCKET RESIDUES
# ============================================================

print("\n" + "=" * 70)
print("ACTIVE-SITE POCKET RESIDUE VALIDATION")
print("=" * 70)


one_letter_mapping = {
    "ALA": "A",
    "ARG": "R",
    "ASN": "N",
    "ASP": "D",
    "CYS": "C",
    "GLN": "Q",
    "GLU": "E",
    "GLY": "G",
    "HIS": "H",
    "ILE": "I",
    "LEU": "L",
    "LYS": "K",
    "MET": "M",
    "PHE": "F",
    "PRO": "P",
    "SER": "S",
    "THR": "T",
    "TRP": "W",
    "TYR": "Y",
    "VAL": "V"
}


active_site_coordinates = {}

missing_pocket_residues = []


for position in ACTIVE_SITE_POCKET_RESIDUES:

    if position not in ca_coordinates:

        missing_pocket_residues.append(position)

        print(
            f"Residue {position}: NOT AVAILABLE"
        )

        continue


    pdb_three_letter = pdb_residue_names[position]

    pdb_one_letter = one_letter_mapping.get(
        pdb_three_letter,
        "?"
    )


    expected_identity = (
        EXPECTED_POCKET_IDENTITIES[position]
    )


    identity_match = (
        pdb_one_letter == expected_identity
    )


    print(
        f"Residue {position}: "
        f"Expected={expected_identity}, "
        f"PDB={pdb_one_letter}, "
        f"Match={identity_match}"
    )


    if not identity_match:

        raise ValueError(
            f"\nUnexpected residue identity at position "
            f"{position}: expected "
            f"{expected_identity}, found "
            f"{pdb_one_letter}."
        )


    active_site_coordinates[position] = (
        ca_coordinates[position]
    )


if len(missing_pocket_residues) > 0:

    raise ValueError(
        "\nThe following active-site pocket residues "
        "do not have resolved structural coordinates:\n"
        f"{missing_pocket_residues}"
    )


print(
    f"\nAll {len(ACTIVE_SITE_POCKET_RESIDUES)} "
    "active-site pocket residues were successfully validated."
)


# ============================================================
# 10. CALCULATE DISTANCE TO THE ACTIVE-SITE POCKET
# ============================================================

def calculate_distance_to_active_site_pocket(
    residue_position
):
    """
    Calculate the minimum C-alpha distance between one residue
    and the validated VIM-2 core active-site pocket.

    Returns
    -------
    float
        Minimum Euclidean distance in Angstroms.

    np.nan
        Returned when the residue does not have resolved
        structural coordinates in 4NQ2.
    """

    if pd.isna(residue_position):

        return np.nan


    residue_position = int(residue_position)


    if residue_position not in ca_coordinates:

        return np.nan


    mutation_coordinate = (
        ca_coordinates[residue_position]
    )


    distances = []


    for pocket_position, pocket_coordinate in (
        active_site_coordinates.items()
    ):

        distance = np.linalg.norm(
            mutation_coordinate -
            pocket_coordinate
        )

        distances.append(distance)


    return float(np.min(distances))


# ============================================================
# 11. IDENTIFY THE NEAREST ACTIVE-SITE POCKET RESIDUE
# ============================================================

def identify_nearest_active_site_residue(
    residue_position
):
    """
    Identify the validated active-site pocket residue that is
    structurally closest to the mutated residue.

    This annotation is retained for quality control and future
    biological interpretation.
    """

    if pd.isna(residue_position):

        return np.nan


    residue_position = int(residue_position)


    if residue_position not in ca_coordinates:

        return np.nan


    mutation_coordinate = (
        ca_coordinates[residue_position]
    )


    distance_dict = {}


    for pocket_position, pocket_coordinate in (
        active_site_coordinates.items()
    ):

        distance_dict[pocket_position] = (
            np.linalg.norm(
                mutation_coordinate -
                pocket_coordinate
            )
        )


    nearest_position = min(
        distance_dict,
        key=distance_dict.get
    )


    return nearest_position


# ============================================================
# 12. CALCULATE THE NEW STRUCTURAL FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING ACTIVE-SITE POCKET DISTANCES")
print("=" * 70)


df["Distance_to_Active_Site_Pocket"] = (
    df["Structural_Residue_Position"]
    .apply(
        calculate_distance_to_active_site_pocket
    )
)


df["Nearest_Active_Site_Pocket_Residue"] = (
    df["Structural_Residue_Position"]
    .apply(
        identify_nearest_active_site_residue
    )
)


# ============================================================
# 13. QUALITY CONTROL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("FEATURE QUALITY CONTROL")
print("=" * 70)


resolved_count = (
    df["Distance_to_Active_Site_Pocket"]
    .notna()
    .sum()
)


unresolved_count = (
    df["Distance_to_Active_Site_Pocket"]
    .isna()
    .sum()
)


print(
    f"\nMutations with structural distance available: "
    f"{resolved_count}"
)


print(
    f"Mutations without resolved structural coordinates: "
    f"{unresolved_count}"
)


if resolved_count > 0:

    print(
        f"\nMinimum distance: "
        f"{df['Distance_to_Active_Site_Pocket'].min():.3f} Å"
    )

    print(
        f"Maximum distance: "
        f"{df['Distance_to_Active_Site_Pocket'].max():.3f} Å"
    )

    print(
        f"Mean distance: "
        f"{df['Distance_to_Active_Site_Pocket'].mean():.3f} Å"
    )

    print(
        f"Median distance: "
        f"{df['Distance_to_Active_Site_Pocket'].median():.3f} Å"
    )


# ============================================================
# 14. SANITY CHECK:
# ACTIVE-SITE POCKET RESIDUES MUST HAVE ZERO DISTANCE
# ============================================================

print("\n" + "=" * 70)
print("ACTIVE-SITE POCKET DISTANCE SANITY CHECK")
print("=" * 70)


for position in ACTIVE_SITE_POCKET_RESIDUES:

    matching_rows = df[
        df["Structural_Residue_Position"] == position
    ]


    distance_values = matching_rows[
        "Distance_to_Active_Site_Pocket"
    ].dropna()


    if len(distance_values) == 0:

        print(
            f"\nPosition {position}: "
            "No mutation rows found."
        )

        continue


    minimum_distance = distance_values.min()


    print(
        f"\nPosition {position}:"
    )

    print(
        f"Minimum mutation distance: "
        f"{minimum_distance:.6f} Å"
    )

    print(
        "Expected behavior: approximately 0 Å "
        "because this position belongs to the defined "
        "active-site pocket."
    )


# ============================================================
# 15. CHECK FOR INVALID NEGATIVE DISTANCES
# ============================================================

negative_distances = df[
    df["Distance_to_Active_Site_Pocket"] < 0
]


if len(negative_distances) > 0:

    raise ValueError(
        "\nNegative distances were detected. "
        "Euclidean distances cannot be negative."
    )


print(
    "\nNo negative distance values detected."
)


# ============================================================
# 16. DISPLAY EXAMPLE RESULTS
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE STRUCTURAL FEATURES")
print("=" * 70)


display(
    df[
        [
            MUTATION_COLUMN,
            "Distance_to_Metal_Site",
            "Distance_to_Active_Site_Pocket",
            "Nearest_Active_Site_Pocket_Residue"
        ]
    ].head(20)
)


# ============================================================
# 17. SUMMARIZE UNIQUE RESIDUE POSITIONS
# ============================================================

position_summary = (
    df[
        [
            "Structural_Residue_Position",
            "Distance_to_Active_Site_Pocket",
            "Nearest_Active_Site_Pocket_Residue"
        ]
    ]
    .dropna(
        subset=[
            "Distance_to_Active_Site_Pocket"
        ]
    )
    .drop_duplicates(
        subset=[
            "Structural_Residue_Position"
        ]
    )
    .sort_values(
        "Structural_Residue_Position"
    )
)


print(
    f"\nUnique residue positions with calculated "
    f"active-site pocket distances: "
    f"{len(position_summary)}"
)


# ============================================================
# 18. REMOVE TEMPORARY STRUCTURAL MAPPING COLUMNS
# ============================================================

df.drop(
    columns=[
        "Structural_Residue_Position",
        "Structural_WT_Residue"
    ],
    inplace=True
)


# ============================================================
# 19. SAVE THE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 20. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 11C COMPLETE")
print("=" * 70)


print(
    f"\nOutput file saved successfully:\n{OUTPUT_FILE}"
)


print(
    f"\nFinal dataset rows: {len(df)}"
)


print(
    f"Final dataset columns: {len(df.columns)}"
)


print(
    "\nNew primary feature:"
)

print(
    "  Distance_to_Active_Site_Pocket"
)


print(
    "\nNew auxiliary annotation:"
)

print(
    "  Nearest_Active_Site_Pocket_Residue"
)


print(
    "\nDistance unit: Angstrom (Å)"
)


print(
    "\nStructural reference:"
)

print(
    "  PDB: 4NQ2"
)

print(
    "  Chain: A"
)


print(
    "\nValidated core active-site pocket residues:"
)

print(
    "  F62, Y67, W87, H114, H116, D118, "
    "H179, C198, H240"
)


print(
    "\nResidues without resolved coordinates remain NaN."
)


print(
    "\nNext recommended step:"
)

print(
    "  Part 11D — Distance to the L3 active-site loop."
)

======================================================================
PART 11C — DISTANCE TO THE ACTIVE-SITE POCKET
======================================================================

Input dataset found: VIM2_Part11B_Metal_Site_Distance.csv
PDB structure found: 4NQ2.pdb

======================================================================
DATASET SUMMARY
======================================================================

Total mutation rows: 5016
Total columns: 41

======================================================================
STRUCTURE SUMMARY
======================================================================

Structural reference: 4NQ2
Target chain: A

Residues with resolved C-alpha coordinates: 230

======================================================================
ACTIVE-SITE POCKET RESIDUE VALIDATION
======================================================================
Residue 62: Expected=F, PDB=F, Match=True
Residue 67: Expected=Y, PDB=Y, Match=True
Residue 87: Expected=W, PDB=W, Match=True
Residue 114: Expected=H, PDB=H, Match=True
Residue 116: Expected=H, PDB=H, Match=True
Residue 118: Expected=D, PDB=D, Match=True
Residue 179: Expected=H, PDB=H, Match=True
Residue 198: Expected=C, PDB=C, Match=True
Residue 240: Expected=H, PDB=H, Match=True

All 9 active-site pocket residues were successfully validated.

======================================================================
CALCULATING ACTIVE-SITE POCKET DISTANCES
======================================================================

======================================================================
FEATURE QUALITY CONTROL
======================================================================

Mutations with structural distance available: 4335
Mutations without resolved structural coordinates: 681

Minimum distance: 0.000 Å
Maximum distance: 25.624 Å
Mean distance: 11.359 Å
Median distance: 11.096 Å

======================================================================
ACTIVE-SITE POCKET DISTANCE SANITY CHECK
======================================================================

Position 62:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

Position 67:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

Position 87:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

Position 114:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

Position 116:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

Position 118:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

Position 179:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

Position 198:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

Position 240:
Minimum mutation distance: 0.000000 Å
Expected behavior: approximately 0 Å because this position belongs to the defined active-site pocket.

No negative distance values detected.

======================================================================
EXAMPLE STRUCTURAL FEATURES
======================================================================

,Mutation,Distance_to_Metal_Site,Distance_to_Active_Site_Pocket,Nearest_Active_Site_Pocket_Residue
0,M1A,NaN,NaN,NaN
1,M1C,NaN,NaN,NaN
2,M1D,NaN,NaN,NaN
3,M1E,NaN,NaN,NaN
4,M1F,NaN,NaN,NaN
5,M1G,NaN,NaN,NaN
6,M1H,NaN,NaN,NaN
7,M1I,NaN,NaN,NaN
8,M1K,NaN,NaN,NaN
9,M1L,NaN,NaN,NaN
10,M1N,NaN,NaN,NaN
11,M1P,NaN,NaN,NaN
12,M1Q,NaN,NaN,NaN
13,M1R,NaN,NaN,NaN
14,M1S,NaN,NaN,NaN
15,M1T,NaN,NaN,NaN
16,M1V,NaN,NaN,NaN
17,M1W,NaN,NaN,NaN
18,M1Y,NaN,NaN,NaN
19,F2A,NaN,NaN,NaN

Unique residue positions with calculated active-site pocket distances: 230

======================================================================
PART 11C COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part11C_Active_Site_Pocket_Distance.csv

Final dataset rows: 5016
Final dataset columns: 43

New primary feature:
  Distance_to_Active_Site_Pocket

New auxiliary annotation:
  Nearest_Active_Site_Pocket_Residue

Distance unit: Angstrom (Å)

Structural reference:
  PDB: 4NQ2
  Chain: A

Validated core active-site pocket residues:
  F62, Y67, W87, H114, H116, D118, H179, C198, H240

Residues without resolved coordinates remain NaN.

Next recommended step:
  Part 11D — Distance to the L3 active-site loop.

In [ ]:
# @title
# ============================================================
# PART 11D
# STRUCTURAL FEATURE ENGINEERING:
# DISTANCE TO THE L3 ACTIVE-SITE LOOP
#
# This script calculates the minimum three-dimensional distance
# between each mutated residue and the validated L3 loop of VIM-2
# using the 4NQ2 crystal structure.
#
# Structural reference:
# PDB ID: 4NQ2
# Chain: A
#
# Validated L3 loop:
# Residues 60–68
#
# Distance definition:
# Minimum Euclidean distance between the C-alpha atom of the
# mutated residue and the C-alpha atom of any residue in L3.
#
# Residues without resolved coordinates in 4NQ2 are assigned NaN.
# No artificial structural values are imputed.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os
import re
import numpy as np
import pandas as pd

from Bio.PDB import PDBParser


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part11C_Active_Site_Pocket_Distance.csv"
)

OUTPUT_FILE = (
    "VIM2_Part11D_L3_Distance.csv"
)

PDB_FILE = "4NQ2.pdb"

TARGET_CHAIN = "A"

MUTATION_COLUMN = "Mutation"


# ============================================================
# 3. DEFINE THE VALIDATED L3 LOOP
# ============================================================

# Previous sequence-to-PDB validation showed a 100% direct
# identity match across the L3 loop.
#
# L3:
# Q60 - S61 - F62 - D63 - G64 - A65 - V66 - Y67 - P68
#
# Therefore, the validated L3 structural region is:
#
# 60–68

L3_RESIDUES = list(
    range(60, 69)
)


# Expected residue identities are retained for structural QC.

EXPECTED_L3_IDENTITIES = {
    60: "Q",
    61: "S",
    62: "F",
    63: "D",
    64: "G",
    65: "A",
    66: "V",
    67: "Y",
    68: "P"
}


# ============================================================
# 4. VALIDATE INPUT FILES
# ============================================================

print("=" * 70)
print("PART 11D — DISTANCE TO THE L3 ACTIVE-SITE LOOP")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        f"\nInput dataset was not found:\n{INPUT_FILE}"
    )


if not os.path.exists(PDB_FILE):

    raise FileNotFoundError(
        f"\nPDB structure was not found:\n{PDB_FILE}"
    )


print(
    f"\nInput dataset found: {INPUT_FILE}"
)

print(
    f"PDB structure found: {PDB_FILE}"
)


# ============================================================
# 5. LOAD DATASET
# ============================================================

df = pd.read_csv(
    INPUT_FILE
)


print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)

print(
    f"\nTotal mutation rows: {len(df)}"
)

print(
    f"Total columns: {len(df.columns)}"
)


if MUTATION_COLUMN not in df.columns:

    raise ValueError(
        f"\nRequired mutation column "
        f"'{MUTATION_COLUMN}' was not found."
    )


# ============================================================
# 6. PARSE MUTATION POSITIONS
# ============================================================

mutation_pattern = re.compile(
    r"^([A-Z])(\d+)([A-Z])$"
)


def extract_mutation_position(
    mutation
):
    """
    Extract the numerical residue position
    from standard mutation notation.

    Example:
    Y67A -> 67
    """

    if pd.isna(mutation):

        return np.nan


    mutation = str(
        mutation
    ).strip()


    match = mutation_pattern.match(
        mutation
    )


    if match:

        return int(
            match.group(2)
        )


    return np.nan


df["Structural_Residue_Position"] = (
    df[MUTATION_COLUMN]
    .apply(
        extract_mutation_position
    )
)


# ============================================================
# 7. LOAD 4NQ2 STRUCTURE
# ============================================================

parser = PDBParser(
    QUIET=True
)


structure = parser.get_structure(
    "VIM2",
    PDB_FILE
)


model = structure[0]


if TARGET_CHAIN not in model:

    available_chains = [
        chain.id
        for chain in model
    ]

    raise ValueError(
        f"\nTarget chain '{TARGET_CHAIN}' "
        f"was not found.\n"
        f"Available chains: "
        f"{available_chains}"
    )


chain = model[
    TARGET_CHAIN
]


print("\n" + "=" * 70)
print("STRUCTURE SUMMARY")
print("=" * 70)

print(
    "\nPDB ID: 4NQ2"
)

print(
    f"Target chain: {TARGET_CHAIN}"
)


# ============================================================
# 8. EXTRACT RESOLVED C-ALPHA COORDINATES
# ============================================================

ca_coordinates = {}

pdb_residue_names = {}


for residue in chain:

    # Keep standard amino-acid residues only.
    if residue.id[0] != " ":

        continue


    residue_position = residue.id[1]


    # Only residues with resolved C-alpha coordinates
    # can participate in the distance calculation.
    if "CA" not in residue:

        continue


    ca_coordinates[
        residue_position
    ] = (
        residue["CA"]
        .coord
        .astype(float)
    )


    pdb_residue_names[
        residue_position
    ] = residue.get_resname()


print(
    f"\nResolved C-alpha residues: "
    f"{len(ca_coordinates)}"
)


# ============================================================
# 9. THREE-LETTER TO ONE-LETTER RESIDUE MAPPING
# ============================================================

one_letter_mapping = {

    "ALA": "A",
    "ARG": "R",
    "ASN": "N",
    "ASP": "D",
    "CYS": "C",
    "GLN": "Q",
    "GLU": "E",
    "GLY": "G",
    "HIS": "H",
    "ILE": "I",
    "LEU": "L",
    "LYS": "K",
    "MET": "M",
    "PHE": "F",
    "PRO": "P",
    "SER": "S",
    "THR": "T",
    "TRP": "W",
    "TYR": "Y",
    "VAL": "V"
}


# ============================================================
# 10. VALIDATE L3 LOOP AGAINST THE PDB
# ============================================================

print("\n" + "=" * 70)
print("L3 LOOP STRUCTURAL VALIDATION")
print("=" * 70)


l3_coordinates = {}

missing_l3_residues = []

identity_mismatches = []


for position in L3_RESIDUES:

    # Check structural availability.
    if position not in ca_coordinates:

        missing_l3_residues.append(
            position
        )

        print(
            f"Residue {position}: "
            "NOT AVAILABLE"
        )

        continue


    # Convert PDB residue identity to one-letter code.
    pdb_three_letter = (
        pdb_residue_names[
            position
        ]
    )


    pdb_one_letter = (
        one_letter_mapping.get(
            pdb_three_letter,
            "?"
        )
    )


    expected_identity = (
        EXPECTED_L3_IDENTITIES[
            position
        ]
    )


    identity_match = (
        pdb_one_letter ==
        expected_identity
    )


    print(
        f"Position {position}: "
        f"Expected={expected_identity}, "
        f"PDB={pdb_one_letter}, "
        f"Match={identity_match}"
    )


    if not identity_match:

        identity_mismatches.append(
            position
        )


    l3_coordinates[
        position
    ] = ca_coordinates[
        position
    ]


# Stop if the validated loop is incomplete.

if len(missing_l3_residues) > 0:

    raise ValueError(
        "\nMissing L3 residues in the PDB:\n"
        f"{missing_l3_residues}"
    )


if len(identity_mismatches) > 0:

    raise ValueError(
        "\nL3 sequence/PDB identity mismatch detected "
        "at positions:\n"
        f"{identity_mismatches}"
    )


print(
    "\nAll L3 residues are structurally resolved "
    "and sequence-validated."
)


print(
    f"L3 residues validated: "
    f"{len(l3_coordinates)} / "
    f"{len(L3_RESIDUES)}"
)


# ============================================================
# 11. CALCULATE DISTANCE TO L3
# ============================================================

def calculate_distance_to_L3(
    residue_position
):
    """
    Calculate the minimum C-alpha distance between
    a mutation position and the validated L3 loop.

    Distance is reported in Angstroms (Å).

    NaN is returned when the mutated residue does not
    have resolved coordinates in the reference structure.
    """

    if pd.isna(
        residue_position
    ):

        return np.nan


    residue_position = int(
        residue_position
    )


    # No structural coordinate -> no distance.
    if residue_position not in ca_coordinates:

        return np.nan


    mutation_coordinate = (
        ca_coordinates[
            residue_position
        ]
    )


    distances = []


    for l3_position, l3_coordinate in (
        l3_coordinates.items()
    ):

        distance = np.linalg.norm(
            mutation_coordinate -
            l3_coordinate
        )


        distances.append(
            distance
        )


    return float(
        np.min(
            distances
        )
    )


# ============================================================
# 12. IDENTIFY THE NEAREST L3 RESIDUE
# ============================================================

def identify_nearest_L3_residue(
    residue_position
):
    """
    Identify the closest L3 residue for each mutation.
    """

    if pd.isna(
        residue_position
    ):

        return np.nan


    residue_position = int(
        residue_position
    )


    if residue_position not in ca_coordinates:

        return np.nan


    mutation_coordinate = (
        ca_coordinates[
            residue_position
        ]
    )


    distance_dict = {}


    for l3_position, l3_coordinate in (
        l3_coordinates.items()
    ):

        distance_dict[
            l3_position
        ] = np.linalg.norm(
            mutation_coordinate -
            l3_coordinate
        )


    return min(
        distance_dict,
        key=distance_dict.get
    )


# ============================================================
# 13. CALCULATE THE NEW FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING L3 DISTANCES")
print("=" * 70)


df[
    "Distance_to_L3_Loop"
] = (
    df[
        "Structural_Residue_Position"
    ]
    .apply(
        calculate_distance_to_L3
    )
)


df[
    "Nearest_L3_Residue"
] = (
    df[
        "Structural_Residue_Position"
    ]
    .apply(
        identify_nearest_L3_residue
    )
)


# ============================================================
# 14. QUALITY CONTROL
# ============================================================

print("\n" + "=" * 70)
print("FEATURE QUALITY CONTROL")
print("=" * 70)


resolved_count = (
    df[
        "Distance_to_L3_Loop"
    ]
    .notna()
    .sum()
)


unresolved_count = (
    df[
        "Distance_to_L3_Loop"
    ]
    .isna()
    .sum()
)


print(
    f"\nMutations with structural L3 distance: "
    f"{resolved_count}"
)


print(
    f"Mutations without resolved coordinates: "
    f"{unresolved_count}"
)


if resolved_count > 0:

    print(
        f"\nMinimum L3 distance: "
        f"{df['Distance_to_L3_Loop'].min():.3f} Å"
    )


    print(
        f"Maximum L3 distance: "
        f"{df['Distance_to_L3_Loop'].max():.3f} Å"
    )


    print(
        f"Mean L3 distance: "
        f"{df['Distance_to_L3_Loop'].mean():.3f} Å"
    )


    print(
        f"Median L3 distance: "
        f"{df['Distance_to_L3_Loop'].median():.3f} Å"
    )


# ============================================================
# 15. SANITY CHECK
# ============================================================

# Every residue belonging to L3 should have a distance of
# approximately 0 Å to the L3 loop itself.

print("\n" + "=" * 70)
print("L3 DISTANCE SANITY CHECK")
print("=" * 70)


for position in L3_RESIDUES:

    matching_rows = df[
        df[
            "Structural_Residue_Position"
        ] == position
    ]


    distance_values = (
        matching_rows[
            "Distance_to_L3_Loop"
        ]
        .dropna()
    )


    if len(distance_values) == 0:

        print(
            f"\nPosition {position}: "
            "No mutation rows found."
        )

        continue


    minimum_distance = (
        distance_values.min()
    )


    print(
        f"\nPosition {position}: "
        f"minimum distance = "
        f"{minimum_distance:.6f} Å"
    )


# ============================================================
# 16. CHECK FOR NEGATIVE DISTANCES
# ============================================================

negative_distances = df[
    df[
        "Distance_to_L3_Loop"
    ] < 0
]


if len(
    negative_distances
) > 0:

    raise ValueError(
        "\nNegative distances detected. "
        "This is mathematically impossible for "
        "Euclidean distances."
    )


print(
    "\nNo negative distances detected."
)


# ============================================================
# 17. DISPLAY EXAMPLE RESULTS
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE L3 STRUCTURAL FEATURES")
print("=" * 70)


display(
    df[
        [
            MUTATION_COLUMN,
            "Distance_to_Metal_Site",
            "Distance_to_Active_Site_Pocket",
            "Distance_to_L3_Loop",
            "Nearest_L3_Residue"
        ]
    ]
    .head(20)
)


# ============================================================
# 18. UNIQUE POSITION SUMMARY
# ============================================================

position_summary = (
    df[
        [
            "Structural_Residue_Position",
            "Distance_to_L3_Loop",
            "Nearest_L3_Residue"
        ]
    ]
    .dropna(
        subset=[
            "Distance_to_L3_Loop"
        ]
    )
    .drop_duplicates(
        subset=[
            "Structural_Residue_Position"
        ]
    )
    .sort_values(
        "Structural_Residue_Position"
    )
)


print(
    f"\nUnique residue positions with calculated "
    f"L3 distances: "
    f"{len(position_summary)}"
)


# ============================================================
# 19. REMOVE TEMPORARY COLUMN
# ============================================================

df.drop(
    columns=[
        "Structural_Residue_Position"
    ],
    inplace=True
)


# ============================================================
# 20. SAVE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 21. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 11D COMPLETE")
print("=" * 70)


print(
    f"\nOutput file saved successfully:"
)

print(
    f"{OUTPUT_FILE}"
)


print(
    f"\nFinal dataset rows: "
    f"{len(df)}"
)


print(
    f"Final dataset columns: "
    f"{len(df.columns)}"
)


print(
    "\nNew primary feature:"
)

print(
    "  Distance_to_L3_Loop"
)


print(
    "\nNew auxiliary annotation:"
)

print(
    "  Nearest_L3_Residue"
)


print(
    "\nL3 definition:"
)

print(
    "  Residues 60–68"
)


print(
    "\nStructural reference:"
)

print(
    "  PDB: 4NQ2"
)

print(
    "  Chain: A"
)


print(
    "\nResidues without resolved coordinates remain NaN."
)


print(
    "\nNext step:"
)

print(
    "  Part 11E — Distance to the L10 active-site loop."
)

======================================================================
PART 11D — DISTANCE TO THE L3 ACTIVE-SITE LOOP
======================================================================

Input dataset found: VIM2_Part11C_Active_Site_Pocket_Distance.csv
PDB structure found: 4NQ2.pdb

======================================================================
DATASET SUMMARY
======================================================================

Total mutation rows: 5016
Total columns: 43

======================================================================
STRUCTURE SUMMARY
======================================================================

PDB ID: 4NQ2
Target chain: A

Resolved C-alpha residues: 230

======================================================================
L3 LOOP STRUCTURAL VALIDATION
======================================================================
Position 60: Expected=Q, PDB=Q, Match=True
Position 61: Expected=S, PDB=S, Match=True
Position 62: Expected=F, PDB=F, Match=True
Position 63: Expected=D, PDB=D, Match=True
Position 64: Expected=G, PDB=G, Match=True
Position 65: Expected=A, PDB=A, Match=True
Position 66: Expected=V, PDB=V, Match=True
Position 67: Expected=Y, PDB=Y, Match=True
Position 68: Expected=P, PDB=P, Match=True

All L3 residues are structurally resolved and sequence-validated.
L3 residues validated: 9 / 9

======================================================================
CALCULATING L3 DISTANCES
======================================================================

======================================================================
FEATURE QUALITY CONTROL
======================================================================

Mutations with structural L3 distance: 4335
Mutations without resolved coordinates: 681

Minimum L3 distance: 0.000 Å
Maximum L3 distance: 30.918 Å
Mean L3 distance: 18.154 Å
Median L3 distance: 19.267 Å

======================================================================
L3 DISTANCE SANITY CHECK
======================================================================

Position 60: minimum distance = 0.000000 Å

Position 61: minimum distance = 0.000000 Å

Position 62: minimum distance = 0.000000 Å

Position 63: minimum distance = 0.000000 Å

Position 64: minimum distance = 0.000000 Å

Position 65: minimum distance = 0.000000 Å

Position 66: minimum distance = 0.000000 Å

Position 67: minimum distance = 0.000000 Å

Position 68: minimum distance = 0.000000 Å

No negative distances detected.

======================================================================
EXAMPLE L3 STRUCTURAL FEATURES
======================================================================

,Mutation,Distance_to_Metal_Site,Distance_to_Active_Site_Pocket,Distance_to_L3_Loop,Nearest_L3_Residue
0,M1A,NaN,NaN,NaN,NaN
1,M1C,NaN,NaN,NaN,NaN
2,M1D,NaN,NaN,NaN,NaN
3,M1E,NaN,NaN,NaN,NaN
4,M1F,NaN,NaN,NaN,NaN
5,M1G,NaN,NaN,NaN,NaN
6,M1H,NaN,NaN,NaN,NaN
7,M1I,NaN,NaN,NaN,NaN
8,M1K,NaN,NaN,NaN,NaN
9,M1L,NaN,NaN,NaN,NaN
10,M1N,NaN,NaN,NaN,NaN
11,M1P,NaN,NaN,NaN,NaN
12,M1Q,NaN,NaN,NaN,NaN
13,M1R,NaN,NaN,NaN,NaN
14,M1S,NaN,NaN,NaN,NaN
15,M1T,NaN,NaN,NaN,NaN
16,M1V,NaN,NaN,NaN,NaN
17,M1W,NaN,NaN,NaN,NaN
18,M1Y,NaN,NaN,NaN,NaN
19,F2A,NaN,NaN,NaN,NaN

Unique residue positions with calculated L3 distances: 230

======================================================================
PART 11D COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part11D_L3_Distance.csv

Final dataset rows: 5016
Final dataset columns: 45

New primary feature:
  Distance_to_L3_Loop

New auxiliary annotation:
  Nearest_L3_Residue

L3 definition:
  Residues 60–68

Structural reference:
  PDB: 4NQ2
  Chain: A

Residues without resolved coordinates remain NaN.

Next step:
  Part 11E — Distance to the L10 active-site loop.

In [ ]:
# @title
# ============================================================
# QUICK QC — CHECK STRUCTURAL FEATURE COVERAGE
# ============================================================

import re
import pandas as pd

df = pd.read_csv(
    "VIM2_Part11D_L3_Distance.csv"
)

# Extract mutation position
df["Position"] = (
    df["Mutation"]
    .astype(str)
    .str.extract(r"^[A-Z](\d+)[A-Z]$")[0]
    .astype(float)
)

# Unique positions with / without L3 distance
coverage = (
    df.groupby("Position")
      ["Distance_to_L3_Loop"]
      .first()
      .reset_index()
)

print("=" * 70)
print("L3 STRUCTURAL FEATURE COVERAGE")
print("=" * 70)

print(
    "\nTotal unique mutation positions:",
    coverage["Position"].nunique()
)

print(
    "Positions with L3 distance:",
    coverage["Distance_to_L3_Loop"].notna().sum()
)

print(
    "Positions without L3 distance:",
    coverage["Distance_to_L3_Loop"].isna().sum()
)

print("\nPositions WITHOUT structural distance:")

print(
    coverage.loc[
        coverage["Distance_to_L3_Loop"].isna(),
        "Position"
    ].tolist()
)

print("\nExpected unresolved positions:")

print(
    list(range(1, 32)) +
    list(range(262, 267))
)

======================================================================
L3 STRUCTURAL FEATURE COVERAGE
======================================================================

Total unique mutation positions: 266
Positions with L3 distance: 230
Positions without L3 distance: 36

Positions WITHOUT structural distance:
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 262.0, 263.0, 264.0, 265.0, 266.0]

Expected unresolved positions:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 262, 263, 264, 265, 266]

In [ ]:
# @title
# ============================================================
# PART 11E
# STRUCTURAL FEATURE ENGINEERING:
# DISTANCE TO THE L10 ACTIVE-SITE LOOP
#
# This script calculates the minimum three-dimensional distance
# between each mutated residue and the validated L10 loop of VIM-2
# using the 4NQ2 crystal structure.
#
# Structural reference:
# PDB ID: 4NQ2
# Chain: A
#
# Validated L10 loop:
# Residues 201–214
#
# Distance definition:
# Minimum Euclidean distance between the C-alpha atom of the
# mutated residue and the C-alpha atom of any residue in L10.
#
# Residues without resolved coordinates in 4NQ2 remain NaN.
# No artificial structural values are generated.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os
import re
import numpy as np
import pandas as pd

from Bio.PDB import PDBParser


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part11D_L3_Distance.csv"
)

OUTPUT_FILE = (
    "VIM2_Part11E_L10_Distance.csv"
)

PDB_FILE = "4NQ2.pdb"

TARGET_CHAIN = "A"

MUTATION_COLUMN = "Mutation"


# ============================================================
# 3. DEFINE VALIDATED L10 LOOP
# ============================================================

# The sequence-to-PDB validation previously confirmed a 100%
# direct identity match across the L10 region.
#
# Validated L10 region:
#
# 201–214
#
# The corresponding sequence was:
#
# Y201 - E202 - L203 - S204 - R205 - T206 - S207
# - A208 - G209 - N210 - V211 - A212 - D213 - A214

L10_RESIDUES = list(
    range(201, 215)
)


EXPECTED_L10_IDENTITIES = {
    201: "Y",
    202: "E",
    203: "L",
    204: "S",
    205: "R",
    206: "T",
    207: "S",
    208: "A",
    209: "G",
    210: "N",
    211: "V",
    212: "A",
    213: "D",
    214: "A"
}


# ============================================================
# 4. VALIDATE INPUT FILES
# ============================================================

print("=" * 70)
print("PART 11E — DISTANCE TO THE L10 ACTIVE-SITE LOOP")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        f"\nInput dataset was not found:\n{INPUT_FILE}"
    )


if not os.path.exists(PDB_FILE):

    raise FileNotFoundError(
        f"\nPDB structure was not found:\n{PDB_FILE}"
    )


print(
    f"\nInput dataset found: {INPUT_FILE}"
)

print(
    f"PDB structure found: {PDB_FILE}"
)


# ============================================================
# 5. LOAD DATASET
# ============================================================

df = pd.read_csv(
    INPUT_FILE
)


print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)

print(
    f"\nTotal mutation rows: {len(df)}"
)

print(
    f"Total columns: {len(df.columns)}"
)


if MUTATION_COLUMN not in df.columns:

    raise ValueError(
        f"\nRequired mutation column "
        f"'{MUTATION_COLUMN}' was not found."
    )


# ============================================================
# 6. PARSE MUTATION POSITIONS
# ============================================================

mutation_pattern = re.compile(
    r"^([A-Z])(\d+)([A-Z])$"
)


def extract_mutation_position(
    mutation
):
    """
    Extract numerical residue position
    from standard amino-acid substitution notation.

    Example:
    Y201A -> 201
    """

    if pd.isna(mutation):

        return np.nan


    mutation = str(
        mutation
    ).strip()


    match = mutation_pattern.match(
        mutation
    )


    if match:

        return int(
            match.group(2)
        )


    return np.nan


df["Structural_Residue_Position"] = (
    df[MUTATION_COLUMN]
    .apply(
        extract_mutation_position
    )
)


# ============================================================
# 7. LOAD 4NQ2 STRUCTURE
# ============================================================

parser = PDBParser(
    QUIET=True
)


structure = parser.get_structure(
    "VIM2",
    PDB_FILE
)


model = structure[0]


if TARGET_CHAIN not in model:

    available_chains = [
        chain.id
        for chain in model
    ]

    raise ValueError(
        f"\nTarget chain '{TARGET_CHAIN}' "
        f"was not found.\n"
        f"Available chains: "
        f"{available_chains}"
    )


chain = model[
    TARGET_CHAIN
]


print("\n" + "=" * 70)
print("STRUCTURE SUMMARY")
print("=" * 70)

print(
    "\nPDB ID: 4NQ2"
)

print(
    f"Target chain: {TARGET_CHAIN}"
)


# ============================================================
# 8. EXTRACT RESOLVED C-ALPHA COORDINATES
# ============================================================

ca_coordinates = {}

pdb_residue_names = {}


for residue in chain:

    # Keep standard amino-acid residues only.
    if residue.id[0] != " ":

        continue


    residue_position = residue.id[1]


    # Only residues with a resolved C-alpha atom
    # can be used for distance calculations.
    if "CA" not in residue:

        continue


    ca_coordinates[
        residue_position
    ] = (
        residue["CA"]
        .coord
        .astype(float)
    )


    pdb_residue_names[
        residue_position
    ] = residue.get_resname()


print(
    f"\nResolved C-alpha residues: "
    f"{len(ca_coordinates)}"
)


# ============================================================
# 9. THREE-LETTER TO ONE-LETTER MAPPING
# ============================================================

one_letter_mapping = {

    "ALA": "A",
    "ARG": "R",
    "ASN": "N",
    "ASP": "D",
    "CYS": "C",
    "GLN": "Q",
    "GLU": "E",
    "GLY": "G",
    "HIS": "H",
    "ILE": "I",
    "LEU": "L",
    "LYS": "K",
    "MET": "M",
    "PHE": "F",
    "PRO": "P",
    "SER": "S",
    "THR": "T",
    "TRP": "W",
    "TYR": "Y",
    "VAL": "V"
}


# ============================================================
# 10. VALIDATE L10 LOOP AGAINST THE PDB
# ============================================================

print("\n" + "=" * 70)
print("L10 LOOP STRUCTURAL VALIDATION")
print("=" * 70)


l10_coordinates = {}

missing_l10_residues = []

identity_mismatches = []


for position in L10_RESIDUES:

    # Check whether structural coordinates exist.
    if position not in ca_coordinates:

        missing_l10_residues.append(
            position
        )

        print(
            f"Residue {position}: "
            "NOT AVAILABLE"
        )

        continue


    pdb_three_letter = (
        pdb_residue_names[
            position
        ]
    )


    pdb_one_letter = (
        one_letter_mapping.get(
            pdb_three_letter,
            "?"
        )
    )


    expected_identity = (
        EXPECTED_L10_IDENTITIES[
            position
        ]
    )


    identity_match = (
        pdb_one_letter ==
        expected_identity
    )


    print(
        f"Position {position}: "
        f"Expected={expected_identity}, "
        f"PDB={pdb_one_letter}, "
        f"Match={identity_match}"
    )


    if not identity_match:

        identity_mismatches.append(
            position
        )


    l10_coordinates[
        position
    ] = ca_coordinates[
        position
    ]


# Stop if the validated loop is structurally incomplete.

if len(
    missing_l10_residues
) > 0:

    raise ValueError(
        "\nMissing L10 residues in the PDB:\n"
        f"{missing_l10_residues}"
    )


if len(
    identity_mismatches
) > 0:

    raise ValueError(
        "\nL10 sequence/PDB identity mismatch detected "
        "at positions:\n"
        f"{identity_mismatches}"
    )


print(
    "\nAll L10 residues are structurally resolved "
    "and sequence-validated."
)


print(
    f"L10 residues validated: "
    f"{len(l10_coordinates)} / "
    f"{len(L10_RESIDUES)}"
)


# ============================================================
# 11. CALCULATE DISTANCE TO L10
# ============================================================

def calculate_distance_to_L10(
    residue_position
):
    """
    Calculate the minimum C-alpha distance between
    a mutation position and the validated L10 loop.

    Distance unit:
    Angstroms (Å)

    NaN:
    Returned when the mutated residue does not have
    resolved structural coordinates in 4NQ2.
    """

    if pd.isna(
        residue_position
    ):

        return np.nan


    residue_position = int(
        residue_position
    )


    if residue_position not in ca_coordinates:

        return np.nan


    mutation_coordinate = (
        ca_coordinates[
            residue_position
        ]
    )


    distances = []


    for l10_position, l10_coordinate in (
        l10_coordinates.items()
    ):

        distance = np.linalg.norm(
            mutation_coordinate -
            l10_coordinate
        )


        distances.append(
            distance
        )


    return float(
        np.min(
            distances
        )
    )


# ============================================================
# 12. IDENTIFY NEAREST L10 RESIDUE
# ============================================================

def identify_nearest_L10_residue(
    residue_position
):
    """
    Identify the closest validated L10 residue
    for each mutation position.
    """

    if pd.isna(
        residue_position
    ):

        return np.nan


    residue_position = int(
        residue_position
    )


    if residue_position not in ca_coordinates:

        return np.nan


    mutation_coordinate = (
        ca_coordinates[
            residue_position
        ]
    )


    distance_dict = {}


    for l10_position, l10_coordinate in (
        l10_coordinates.items()
    ):

        distance_dict[
            l10_position
        ] = np.linalg.norm(
            mutation_coordinate -
            l10_coordinate
        )


    return min(
        distance_dict,
        key=distance_dict.get
    )


# ============================================================
# 13. CALCULATE NEW FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING L10 DISTANCES")
print("=" * 70)


df[
    "Distance_to_L10_Loop"
] = (
    df[
        "Structural_Residue_Position"
    ]
    .apply(
        calculate_distance_to_L10
    )
)


df[
    "Nearest_L10_Residue"
] = (
    df[
        "Structural_Residue_Position"
    ]
    .apply(
        identify_nearest_L10_residue
    )
)


# ============================================================
# 14. QUALITY CONTROL
# ============================================================

print("\n" + "=" * 70)
print("FEATURE QUALITY CONTROL")
print("=" * 70)


resolved_count = (
    df[
        "Distance_to_L10_Loop"
    ]
    .notna()
    .sum()
)


unresolved_count = (
    df[
        "Distance_to_L10_Loop"
    ]
    .isna()
    .sum()
)


print(
    f"\nMutations with structural L10 distance: "
    f"{resolved_count}"
)


print(
    f"Mutations without resolved coordinates: "
    f"{unresolved_count}"
)


if resolved_count > 0:

    print(
        f"\nMinimum L10 distance: "
        f"{df['Distance_to_L10_Loop'].min():.3f} Å"
    )


    print(
        f"Maximum L10 distance: "
        f"{df['Distance_to_L10_Loop'].max():.3f} Å"
    )


    print(
        f"Mean L10 distance: "
        f"{df['Distance_to_L10_Loop'].mean():.3f} Å"
    )


    print(
        f"Median L10 distance: "
        f"{df['Distance_to_L10_Loop'].median():.3f} Å"
    )


# ============================================================
# 15. SANITY CHECK
# ============================================================

# Every residue belonging to L10 should have approximately
# zero distance to the L10 loop itself.

print("\n" + "=" * 70)
print("L10 DISTANCE SANITY CHECK")
print("=" * 70)


for position in L10_RESIDUES:

    matching_rows = df[
        df[
            "Structural_Residue_Position"
        ] == position
    ]


    distance_values = (
        matching_rows[
            "Distance_to_L10_Loop"
        ]
        .dropna()
    )


    if len(distance_values) == 0:

        print(
            f"\nPosition {position}: "
            "No mutation rows found."
        )

        continue


    minimum_distance = (
        distance_values.min()
    )


    print(
        f"\nPosition {position}: "
        f"minimum distance = "
        f"{minimum_distance:.6f} Å"
    )


# ============================================================
# 16. CHECK FOR NEGATIVE DISTANCES
# ============================================================

negative_distances = df[
    df[
        "Distance_to_L10_Loop"
    ] < 0
]


if len(
    negative_distances
) > 0:

    raise ValueError(
        "\nNegative distances detected. "
        "Euclidean distances cannot be negative."
    )


print(
    "\nNo negative distances detected."
)


# ============================================================
# 17. DISPLAY EXAMPLE RESULTS
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE L10 STRUCTURAL FEATURES")
print("=" * 70)


display(
    df[
        [
            MUTATION_COLUMN,
            "Distance_to_Metal_Site",
            "Distance_to_Active_Site_Pocket",
            "Distance_to_L3_Loop",
            "Distance_to_L10_Loop",
            "Nearest_L10_Residue"
        ]
    ]
    .head(20)
)


# ============================================================
# 18. UNIQUE POSITION SUMMARY
# ============================================================

position_summary = (
    df[
        [
            "Structural_Residue_Position",
            "Distance_to_L10_Loop",
            "Nearest_L10_Residue"
        ]
    ]
    .dropna(
        subset=[
            "Distance_to_L10_Loop"
        ]
    )
    .drop_duplicates(
        subset=[
            "Structural_Residue_Position"
        ]
    )
    .sort_values(
        "Structural_Residue_Position"
    )
)


print(
    f"\nUnique residue positions with calculated "
    f"L10 distances: "
    f"{len(position_summary)}"
)


# ============================================================
# 19. REMOVE TEMPORARY COLUMN
# ============================================================

df.drop(
    columns=[
        "Structural_Residue_Position"
    ],
    inplace=True
)


# ============================================================
# 20. SAVE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 21. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 11E COMPLETE")
print("=" * 70)


print(
    f"\nOutput file saved successfully:"
)

print(
    OUTPUT_FILE
)


print(
    f"\nFinal dataset rows: "
    f"{len(df)}"
)


print(
    f"Final dataset columns: "
    f"{len(df.columns)}"
)


print(
    "\nNew primary feature:"
)

print(
    "  Distance_to_L10_Loop"
)


print(
    "\nNew auxiliary annotation:"
)

print(
    "  Nearest_L10_Residue"
)


print(
    "\nL10 definition:"
)

print(
    "  Residues 201–214"
)


print(
    "\nDistance unit:"
)

print(
    "  Angstrom (Å)"
)


print(
    "\nStructural reference:"
)

print(
    "  PDB: 4NQ2"
)

print(
    "  Chain: A"
)


print(
    "\nResidues without resolved coordinates remain NaN."
)


print(
    "\nNext step:"
)

print(
    "  Part 11F — Solvent Accessible Surface Area (SASA)."
)

======================================================================
PART 11E — DISTANCE TO THE L10 ACTIVE-SITE LOOP
======================================================================

Input dataset found: VIM2_Part11D_L3_Distance.csv
PDB structure found: 4NQ2.pdb

======================================================================
DATASET SUMMARY
======================================================================

Total mutation rows: 5016
Total columns: 45

======================================================================
STRUCTURE SUMMARY
======================================================================

PDB ID: 4NQ2
Target chain: A

Resolved C-alpha residues: 230

======================================================================
L10 LOOP STRUCTURAL VALIDATION
======================================================================
Position 201: Expected=Y, PDB=Y, Match=True
Position 202: Expected=E, PDB=E, Match=True
Position 203: Expected=L, PDB=L, Match=True
Position 204: Expected=S, PDB=S, Match=True
Position 205: Expected=R, PDB=R, Match=True
Position 206: Expected=T, PDB=T, Match=True
Position 207: Expected=S, PDB=S, Match=True
Position 208: Expected=A, PDB=A, Match=True
Position 209: Expected=G, PDB=G, Match=True
Position 210: Expected=N, PDB=N, Match=True
Position 211: Expected=V, PDB=V, Match=True
Position 212: Expected=A, PDB=A, Match=True
Position 213: Expected=D, PDB=D, Match=True
Position 214: Expected=A, PDB=A, Match=True

All L10 residues are structurally resolved and sequence-validated.
L10 residues validated: 14 / 14

======================================================================
CALCULATING L10 DISTANCES
======================================================================

======================================================================
FEATURE QUALITY CONTROL
======================================================================

Mutations with structural L10 distance: 4335
Mutations without resolved coordinates: 681

Minimum L10 distance: 0.000 Å
Maximum L10 distance: 31.614 Å
Mean L10 distance: 15.540 Å
Median L10 distance: 15.581 Å

======================================================================
L10 DISTANCE SANITY CHECK
======================================================================

Position 201: minimum distance = 0.000000 Å

Position 202: minimum distance = 0.000000 Å

Position 203: minimum distance = 0.000000 Å

Position 204: minimum distance = 0.000000 Å

Position 205: minimum distance = 0.000000 Å

Position 206: minimum distance = 0.000000 Å

Position 207: minimum distance = 0.000000 Å

Position 208: minimum distance = 0.000000 Å

Position 209: minimum distance = 0.000000 Å

Position 210: minimum distance = 0.000000 Å

Position 211: minimum distance = 0.000000 Å

Position 212: minimum distance = 0.000000 Å

Position 213: minimum distance = 0.000000 Å

Position 214: minimum distance = 0.000000 Å

No negative distances detected.

======================================================================
EXAMPLE L10 STRUCTURAL FEATURES
======================================================================

,Mutation,Distance_to_Metal_Site,Distance_to_Active_Site_Pocket,Distance_to_L3_Loop,Distance_to_L10_Loop,Nearest_L10_Residue
0,M1A,NaN,NaN,NaN,NaN,NaN
1,M1C,NaN,NaN,NaN,NaN,NaN
2,M1D,NaN,NaN,NaN,NaN,NaN
3,M1E,NaN,NaN,NaN,NaN,NaN
4,M1F,NaN,NaN,NaN,NaN,NaN
5,M1G,NaN,NaN,NaN,NaN,NaN
6,M1H,NaN,NaN,NaN,NaN,NaN
7,M1I,NaN,NaN,NaN,NaN,NaN
8,M1K,NaN,NaN,NaN,NaN,NaN
9,M1L,NaN,NaN,NaN,NaN,NaN
10,M1N,NaN,NaN,NaN,NaN,NaN
11,M1P,NaN,NaN,NaN,NaN,NaN
12,M1Q,NaN,NaN,NaN,NaN,NaN
13,M1R,NaN,NaN,NaN,NaN,NaN
14,M1S,NaN,NaN,NaN,NaN,NaN
15,M1T,NaN,NaN,NaN,NaN,NaN
16,M1V,NaN,NaN,NaN,NaN,NaN
17,M1W,NaN,NaN,NaN,NaN,NaN
18,M1Y,NaN,NaN,NaN,NaN,NaN
19,F2A,NaN,NaN,NaN,NaN,NaN

Unique residue positions with calculated L10 distances: 230

======================================================================
PART 11E COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part11E_L10_Distance.csv

Final dataset rows: 5016
Final dataset columns: 47

New primary feature:
  Distance_to_L10_Loop

New auxiliary annotation:
  Nearest_L10_Residue

L10 definition:
  Residues 201–214

Distance unit:
  Angstrom (Å)

Structural reference:
  PDB: 4NQ2
  Chain: A

Residues without resolved coordinates remain NaN.

Next step:
  Part 11F — Solvent Accessible Surface Area (SASA).

In [ ]:
# @title
# ============================================================
# PART 11F
# STRUCTURAL FEATURE ENGINEERING:
# SOLVENT ACCESSIBLE SURFACE AREA (SASA)
#
# This script calculates residue-level solvent accessible
# surface area (SASA) for VIM-2 using the 4NQ2 crystal
# structure.
#
# SASA is calculated using the Shrake-Rupley algorithm
# implemented in Biopython.
#
# For every mutation, the SASA value corresponds to the
# wild-type residue at that mutation position.
#
# Structural reference:
# PDB ID: 4NQ2
# Chain: A
#
# SASA unit:
# Angstrom squared (Å²)
#
# Important:
# Residues without resolved structural coordinates remain NaN.
# No artificial structural values are generated.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os
import re
import numpy as np
import pandas as pd

from Bio.PDB import PDBParser
from Bio.PDB.SASA import ShrakeRupley


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part11E_L10_Distance.csv"
)

OUTPUT_FILE = (
    "VIM2_Part11F_SASA.csv"
)

PDB_FILE = "4NQ2.pdb"

TARGET_CHAIN = "A"

MUTATION_COLUMN = "Mutation"


# ============================================================
# 3. SASA PARAMETERS
# ============================================================

# Standard Shrake-Rupley parameters.
#
# probe_radius:
# Radius of the solvent probe in Angstroms.
#
# n_points:
# Number of points used to approximate the solvent-accessible
# surface of each atom.
#
# A relatively high point density is used to obtain stable
# residue-level SASA estimates.

PROBE_RADIUS = 1.4

N_POINTS = 960


# ============================================================
# 4. VALIDATE INPUT FILES
# ============================================================

print("=" * 70)
print("PART 11F — SOLVENT ACCESSIBLE SURFACE AREA (SASA)")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        f"\nInput dataset was not found:\n{INPUT_FILE}"
    )


if not os.path.exists(PDB_FILE):

    raise FileNotFoundError(
        f"\nPDB structure was not found:\n{PDB_FILE}"
    )


print(
    f"\nInput dataset found: {INPUT_FILE}"
)

print(
    f"PDB structure found: {PDB_FILE}"
)


# ============================================================
# 5. LOAD DATASET
# ============================================================

df = pd.read_csv(
    INPUT_FILE
)


print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)

print(
    f"\nTotal mutation rows: {len(df)}"
)

print(
    f"Total columns: {len(df.columns)}"
)


if MUTATION_COLUMN not in df.columns:

    raise ValueError(
        f"\nRequired mutation column "
        f"'{MUTATION_COLUMN}' was not found."
    )


# ============================================================
# 6. PARSE MUTATION POSITIONS
# ============================================================

mutation_pattern = re.compile(
    r"^([A-Z])(\d+)([A-Z])$"
)


def extract_mutation_position(
    mutation
):
    """
    Extract the numerical residue position
    from standard mutation notation.

    Example:
    Y67A -> 67
    H114R -> 114
    """

    if pd.isna(mutation):

        return np.nan


    mutation = str(
        mutation
    ).strip()


    match = mutation_pattern.match(
        mutation
    )


    if match:

        return int(
            match.group(2)
        )


    return np.nan


def extract_wild_type_residue(
    mutation
):
    """
    Extract the wild-type amino-acid identity.

    Example:
    Y67A -> Y
    """

    if pd.isna(mutation):

        return np.nan


    mutation = str(
        mutation
    ).strip()


    match = mutation_pattern.match(
        mutation
    )


    if match:

        return match.group(1)


    return np.nan


df["Structural_Residue_Position"] = (
    df[MUTATION_COLUMN]
    .apply(
        extract_mutation_position
    )
)


df["Structural_WT_Residue"] = (
    df[MUTATION_COLUMN]
    .apply(
        extract_wild_type_residue
    )
)


# ============================================================
# 7. LOAD 4NQ2 STRUCTURE
# ============================================================

parser = PDBParser(
    QUIET=True
)


structure = parser.get_structure(
    "VIM2",
    PDB_FILE
)


model = structure[0]


if TARGET_CHAIN not in model:

    available_chains = [
        chain.id
        for chain in model
    ]

    raise ValueError(
        f"\nTarget chain '{TARGET_CHAIN}' "
        f"was not found.\n"
        f"Available chains: "
        f"{available_chains}"
    )


chain = model[
    TARGET_CHAIN
]


print("\n" + "=" * 70)
print("STRUCTURE SUMMARY")
print("=" * 70)

print(
    "\nPDB ID: 4NQ2"
)

print(
    f"Target chain: {TARGET_CHAIN}"
)


# ============================================================
# 8. CREATE SHRake-RUPLEY SASA CALCULATOR
# ============================================================

# SASA is calculated on the complete structural model.
#
# The Shrake-Rupley algorithm estimates the solvent-accessible
# surface by sampling points on the surface of each atom and
# determining which points are accessible to the solvent probe.

sr = ShrakeRupley(
    probe_radius=PROBE_RADIUS,
    n_points=N_POINTS
)


# ============================================================
# 9. CALCULATE SASA FOR THE STRUCTURE
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING STRUCTURAL SASA")
print("=" * 70)

print(
    f"\nProbe radius: "
    f"{PROBE_RADIUS:.2f} Å"
)

print(
    f"Surface sampling points per atom: "
    f"{N_POINTS}"
)


# Calculate SASA at the residue level.
#
# level="R" means that Biopython stores the calculated
# SASA value for each residue.

sr.compute(
    model,
    level="R"
)


print(
    "\nShrake-Rupley SASA calculation completed."
)


# ============================================================
# 10. EXTRACT RESIDUE-LEVEL SASA VALUES
# ============================================================

residue_sasa = {}

pdb_residue_names = {}


for residue in chain:

    # Keep standard amino-acid residues only.
    if residue.id[0] != " ":

        continue


    residue_position = residue.id[1]


    # Residues without atoms / structural coordinates
    # cannot provide a meaningful SASA estimate.
    if len(residue.child_list) == 0:

        continue


    residue_sasa[
        residue_position
    ] = float(
        residue.sasa
    )


    pdb_residue_names[
        residue_position
    ] = residue.get_resname()


print(
    f"\nResidues with calculated SASA: "
    f"{len(residue_sasa)}"
)


# ============================================================
# 11. RESIDUE IDENTITY MAPPING
# ============================================================

one_letter_mapping = {

    "ALA": "A",
    "ARG": "R",
    "ASN": "N",
    "ASP": "D",
    "CYS": "C",
    "GLN": "Q",
    "GLU": "E",
    "GLY": "G",
    "HIS": "H",
    "ILE": "I",
    "LEU": "L",
    "LYS": "K",
    "MET": "M",
    "PHE": "F",
    "PRO": "P",
    "SER": "S",
    "THR": "T",
    "TRP": "W",
    "TYR": "Y",
    "VAL": "V"
}


# ============================================================
# 12. STRUCTURAL IDENTITY VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("DATASET-TO-PDB SASA IDENTITY VALIDATION")
print("=" * 70)


identity_matches = 0

identity_mismatches = []

validated_positions = 0


for position in sorted(
    residue_sasa.keys()
):

    pdb_three_letter = (
        pdb_residue_names[
            position
        ]
    )


    pdb_one_letter = (
        one_letter_mapping.get(
            pdb_three_letter,
            "?"
        )
    )


    dataset_rows = df[
        df[
            "Structural_Residue_Position"
        ] == position
    ]


    if len(dataset_rows) == 0:

        continue


    dataset_identity = (
        dataset_rows[
            "Structural_WT_Residue"
        ]
        .dropna()
        .iloc[0]
    )


    validated_positions += 1


    if (
        pdb_one_letter ==
        dataset_identity
    ):

        identity_matches += 1

    else:

        identity_mismatches.append(
            {
                "Position": position,
                "Dataset_WT": dataset_identity,
                "PDB_Position": position,
                "PDB_WT": pdb_one_letter
            }
        )


print(
    f"\nPositions validated: "
    f"{validated_positions}"
)

print(
    f"Exact WT identity matches: "
    f"{identity_matches}"
)


print(
    f"Identity mismatches: "
    f"{len(identity_mismatches)}"
)


# ------------------------------------------------------------
# Report mismatches without stopping the analysis.
#
# The previously validated structure-to-sequence comparison
# identified one numbering discrepancy around position 184.
#
# This discrepancy should be retained as a QC annotation rather
# than causing the entire SASA calculation to fail.
# ------------------------------------------------------------

if len(identity_mismatches) > 0:

    print(
        "\nIMPORTANT — STRUCTURAL NUMBERING MISMATCHES:"
    )

    mismatch_df = pd.DataFrame(
        identity_mismatches
    )

    display(
        mismatch_df
    )

else:

    print(
        "\nNo dataset-to-PDB identity mismatches detected."
    )


# ------------------------------------------------------------
# The mismatch is reported but does not invalidate SASA for
# the remaining structurally resolved residues.
# ------------------------------------------------------------

print(
    "\nSASA calculation will continue using the resolved "
    "4NQ2 residue coordinates."
)


# ============================================================
# 13. MAP SASA TO MUTATION POSITIONS
# ============================================================

def get_residue_sasa(
    residue_position
):
    """
    Return residue-level SASA for the corresponding
    wild-type residue.

    NaN is returned for positions without resolved
    structural information.
    """

    if pd.isna(
        residue_position
    ):

        return np.nan


    residue_position = int(
        residue_position
    )


    if residue_position not in residue_sasa:

        return np.nan


    return residue_sasa[
        residue_position
    ]


df[
    "SASA"
] = (
    df[
        "Structural_Residue_Position"
    ]
    .apply(
        get_residue_sasa
    )
)


# ============================================================
# 14. OPTIONAL BINARY ACCESSIBILITY ANNOTATION
# ============================================================

# This auxiliary annotation is intentionally NOT used as the
# primary feature.
#
# The continuous SASA value contains more information than a
# binary exposed/buried classification.
#
# Therefore, we retain SASA as the main structural feature and
# do not impose an arbitrary universal SASA threshold here.

print(
    "\nPrimary feature retained as continuous residue-level SASA."
)


# ============================================================
# 15. QUALITY CONTROL
# ============================================================

print("\n" + "=" * 70)
print("SASA FEATURE QUALITY CONTROL")
print("=" * 70)


resolved_count = (
    df[
        "SASA"
    ]
    .notna()
    .sum()
)


unresolved_count = (
    df[
        "SASA"
    ]
    .isna()
    .sum()
)


print(
    f"\nMutations with structural SASA: "
    f"{resolved_count}"
)


print(
    f"Mutations without resolved coordinates: "
    f"{unresolved_count}"
)


if resolved_count > 0:

    print(
        f"\nMinimum SASA: "
        f"{df['SASA'].min():.3f} Å²"
    )


    print(
        f"Maximum SASA: "
        f"{df['SASA'].max():.3f} Å²"
    )


    print(
        f"Mean SASA: "
        f"{df['SASA'].mean():.3f} Å²"
    )


    print(
        f"Median SASA: "
        f"{df['SASA'].median():.3f} Å²"
    )


# ============================================================
# 16. CHECK FOR INVALID NEGATIVE SASA
# ============================================================

negative_sasa = df[
    df[
        "SASA"
    ] < 0
]


if len(
    negative_sasa
) > 0:

    raise ValueError(
        "\nNegative SASA values were detected. "
        "SASA cannot be negative."
    )


print(
    "\nNo negative SASA values detected."
)


# ============================================================
# 17. STRUCTURAL COVERAGE SUMMARY
# ============================================================

unique_position_sasa = (
    df[
        [
            "Structural_Residue_Position",
            "SASA"
        ]
    ]
    .drop_duplicates(
        subset=[
            "Structural_Residue_Position"
        ]
    )
)


positions_with_sasa = (
    unique_position_sasa[
        "SASA"
    ]
    .notna()
    .sum()
)


positions_without_sasa = (
    unique_position_sasa[
        "SASA"
    ]
    .isna()
    .sum()
)


print("\n" + "=" * 70)
print("STRUCTURAL SASA COVERAGE")
print("=" * 70)


print(
    f"\nUnique mutation positions: "
    f"{len(unique_position_sasa)}"
)


print(
    f"Positions with SASA: "
    f"{positions_with_sasa}"
)


print(
    f"Positions without SASA: "
    f"{positions_without_sasa}"
)


print(
    "\nExpected unresolved structural positions:"
)

print(
    list(range(1, 32)) +
    list(range(262, 267))
)


# ============================================================
# 18. DISPLAY EXAMPLE RESULTS
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE SASA FEATURES")
print("=" * 70)


display(
    df[
        [
            MUTATION_COLUMN,
            "Distance_to_Metal_Site",
            "Distance_to_Active_Site_Pocket",
            "Distance_to_L3_Loop",
            "Distance_to_L10_Loop",
            "SASA"
        ]
    ]
    .head(20)
)


# ============================================================
# 19. REMOVE TEMPORARY COLUMNS
# ============================================================

df.drop(
    columns=[
        "Structural_Residue_Position",
        "Structural_WT_Residue"
    ],
    inplace=True
)


# ============================================================
# 20. SAVE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 21. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 11F COMPLETE")
print("=" * 70)


print(
    f"\nOutput file saved successfully:"
)

print(
    OUTPUT_FILE
)


print(
    f"\nFinal dataset rows: "
    f"{len(df)}"
)


print(
    f"Final dataset columns: "
    f"{len(df.columns)}"
)


print(
    "\nNew primary feature:"
)

print(
    "  SASA"
)


print(
    "\nSASA unit:"
)

print(
    "  Å²"
)


print(
    "\nSASA method:"
)

print(
    "  Shrake-Rupley"
)


print(
    "\nProbe radius:"
)

print(
    f"  {PROBE_RADIUS:.2f} Å"
)


print(
    "\nStructural reference:"
)

print(
    "  PDB: 4NQ2"
)

print(
    "  Chain: A"
)


print(
    "\nResidues without resolved coordinates remain NaN."
)


print(
    "\nNext step:"
)

print(
    "  Part 11G — Secondary Structure."
)

======================================================================
PART 11F — SOLVENT ACCESSIBLE SURFACE AREA (SASA)
======================================================================

Input dataset found: VIM2_Part11E_L10_Distance.csv
PDB structure found: 4NQ2.pdb

======================================================================
DATASET SUMMARY
======================================================================

Total mutation rows: 5016
Total columns: 47

======================================================================
STRUCTURE SUMMARY
======================================================================

PDB ID: 4NQ2
Target chain: A

======================================================================
CALCULATING STRUCTURAL SASA
======================================================================

Probe radius: 1.40 Å
Surface sampling points per atom: 960

Shrake-Rupley SASA calculation completed.

Residues with calculated SASA: 230

======================================================================
DATASET-TO-PDB SASA IDENTITY VALIDATION
======================================================================

Positions validated: 230
Exact WT identity matches: 229
Identity mismatches: 1

IMPORTANT — STRUCTURAL NUMBERING MISMATCHES:

   Position Dataset_WT  PDB_Position PDB_WT
0       185          I           185      V

SASA calculation will continue using the resolved 4NQ2 residue coordinates.

Primary feature retained as continuous residue-level SASA.

======================================================================
SASA FEATURE QUALITY CONTROL
======================================================================

Mutations with structural SASA: 4335
Mutations without resolved coordinates: 681

Minimum SASA: 0.000 Å²
Maximum SASA: 152.417 Å²
Mean SASA: 19.666 Å²
Median SASA: 3.460 Å²

No negative SASA values detected.

======================================================================
STRUCTURAL SASA COVERAGE
======================================================================

Unique mutation positions: 266
Positions with SASA: 230
Positions without SASA: 36

Expected unresolved structural positions:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 262, 263, 264, 265, 266]

======================================================================
EXAMPLE SASA FEATURES
======================================================================

,Mutation,Distance_to_Metal_Site,Distance_to_Active_Site_Pocket,Distance_to_L3_Loop,Distance_to_L10_Loop,SASA
0,M1A,NaN,NaN,NaN,NaN,NaN
1,M1C,NaN,NaN,NaN,NaN,NaN
2,M1D,NaN,NaN,NaN,NaN,NaN
3,M1E,NaN,NaN,NaN,NaN,NaN
4,M1F,NaN,NaN,NaN,NaN,NaN
5,M1G,NaN,NaN,NaN,NaN,NaN
6,M1H,NaN,NaN,NaN,NaN,NaN
7,M1I,NaN,NaN,NaN,NaN,NaN
8,M1K,NaN,NaN,NaN,NaN,NaN
9,M1L,NaN,NaN,NaN,NaN,NaN
10,M1N,NaN,NaN,NaN,NaN,NaN
11,M1P,NaN,NaN,NaN,NaN,NaN
12,M1Q,NaN,NaN,NaN,NaN,NaN
13,M1R,NaN,NaN,NaN,NaN,NaN
14,M1S,NaN,NaN,NaN,NaN,NaN
15,M1T,NaN,NaN,NaN,NaN,NaN
16,M1V,NaN,NaN,NaN,NaN,NaN
17,M1W,NaN,NaN,NaN,NaN,NaN
18,M1Y,NaN,NaN,NaN,NaN,NaN
19,F2A,NaN,NaN,NaN,NaN,NaN

======================================================================
PART 11F COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part11F_SASA.csv

Final dataset rows: 5016
Final dataset columns: 48

New primary feature:
  SASA

SASA unit:
  Å²

SASA method:
  Shrake-Rupley

Probe radius:
  1.40 Å

Structural reference:
  PDB: 4NQ2
  Chain: A

Residues without resolved coordinates remain NaN.

Next step:
  Part 11G — Secondary Structure.

In [ ]:
# ============================================================
# INSTALL DSSP FOR SECONDARY-STRUCTURE ASSIGNMENT
#
# DSSP (Define Secondary Structure of Proteins) is required
# to assign residue-level secondary-structure states from
# the experimentally resolved 3D protein structure.
#
# This installation is required before running Part 11G.
# ============================================================

!apt-get update -qq

!apt-get install -y dssp

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libboost-iostreams1.74.0 libboost-program-options1.74.0 libboost-regex1.74.0
  libcifpp-data libcifpp2
The following NEW packages will be installed:
  dssp libboost-iostreams1.74.0 libboost-program-options1.74.0
  libboost-regex1.74.0 libcifpp-data libcifpp2
0 upgraded, 6 newly installed, 0 to remove and 16 not upgraded.
Need to get 3,034 kB of archives.
After this operation, 22.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-iostreams1.74.0 amd64 1.74.0-14ubuntu3 [245 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-program-options1.74.0 amd64 1.74.0-14ubuntu3 [311 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libboost-regex1.74.0 amd64 1.74.0-14ubuntu3 [511 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libcifpp-data all 2.0.5-1build1 [437 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libcifpp2 amd64 2.0.5-1build1 [1,019 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 dssp amd64 4.0.4-1 [511 kB]
Fetched 3,034 kB in 1s (3,641 kB/s)
Preconfiguring packages ...
Selecting previously unselected package libboost-iostreams1.74.0:amd64.
(Reading database ... 118422 files and directories currently installed.)
Preparing to unpack .../0-libboost-iostreams1.74.0_1.74.0-14ubuntu3_amd64.deb ...
Unpacking libboost-iostreams1.74.0:amd64 (1.74.0-14ubuntu3) ...
Selecting previously unselected package libboost-program-options1.74.0:amd64.
Preparing to unpack .../1-libboost-program-options1.74.0_1.74.0-14ubuntu3_amd64.deb ...
Unpacking libboost-program-options1.74.0:amd64 (1.74.0-14ubuntu3) ...
Selecting previously unselected package libboost-regex1.74.0:amd64.
Preparing to unpack .../2-libboost-regex1.74.0_1.74.0-14ubuntu3_amd64.deb ...
Unpacking libboost-regex1.74.0:amd64 (1.74.0-14ubuntu3) ...
Selecting previously unselected package libcifpp-data.
Preparing to unpack .../3-libcifpp-data_2.0.5-1build1_all.deb ...
Unpacking libcifpp-data (2.0.5-1build1) ...
Selecting previously unselected package libcifpp2:amd64.
Preparing to unpack .../4-libcifpp2_2.0.5-1build1_amd64.deb ...
Unpacking libcifpp2:amd64 (2.0.5-1build1) ...
Selecting previously unselected package dssp.
Preparing to unpack .../5-dssp_4.0.4-1_amd64.deb ...
Unpacking dssp (4.0.4-1) ...
Setting up libboost-iostreams1.74.0:amd64 (1.74.0-14ubuntu3) ...
Setting up libboost-program-options1.74.0:amd64 (1.74.0-14ubuntu3) ...
Setting up libboost-regex1.74.0:amd64 (1.74.0-14ubuntu3) ...
Setting up libcifpp-data (2.0.5-1build1) ...
Setting up libcifpp2:amd64 (2.0.5-1build1) ...
Setting up dssp (4.0.4-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.14) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...

In [ ]:
# @title
# ============================================================
# PART 11G
# STRUCTURAL FEATURE ENGINEERING:
# SECONDARY STRUCTURE
#
# This script assigns secondary-structure annotations to VIM-2
# residues using the DSSP algorithm and the experimentally
# determined 4NQ2 structure.
#
# Structural reference:
# PDB ID: 4NQ2
# Chain: A
#
# DSSP secondary-structure states are collapsed into three
# machine-learning-friendly categories:
#
# Helix:
#     H = alpha helix
#     G = 3-10 helix
#     I = pi helix
#
# Sheet:
#     E = extended beta strand
#     B = isolated beta bridge
#
# Coil:
#     T = turn
#     S = bend
#     - = other / loop / irregular structure
#
# Residues without resolved coordinates remain NaN.
# No artificial structural annotations are generated.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os
import re
import shutil

import numpy as np
import pandas as pd

from Bio.PDB import PDBParser
from Bio.PDB.DSSP import DSSP


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part11F_SASA.csv"
)

OUTPUT_FILE = (
    "VIM2_Part11G_Secondary_Structure.csv"
)

PDB_FILE = "4NQ2.pdb"

TARGET_CHAIN = "A"

MUTATION_COLUMN = "Mutation"


# ============================================================
# 3. CHECK DSSP INSTALLATION
# ============================================================

print("=" * 70)
print("PART 11G — SECONDARY STRUCTURE")
print("=" * 70)


# DSSP may be installed under different executable names
# depending on the operating system and environment.

DSSP_EXECUTABLE = None


for executable_name in [
    "mkdssp",
    "dssp"
]:

    executable_path = shutil.which(
        executable_name
    )

    if executable_path is not None:

        DSSP_EXECUTABLE = executable_path

        print(
            f"\nDSSP executable detected: "
            f"{DSSP_EXECUTABLE}"
        )

        break


if DSSP_EXECUTABLE is None:

    raise FileNotFoundError(
        "\nDSSP executable was not found.\n\n"
        "In Google Colab, run this installation command "
        "in a separate cell first:\n\n"
        "!apt-get update -qq\n"
        "!apt-get install -y dssp\n\n"
        "Then rerun this Part 11G code."
    )


# ============================================================
# 4. VALIDATE INPUT FILES
# ============================================================

if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        f"\nInput dataset was not found:\n"
        f"{INPUT_FILE}"
    )


if not os.path.exists(PDB_FILE):

    raise FileNotFoundError(
        f"\nPDB structure was not found:\n"
        f"{PDB_FILE}"
    )


print(
    f"\nInput dataset found: "
    f"{INPUT_FILE}"
)

print(
    f"PDB structure found: "
    f"{PDB_FILE}"
)


# ============================================================
# 5. LOAD DATASET
# ============================================================

df = pd.read_csv(
    INPUT_FILE
)


print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)


print(
    f"\nTotal mutation rows: "
    f"{len(df)}"
)

print(
    f"Total columns: "
    f"{len(df.columns)}"
)


if MUTATION_COLUMN not in df.columns:

    raise ValueError(
        f"\nRequired mutation column "
        f"'{MUTATION_COLUMN}' was not found."
    )


# ============================================================
# 6. PARSE MUTATION POSITIONS
# ============================================================

mutation_pattern = re.compile(
    r"^([A-Z])(\d+)([A-Z])$"
)


def extract_mutation_position(
    mutation
):
    """
    Extract the numerical residue position from standard
    amino-acid substitution notation.

    Example:
    Y67A -> 67
    H114R -> 114
    """

    if pd.isna(mutation):

        return np.nan


    mutation = str(
        mutation
    ).strip()


    match = mutation_pattern.match(
        mutation
    )


    if match:

        return int(
            match.group(2)
        )


    return np.nan


df[
    "Structural_Residue_Position"
] = (
    df[MUTATION_COLUMN]
    .apply(
        extract_mutation_position
    )
)


# ============================================================
# 7. LOAD THE 4NQ2 STRUCTURE
# ============================================================

parser = PDBParser(
    QUIET=True
)


structure = parser.get_structure(
    "VIM2",
    PDB_FILE
)


model = structure[0]


if TARGET_CHAIN not in model:

    available_chains = [
        chain.id
        for chain in model
    ]

    raise ValueError(
        f"\nTarget chain '{TARGET_CHAIN}' "
        f"was not found.\n"
        f"Available chains: "
        f"{available_chains}"
    )


print("\n" + "=" * 70)
print("STRUCTURE SUMMARY")
print("=" * 70)


print(
    "\nPDB ID: 4NQ2"
)

print(
    f"Target chain: "
    f"{TARGET_CHAIN}"
)


# ============================================================
# 8. RUN DSSP
# ============================================================

print("\n" + "=" * 70)
print("RUNNING DSSP SECONDARY-STRUCTURE ASSIGNMENT")
print("=" * 70)


try:

    dssp = DSSP(
        model,
        PDB_FILE,
        dssp=DSSP_EXECUTABLE
    )


except Exception as error:

    raise RuntimeError(
        "\nDSSP failed to process the 4NQ2 structure.\n\n"
        f"Original error:\n{error}"
    )


print(
    "\nDSSP calculation completed successfully."
)


print(
    f"Total residues annotated by DSSP: "
    f"{len(dssp)}"
)


# ============================================================
# 9. DEFINE DSSP SECONDARY-STRUCTURE CATEGORIES
# ============================================================

# DSSP states:
#
# H = alpha helix
# B = isolated beta bridge
# E = extended beta strand
# G = 3-10 helix
# I = pi helix
# T = hydrogen-bonded turn
# S = bend
# - = other / loop / irregular structure


DSSP_TO_CATEGORY = {

    "H": "Helix",
    "G": "Helix",
    "I": "Helix",

    "E": "Sheet",
    "B": "Sheet",

    "T": "Coil",
    "S": "Coil",
    "-": "Coil"
}


# Numerical encoding for downstream machine-learning workflows.
#
# The categorical label remains the biologically interpretable
# primary feature. The numerical code is included only as an
# auxiliary representation.

SECONDARY_STRUCTURE_CODE = {

    "Helix": 1,
    "Sheet": 2,
    "Coil": 3
}


# ============================================================
# 10. EXTRACT DSSP ANNOTATIONS FOR CHAIN A
# ============================================================

print("\n" + "=" * 70)
print("EXTRACTING CHAIN A DSSP ANNOTATIONS")
print("=" * 70)


secondary_structure_raw = {}

secondary_structure_category = {}

pdb_residue_identity = {}


for dssp_key in dssp.keys():

    chain_id = dssp_key[0]

    residue_id = dssp_key[1]


    # Keep only the selected VIM-2 chain.
    if chain_id != TARGET_CHAIN:

        continue


    # Standard residue numbering.
    #
    # residue_id format:
    # (' ', residue_number, insertion_code)

    if residue_id[0] != " ":

        continue


    residue_position = residue_id[1]


    dssp_record = dssp[
        dssp_key
    ]


    # DSSP tuple index 2 contains the secondary-structure code.
    dssp_code = dssp_record[2]


    # DSSP may occasionally return a blank-like value.
    # Standardize such cases as irregular/coil structure.
    if (
        dssp_code is None
        or str(dssp_code).strip() == ""
    ):

        dssp_code = "-"


    dssp_code = str(
        dssp_code
    ).strip()


    if dssp_code not in DSSP_TO_CATEGORY:

        dssp_code = "-"


    secondary_structure_raw[
        residue_position
    ] = dssp_code


    secondary_structure_category[
        residue_position
    ] = DSSP_TO_CATEGORY[
        dssp_code
    ]


    # DSSP tuple index 1 contains the amino-acid identity.
    pdb_residue_identity[
        residue_position
    ] = dssp_record[1]


print(
    f"\nChain A residues with DSSP annotations: "
    f"{len(secondary_structure_category)}"
)


# ============================================================
# 11. DISPLAY RAW DSSP CATEGORY DISTRIBUTION
# ============================================================

raw_dssp_counts = (
    pd.Series(
        secondary_structure_raw
    )
    .value_counts()
    .sort_index()
)


print("\n" + "=" * 70)
print("RAW DSSP STATE DISTRIBUTION")
print("=" * 70)


print(
    raw_dssp_counts
)


# ============================================================
# 12. DISPLAY COLLAPSED CATEGORY DISTRIBUTION
# ============================================================

collapsed_category_counts = (
    pd.Series(
        secondary_structure_category
    )
    .value_counts()
)


print("\n" + "=" * 70)
print("COLLAPSED SECONDARY-STRUCTURE DISTRIBUTION")
print("=" * 70)


print(
    collapsed_category_counts
)


# ============================================================
# 13. DATASET-TO-DSSP POSITION VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("DATASET-TO-DSSP POSITION VALIDATION")
print("=" * 70)


unique_dataset_positions = sorted(
    df[
        "Structural_Residue_Position"
    ]
    .dropna()
    .unique()
)


dssp_positions = sorted(
    secondary_structure_category.keys()
)


common_positions = sorted(
    set(
        unique_dataset_positions
    ).intersection(
        set(
            dssp_positions
        )
    )
)


dataset_only_positions = sorted(
    set(
        unique_dataset_positions
    ).difference(
        set(
            dssp_positions
        )
    )
)


print(
    f"\nUnique mutation positions in dataset: "
    f"{len(unique_dataset_positions)}"
)


print(
    f"Positions annotated by DSSP: "
    f"{len(dssp_positions)}"
)


print(
    f"Positions shared by dataset and DSSP: "
    f"{len(common_positions)}"
)


print(
    f"Positions without DSSP structural annotation: "
    f"{len(dataset_only_positions)}"
)


print(
    "\nPositions without DSSP annotation:"
)

print(
    dataset_only_positions
)


# ============================================================
# 14. MAP SECONDARY STRUCTURE TO EACH MUTATION
# ============================================================

def get_secondary_structure(
    residue_position
):
    """
    Return the collapsed DSSP secondary-structure category
    for the corresponding residue position.

    Returns:
        Helix
        Sheet
        Coil
        NaN for unresolved structural positions
    """

    if pd.isna(
        residue_position
    ):

        return np.nan


    residue_position = int(
        residue_position
    )


    return secondary_structure_category.get(
        residue_position,
        np.nan
    )


def get_secondary_structure_code(
    secondary_structure
):
    """
    Convert the interpretable secondary-structure category
    into an auxiliary numerical representation.
    """

    if pd.isna(
        secondary_structure
    ):

        return np.nan


    return SECONDARY_STRUCTURE_CODE.get(
        secondary_structure,
        np.nan
    )


def get_raw_dssp_code(
    residue_position
):
    """
    Return the original DSSP secondary-structure code.

    This auxiliary feature preserves the full DSSP assignment
    before collapsing into Helix, Sheet, and Coil.
    """

    if pd.isna(
        residue_position
    ):

        return np.nan


    residue_position = int(
        residue_position
    )


    return secondary_structure_raw.get(
        residue_position,
        np.nan
    )


# Add the primary interpretable feature.

df[
    "Secondary_Structure"
] = (
    df[
        "Structural_Residue_Position"
    ]
    .apply(
        get_secondary_structure
    )
)


# Add the original DSSP state as an auxiliary annotation.

df[
    "DSSP_Secondary_Structure"
] = (
    df[
        "Structural_Residue_Position"
    ]
    .apply(
        get_raw_dssp_code
    )
)


# Add numerical encoding.

df[
    "Secondary_Structure_Code"
] = (
    df[
        "Secondary_Structure"
    ]
    .apply(
        get_secondary_structure_code
    )
)


# ============================================================
# 15. QUALITY CONTROL
# ============================================================

print("\n" + "=" * 70)
print("SECONDARY-STRUCTURE FEATURE QUALITY CONTROL")
print("=" * 70)


resolved_count = (
    df[
        "Secondary_Structure"
    ]
    .notna()
    .sum()
)


unresolved_count = (
    df[
        "Secondary_Structure"
    ]
    .isna()
    .sum()
)


print(
    f"\nMutations with secondary-structure annotation: "
    f"{resolved_count}"
)


print(
    f"Mutations without structural annotation: "
    f"{unresolved_count}"
)


# ============================================================
# 16. UNIQUE POSITION COVERAGE
# ============================================================

position_summary = (
    df[
        [
            "Structural_Residue_Position",
            "Secondary_Structure",
            "DSSP_Secondary_Structure"
        ]
    ]
    .drop_duplicates(
        subset=[
            "Structural_Residue_Position"
        ]
    )
    .sort_values(
        "Structural_Residue_Position"
    )
)


positions_with_annotation = (
    position_summary[
        "Secondary_Structure"
    ]
    .notna()
    .sum()
)


positions_without_annotation = (
    position_summary[
        "Secondary_Structure"
    ]
    .isna()
    .sum()
)


print("\n" + "=" * 70)
print("SECONDARY-STRUCTURE COVERAGE")
print("=" * 70)


print(
    f"\nUnique mutation positions: "
    f"{len(position_summary)}"
)


print(
    f"Positions with secondary-structure annotation: "
    f"{positions_with_annotation}"
)


print(
    f"Positions without secondary-structure annotation: "
    f"{positions_without_annotation}"
)


print(
    "\nExpected unresolved structural positions:"
)


expected_unresolved_positions = (
    list(range(1, 32))
    +
    list(range(262, 267))
)


print(
    expected_unresolved_positions
)


# ============================================================
# 17. CHECK STRUCTURAL COVERAGE CONSISTENCY
# ============================================================

actual_unresolved_positions = sorted(
    position_summary.loc[
        position_summary[
            "Secondary_Structure"
        ].isna(),
        "Structural_Residue_Position"
    ]
    .dropna()
    .astype(int)
    .tolist()
)


if (
    actual_unresolved_positions ==
    expected_unresolved_positions
):

    print(
        "\nStructural coverage check: PASSED"
    )


else:

    print(
        "\nWARNING — Structural coverage differs from the "
        "expected unresolved positions."
    )


    print(
        "\nActual unresolved positions:"
    )

    print(
        actual_unresolved_positions
    )


# ============================================================
# 18. CATEGORY DISTRIBUTION ACROSS UNIQUE POSITIONS
# ============================================================

print("\n" + "=" * 70)
print("SECONDARY-STRUCTURE DISTRIBUTION ACROSS POSITIONS")
print("=" * 70)


unique_structure_distribution = (
    position_summary[
        "Secondary_Structure"
    ]
    .value_counts(
        dropna=False
    )
)


print(
    unique_structure_distribution
)


# ============================================================
# 19. SANITY CHECK USING KNOWN FUNCTIONAL REGIONS
# ============================================================

print("\n" + "=" * 70)
print("FUNCTIONAL REGION SANITY CHECK")
print("=" * 70)


sanity_positions = [

    60, 61, 62, 63, 64,
    65, 66, 67, 68,

    114, 116, 118,
    179, 198, 240,

    201, 202, 203, 204,
    205, 206, 207, 208,
    209, 210, 211, 212,
    213, 214
]


sanity_records = []


for position in sanity_positions:

    if position in secondary_structure_category:

        sanity_records.append(
            {
                "Position": position,
                "Raw_DSSP":
                    secondary_structure_raw.get(
                        position,
                        np.nan
                    ),
                "Secondary_Structure":
                    secondary_structure_category.get(
                        position,
                        np.nan
                    )
            }
        )


sanity_df = pd.DataFrame(
    sanity_records
)


display(
    sanity_df
)


# ============================================================
# 20. DISPLAY EXAMPLE MUTATION-LEVEL RESULTS
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE SECONDARY-STRUCTURE FEATURES")
print("=" * 70)


display_columns = [

    MUTATION_COLUMN,

    "Distance_to_Metal_Site",

    "Distance_to_Active_Site_Pocket",

    "Distance_to_L3_Loop",

    "Distance_to_L10_Loop",

    "SASA",

    "Secondary_Structure",

    "DSSP_Secondary_Structure",

    "Secondary_Structure_Code"
]


# Keep only columns that actually exist.

display_columns = [

    column
    for column in display_columns
    if column in df.columns
]


display(
    df[
        display_columns
    ]
    .head(25)
)


# ============================================================
# 21. REMOVE TEMPORARY POSITION COLUMN
# ============================================================

df.drop(
    columns=[
        "Structural_Residue_Position"
    ],
    inplace=True
)


# ============================================================
# 22. SAVE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 23. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 11G COMPLETE")
print("=" * 70)


print(
    "\nOutput file saved successfully:"
)

print(
    OUTPUT_FILE
)


print(
    f"\nFinal dataset rows: "
    f"{len(df)}"
)


print(
    f"Final dataset columns: "
    f"{len(df.columns)}"
)


print(
    "\nNew primary feature:"
)

print(
    "  Secondary_Structure"
)


print(
    "\nNew auxiliary features:"
)

print(
    "  DSSP_Secondary_Structure"
)

print(
    "  Secondary_Structure_Code"
)


print(
    "\nSecondary-structure categories:"
)

print(
    "  Helix"
)

print(
    "  Sheet"
)

print(
    "  Coil"
)


print(
    "\nStructural annotation method:"
)

print(
    "  DSSP"
)


print(
    "\nStructural reference:"
)

print(
    "  PDB: 4NQ2"
)

print(
    "  Chain: A"
)


print(
    "\nResidues without resolved coordinates remain NaN."
)


print(
    "\nNext recommended step:"
)

print(
    "  Review the final structural feature coverage "
    "before adding additional sequence- or chemistry-based "
    "features."
)

======================================================================
PART 11G — SECONDARY STRUCTURE
======================================================================

DSSP executable detected: /usr/bin/mkdssp

Input dataset found: VIM2_Part11F_SASA.csv
PDB structure found: 4NQ2.pdb

======================================================================
DATASET SUMMARY
======================================================================

Total mutation rows: 5016
Total columns: 48

======================================================================
STRUCTURE SUMMARY
======================================================================

PDB ID: 4NQ2
Target chain: A

======================================================================
RUNNING DSSP SECONDARY-STRUCTURE ASSIGNMENT
======================================================================

DSSP calculation completed successfully.
Total residues annotated by DSSP: 230

======================================================================
EXTRACTING CHAIN A DSSP ANNOTATIONS
======================================================================

Chain A residues with DSSP annotations: 230

======================================================================
RAW DSSP STATE DISTRIBUTION
======================================================================
-    45
B     1
E    65
G     3
H    59
S    23
T    34
Name: count, dtype: int64

======================================================================
COLLAPSED SECONDARY-STRUCTURE DISTRIBUTION
======================================================================
Coil     102
Sheet     66
Helix     62
Name: count, dtype: int64

======================================================================
DATASET-TO-DSSP POSITION VALIDATION
======================================================================

Unique mutation positions in dataset: 266
Positions annotated by DSSP: 230
Positions shared by dataset and DSSP: 230
Positions without DSSP structural annotation: 36

Positions without DSSP annotation:
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(262), np.int64(263), np.int64(264), np.int64(265), np.int64(266)]

======================================================================
SECONDARY-STRUCTURE FEATURE QUALITY CONTROL
======================================================================

Mutations with secondary-structure annotation: 4335
Mutations without structural annotation: 681

======================================================================
SECONDARY-STRUCTURE COVERAGE
======================================================================

Unique mutation positions: 266
Positions with secondary-structure annotation: 230
Positions without secondary-structure annotation: 36

Expected unresolved structural positions:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 262, 263, 264, 265, 266]

Structural coverage check: PASSED

======================================================================
SECONDARY-STRUCTURE DISTRIBUTION ACROSS POSITIONS
======================================================================
Secondary_Structure
Coil     102
Sheet     66
Helix     62
NaN       36
Name: count, dtype: int64

======================================================================
FUNCTIONAL REGION SANITY CHECK
======================================================================

    Position Raw_DSSP Secondary_Structure
0         60        E               Sheet
1         61        E               Sheet
2         62        -                Coil
3         63        S                Coil
4         64        S                Coil
5         65        S                Coil
6         66        E               Sheet
7         67        E               Sheet
8         68        E               Sheet
9        114        S                Coil
10       116        S                Coil
11       118        H               Helix
12       179        S                Coil
13       198        T                Coil
14       240        S                Coil
15       201        -                Coil
16       202        -                Coil
17       203        T                Coil
18       204        T                Coil
19       205        -                Coil
20       206        -                Coil
21       207        S                Coil
22       208        -                Coil
23       209        -                Coil
24       210        -                Coil
25       211        -                Coil
26       212        T                Coil
27       213        T                Coil
28       214        -                Coil

======================================================================
EXAMPLE SECONDARY-STRUCTURE FEATURES
======================================================================

,Mutation,Distance_to_Metal_Site,Distance_to_Active_Site_Pocket,Distance_to_L3_Loop,Distance_to_L10_Loop,SASA,Secondary_Structure,DSSP_Secondary_Structure,Secondary_Structure_Code
0,M1A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,M1C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,M1D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,M1E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,M1F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,M1G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,M1H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,M1I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,M1K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,M1L,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,M1N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,M1P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,M1Q,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,M1R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,M1S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,M1T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,M1V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,M1W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,M1Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,F2A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,F2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,F2D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,F2E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,F2G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,F2H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
PART 11G COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part11G_Secondary_Structure.csv

Final dataset rows: 5016
Final dataset columns: 51

New primary feature:
  Secondary_Structure

New auxiliary features:
  DSSP_Secondary_Structure
  Secondary_Structure_Code

Secondary-structure categories:
  Helix
  Sheet
  Coil

Structural annotation method:
  DSSP

Structural reference:
  PDB: 4NQ2
  Chain: A

Residues without resolved coordinates remain NaN.

Next recommended step:
  Review the final structural feature coverage before adding additional sequence- or chemistry-based features.

In [ ]:
# @title
# ============================================================
# PART 11H
# FINAL STRUCTURAL FEATURE QUALITY CONTROL
#
# This script performs final quality-control checks for all
# structural features generated in Parts 11B–11G.
#
# No new biological feature is created.
# The purpose of this step is to verify:
#
# 1. Structural feature coverage across mutation positions
# 2. Consistency of unresolved structural positions
# 3. Missing-value patterns
# 4. Numerical feature ranges and distributions
# 5. Categorical feature distributions
# 6. Consistency across all structural annotations
#
# Structural reference:
# PDB ID: 4NQ2
# Chain: A
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os

import numpy as np
import pandas as pd


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part11G_Secondary_Structure.csv"
)

OUTPUT_FILE = (
    "VIM2_Part11H_Final_Structural_QC.csv"
)

MUTATION_COLUMN = "Mutation"


# ============================================================
# 3. VALIDATE INPUT FILE
# ============================================================

print("=" * 70)
print("PART 11H — FINAL STRUCTURAL FEATURE QUALITY CONTROL")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        f"\nInput file was not found:\n"
        f"{INPUT_FILE}"
    )


print(
    f"\nInput file found successfully:\n"
    f"{INPUT_FILE}"
)


# ============================================================
# 4. LOAD DATASET
# ============================================================

df = pd.read_csv(
    INPUT_FILE
)


print("\n" + "=" * 70)
print("DATASET SUMMARY")
print("=" * 70)


print(
    f"\nTotal mutation rows: "
    f"{len(df)}"
)

print(
    f"Total dataset columns: "
    f"{len(df.columns)}"
)


if MUTATION_COLUMN not in df.columns:

    raise ValueError(
        f"\nRequired mutation column "
        f"'{MUTATION_COLUMN}' was not found."
    )


# ============================================================
# 5. DEFINE STRUCTURAL FEATURES
# ============================================================

# Primary numerical structural features.

numerical_structural_features = [

    "Distance_to_Metal_Site",

    "Distance_to_Active_Site_Pocket",

    "Distance_to_L3_Loop",

    "Distance_to_L10_Loop",

    "SASA"
]


# Auxiliary categorical or annotation features.

categorical_structural_features = [

    "Nearest_Metal_Site_Residue",

    "Nearest_Active_Site_Pocket_Residue",

    "Nearest_L3_Residue",

    "Nearest_L10_Residue",

    "Secondary_Structure",

    "DSSP_Secondary_Structure"
]


# Auxiliary numerical encoding.

auxiliary_numerical_features = [

    "Secondary_Structure_Code"
]


# Combine all expected structural features.

all_structural_features = (

    numerical_structural_features
    +
    categorical_structural_features
    +
    auxiliary_numerical_features
)


# ============================================================
# 6. CHECK REQUIRED STRUCTURAL FEATURES
# ============================================================

print("\n" + "=" * 70)
print("STRUCTURAL FEATURE AVAILABILITY CHECK")
print("=" * 70)


missing_features = [

    feature
    for feature in all_structural_features
    if feature not in df.columns
]


available_features = [

    feature
    for feature in all_structural_features
    if feature in df.columns
]


print(
    f"\nExpected structural features: "
    f"{len(all_structural_features)}"
)

print(
    f"Available structural features: "
    f"{len(available_features)}"
)

print(
    f"Missing structural features: "
    f"{len(missing_features)}"
)


if len(missing_features) > 0:

    print(
        "\nMissing features:"
    )

    for feature in missing_features:

        print(
            f"  - {feature}"
        )

else:

    print(
        "\nAll expected structural features are present."
    )


# ============================================================
# 7. PARSE MUTATION POSITIONS
# ============================================================

def extract_position(
    mutation
):
    """
    Extract the numerical residue position from standard
    amino-acid substitution notation.

    Example:
    Y67A -> 67
    H114R -> 114
    """

    if pd.isna(
        mutation
    ):

        return np.nan


    mutation = str(
        mutation
    ).strip()


    import re


    match = re.match(
        r"^[A-Z](\d+)[A-Z]$",
        mutation
    )


    if match:

        return int(
            match.group(1)
        )


    return np.nan


df[
    "QC_Residue_Position"
] = (
    df[
        MUTATION_COLUMN
    ]
    .apply(
        extract_position
    )
)


# ============================================================
# 8. DEFINE EXPECTED STRUCTURAL COVERAGE
# ============================================================

# The 4NQ2 Chain A structure resolves residues 32–261.
#
# Therefore, mutation positions 1–31 and 262–266 are expected
# to lack experimentally resolved structural coordinates.

expected_unresolved_positions = (

    list(
        range(1, 32)
    )

    +

    list(
        range(262, 267)
    )
)


expected_resolved_positions = (

    list(
        range(32, 262)
    )
)


print("\n" + "=" * 70)
print("EXPECTED STRUCTURAL COVERAGE")
print("=" * 70)


print(
    f"\nExpected resolved positions: "
    f"{len(expected_resolved_positions)}"
)

print(
    f"Expected unresolved positions: "
    f"{len(expected_unresolved_positions)}"
)


print(
    "\nExpected unresolved positions:"
)

print(
    expected_unresolved_positions
)


# ============================================================
# 9. CREATE UNIQUE POSITION-LEVEL TABLE
# ============================================================

position_columns = [

    "QC_Residue_Position"
]


position_columns.extend(
    [
        feature
        for feature in available_features
    ]
)


position_df = (

    df[
        position_columns
    ]

    .drop_duplicates(
        subset=[
            "QC_Residue_Position"
        ]
    )

    .sort_values(
        "QC_Residue_Position"
    )

    .reset_index(
        drop=True
    )
)


print("\n" + "=" * 70)
print("POSITION-LEVEL SUMMARY")
print("=" * 70)


print(
    f"\nUnique mutation positions: "
    f"{len(position_df)}"
)

print(
    f"First mutation position: "
    f"{int(position_df['QC_Residue_Position'].min())}"
)

print(
    f"Last mutation position: "
    f"{int(position_df['QC_Residue_Position'].max())}"
)


# ============================================================
# 10. STRUCTURAL FEATURE COVERAGE TABLE
# ============================================================

print("\n" + "=" * 70)
print("STRUCTURAL FEATURE COVERAGE")
print("=" * 70)


coverage_records = []


for feature in available_features:

    positions_with_value = (

        position_df[
            feature
        ]
        .notna()
        .sum()
    )


    positions_without_value = (

        position_df[
            feature
        ]
        .isna()
        .sum()
    )


    coverage_percent = (

        positions_with_value
        /
        len(position_df)
        *
        100
    )


    coverage_records.append(
        {

            "Feature":
                feature,

            "Positions_With_Value":
                positions_with_value,

            "Positions_Without_Value":
                positions_without_value,

            "Coverage_Percent":
                round(
                    coverage_percent,
                    2
                )
        }
    )


coverage_df = pd.DataFrame(
    coverage_records
)


display(
    coverage_df
)


# ============================================================
# 11. CHECK CONSISTENCY OF MISSING POSITIONS
# ============================================================

print("\n" + "=" * 70)
print("MISSING-POSITION CONSISTENCY CHECK")
print("=" * 70)


missing_consistency_records = []


for feature in available_features:

    actual_missing_positions = (

        position_df.loc[
            position_df[
                feature
            ].isna(),
            "QC_Residue_Position"
        ]

        .dropna()

        .astype(int)

        .tolist()
    )


    actual_missing_positions = sorted(
        actual_missing_positions
    )


    consistency_pass = (

        actual_missing_positions
        ==
        expected_unresolved_positions
    )


    missing_consistency_records.append(
        {

            "Feature":
                feature,

            "Expected_Missing_Positions":
                len(
                    expected_unresolved_positions
                ),

            "Actual_Missing_Positions":
                len(
                    actual_missing_positions
                ),

            "Consistency_Check":
                "PASS"
                if consistency_pass
                else "CHECK"
        }
    )


missing_consistency_df = pd.DataFrame(
    missing_consistency_records
)


display(
    missing_consistency_df
)


# ============================================================
# 12. IDENTIFY ANY UNEXPECTED MISSING POSITIONS
# ============================================================

print("\n" + "=" * 70)
print("UNEXPECTED MISSING-POSITION CHECK")
print("=" * 70)


unexpected_missing_found = False


for feature in available_features:

    actual_missing = set(

        position_df.loc[
            position_df[
                feature
            ].isna(),
            "QC_Residue_Position"
        ]

        .dropna()

        .astype(int)

        .tolist()
    )


    unexpected_missing = sorted(

        actual_missing
        -
        set(
            expected_unresolved_positions
        )
    )


    if len(unexpected_missing) > 0:

        unexpected_missing_found = True


        print(
            f"\nFeature: {feature}"
        )


        print(
            "Unexpected missing positions:"
        )


        print(
            unexpected_missing
        )


if not unexpected_missing_found:

    print(
        "\nNo unexpected missing structural positions "
        "were detected."
    )


# ============================================================
# 13. CHECK RESOLVED POSITIONS FOR UNEXPECTED NaN VALUES
# ============================================================

print("\n" + "=" * 70)
print("RESOLVED-POSITION NaN CHECK")
print("=" * 70)


resolved_position_df = (

    position_df[
        position_df[
            "QC_Residue_Position"
        ].isin(
            expected_resolved_positions
        )
    ]
)


resolved_nan_records = []


for feature in available_features:

    nan_positions = (

        resolved_position_df.loc[
            resolved_position_df[
                feature
            ].isna(),
            "QC_Residue_Position"
        ]

        .dropna()

        .astype(int)

        .tolist()
    )


    resolved_nan_records.append(
        {

            "Feature":
                feature,

            "Unexpected_NaN_Count":
                len(
                    nan_positions
                ),

            "Unexpected_NaN_Positions":
                ", ".join(
                    map(
                        str,
                        nan_positions
                    )
                )
                if len(nan_positions) > 0
                else "None"
        }
    )


resolved_nan_df = pd.DataFrame(
    resolved_nan_records
)


display(
    resolved_nan_df
)


# ============================================================
# 14. NUMERICAL FEATURE RANGE AND DISTRIBUTION QC
# ============================================================

print("\n" + "=" * 70)
print("NUMERICAL STRUCTURAL FEATURE QC")
print("=" * 70)


numerical_qc_records = []


for feature in (
    numerical_structural_features
    +
    auxiliary_numerical_features
):

    if feature not in df.columns:

        continue


    values = (

        pd.to_numeric(
            df[feature],
            errors="coerce"
        )

        .dropna()
    )


    if len(values) == 0:

        numerical_qc_records.append(
            {

                "Feature":
                    feature,

                "Non_Missing_Count":
                    0,

                "Minimum":
                    np.nan,

                "Maximum":
                    np.nan,

                "Mean":
                    np.nan,

                "Median":
                    np.nan,

                "Standard_Deviation":
                    np.nan
            }
        )


    else:

        numerical_qc_records.append(
            {

                "Feature":
                    feature,

                "Non_Missing_Count":
                    len(values),

                "Minimum":
                    round(
                        values.min(),
                        4
                    ),

                "Maximum":
                    round(
                        values.max(),
                        4
                    ),

                "Mean":
                    round(
                        values.mean(),
                        4
                    ),

                "Median":
                    round(
                        values.median(),
                        4
                    ),

                "Standard_Deviation":
                    round(
                        values.std(),
                        4
                    )
            }
        )


numerical_qc_df = pd.DataFrame(
    numerical_qc_records
)


display(
    numerical_qc_df
)


# ============================================================
# 15. CHECK FOR NEGATIVE DISTANCES
# ============================================================

print("\n" + "=" * 70)
print("DISTANCE FEATURE SANITY CHECK")
print("=" * 70)


distance_features = [

    feature
    for feature in numerical_structural_features
    if feature.startswith(
        "Distance_to_"
    )
]


negative_distance_found = False


for feature in distance_features:

    if feature not in df.columns:

        continue


    negative_count = (

        pd.to_numeric(
            df[feature],
            errors="coerce"
        )
        .dropna()
        .lt(0)
        .sum()
    )


    print(
        f"\n{feature}:"
    )


    print(
        f"  Negative values: "
        f"{negative_count}"
    )


    if negative_count > 0:

        negative_distance_found = True


if not negative_distance_found:

    print(
        "\nDistance sanity check: PASSED"
    )


# ============================================================
# 16. SASA SANITY CHECK
# ============================================================

print("\n" + "=" * 70)
print("SASA SANITY CHECK")
print("=" * 70)


if "SASA" in df.columns:

    sasa_values = (

        pd.to_numeric(
            df["SASA"],
            errors="coerce"
        )

        .dropna()
    )


    negative_sasa_count = (

        sasa_values
        .lt(0)
        .sum()
    )


    print(
        f"\nNon-missing SASA values: "
        f"{len(sasa_values)}"
    )


    print(
        f"Minimum SASA: "
        f"{sasa_values.min():.4f} Å²"
    )


    print(
        f"Maximum SASA: "
        f"{sasa_values.max():.4f} Å²"
    )


    print(
        f"Negative SASA values: "
        f"{negative_sasa_count}"
    )


    if negative_sasa_count == 0:

        print(
            "\nSASA sanity check: PASSED"
        )


# ============================================================
# 17. CATEGORICAL FEATURE DISTRIBUTIONS
# ============================================================

print("\n" + "=" * 70)
print("CATEGORICAL STRUCTURAL FEATURE DISTRIBUTIONS")
print("=" * 70)


for feature in categorical_structural_features:

    if feature not in df.columns:

        continue


    print(
        "\n" + "-" * 60
    )


    print(
        feature
    )


    print(
        "-" * 60
    )


    distribution = (

        df[
            feature
        ]

        .value_counts(
            dropna=False
        )
    )


    display(
        distribution.to_frame(
            name="Count"
        )
    )


# ============================================================
# 18. SECONDARY STRUCTURE CODE CONSISTENCY CHECK
# ============================================================

print("\n" + "=" * 70)
print("SECONDARY-STRUCTURE CODE CONSISTENCY CHECK")
print("=" * 70)


if (
    "Secondary_Structure" in df.columns
    and
    "Secondary_Structure_Code" in df.columns
):

    expected_structure_codes = {

        "Helix": 1,

        "Sheet": 2,

        "Coil": 3
    }


    structure_code_mismatches = []


    unique_structure_rows = (

        df[
            [
                "Secondary_Structure",
                "Secondary_Structure_Code"
            ]
        ]

        .drop_duplicates()
    )


    for _, row in (
        unique_structure_rows.iterrows()
    ):

        structure = row[
            "Secondary_Structure"
        ]


        code = row[
            "Secondary_Structure_Code"
        ]


        if pd.isna(structure):

            continue


        expected_code = (
            expected_structure_codes.get(
                structure
            )
        )


        if expected_code is None:

            structure_code_mismatches.append(
                {

                    "Secondary_Structure":
                        structure,

                    "Observed_Code":
                        code,

                    "Expected_Code":
                        "Unknown category"
                }
            )


        elif (
            pd.isna(code)
            or
            int(code) != expected_code
        ):

            structure_code_mismatches.append(
                {

                    "Secondary_Structure":
                        structure,

                    "Observed_Code":
                        code,

                    "Expected_Code":
                        expected_code
                }
            )


    if len(structure_code_mismatches) == 0:

        print(
            "\nSecondary-structure encoding check: PASSED"
        )


    else:

        print(
            "\nWARNING — Secondary-structure code mismatches detected:"
        )


        display(
            pd.DataFrame(
                structure_code_mismatches
            )
        )


# ============================================================
# 19. FINAL POSITION-LEVEL STRUCTURAL SNAPSHOT
# ============================================================

print("\n" + "=" * 70)
print("FINAL STRUCTURAL FEATURE SNAPSHOT")
print("=" * 70)


snapshot_columns = [

    "QC_Residue_Position"
]


snapshot_columns.extend(
    [
        feature
        for feature in available_features
    ]
)


display(
    position_df[
        snapshot_columns
    ]
    .head(20)
)


print(
    "\n..."
)


display(
    position_df[
        snapshot_columns
    ]
    .tail(20)
)


# ============================================================
# 20. FINAL QC STATUS
# ============================================================

print("\n" + "=" * 70)
print("FINAL STRUCTURAL QC STATUS")
print("=" * 70)


# Check whether every available feature has the expected
# unresolved-position pattern.

all_coverage_checks_passed = (

    missing_consistency_df[
        "Consistency_Check"
    ]
    .eq(
        "PASS"
    )
    .all()
)


# Check whether resolved positions contain unexpected NaN values.

all_resolved_nan_checks_passed = (

    resolved_nan_df[
        "Unexpected_NaN_Count"
    ]
    .eq(0)
    .all()
)


# Check numerical distance validity.

distance_check_passed = (
    not negative_distance_found
)


if (
    all_coverage_checks_passed
    and
    all_resolved_nan_checks_passed
    and
    distance_check_passed
):

    final_qc_status = "PASS"


else:

    final_qc_status = "CHECK"


print(
    f"\nFINAL STRUCTURAL QC STATUS: "
    f"{final_qc_status}"
)


if final_qc_status == "PASS":

    print(
        "\nAll major structural feature quality-control "
        "checks passed successfully."
    )


else:

    print(
        "\nOne or more quality-control checks require review."
    )


# ============================================================
# 21. REMOVE TEMPORARY QC COLUMN
# ============================================================

df.drop(
    columns=[
        "QC_Residue_Position"
    ],
    inplace=True
)


# ============================================================
# 22. SAVE QC-VALIDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 23. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 11H COMPLETE")
print("=" * 70)


print(
    "\nQC-validated output file saved successfully:"
)

print(
    OUTPUT_FILE
)


print(
    f"\nFinal dataset rows: "
    f"{len(df)}"
)


print(
    f"Final dataset columns: "
    f"{len(df.columns)}"
)


print(
    "\nStructural reference:"
)

print(
    "  PDB: 4NQ2"
)

print(
    "  Chain: A"
)


print(
    "\nStructural features reviewed:"
)


for feature in available_features:

    print(
        f"  - {feature}"
    )


print(
    "\nExpected unresolved positions:"
)

print(
    "  1–31 and 262–266"
)


print(
    f"\nFINAL STRUCTURAL QC STATUS: "
    f"{final_qc_status}"
)


print(
    "\nPart 11 structural feature engineering "
    "and quality control are complete."
)

======================================================================
PART 11H — FINAL STRUCTURAL FEATURE QUALITY CONTROL
======================================================================

Input file found successfully:
VIM2_Part11G_Secondary_Structure.csv

======================================================================
DATASET SUMMARY
======================================================================

Total mutation rows: 5016
Total dataset columns: 51

======================================================================
STRUCTURAL FEATURE AVAILABILITY CHECK
======================================================================

Expected structural features: 12
Available structural features: 12
Missing structural features: 0

All expected structural features are present.

======================================================================
EXPECTED STRUCTURAL COVERAGE
======================================================================

Expected resolved positions: 230
Expected unresolved positions: 36

Expected unresolved positions:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 262, 263, 264, 265, 266]

======================================================================
POSITION-LEVEL SUMMARY
======================================================================

Unique mutation positions: 266
First mutation position: 1
Last mutation position: 266

======================================================================
STRUCTURAL FEATURE COVERAGE
======================================================================

,Feature,Positions_With_Value,Positions_Without_Value,Coverage_Percent
0,Distance_to_Metal_Site,230,36,86.47
1,Distance_to_Active_Site_Pocket,230,36,86.47
2,Distance_to_L3_Loop,230,36,86.47
3,Distance_to_L10_Loop,230,36,86.47
4,SASA,230,36,86.47
5,Nearest_Metal_Site_Residue,230,36,86.47
6,Nearest_Active_Site_Pocket_Residue,230,36,86.47
7,Nearest_L3_Residue,230,36,86.47
8,Nearest_L10_Residue,230,36,86.47
9,Secondary_Structure,230,36,86.47
10,DSSP_Secondary_Structure,230,36,86.47
11,Secondary_Structure_Code,230,36,86.47

======================================================================
MISSING-POSITION CONSISTENCY CHECK
======================================================================

,Feature,Expected_Missing_Positions,Actual_Missing_Positions,Consistency_Check
0,Distance_to_Metal_Site,36,36,PASS
1,Distance_to_Active_Site_Pocket,36,36,PASS
2,Distance_to_L3_Loop,36,36,PASS
3,Distance_to_L10_Loop,36,36,PASS
4,SASA,36,36,PASS
5,Nearest_Metal_Site_Residue,36,36,PASS
6,Nearest_Active_Site_Pocket_Residue,36,36,PASS
7,Nearest_L3_Residue,36,36,PASS
8,Nearest_L10_Residue,36,36,PASS
9,Secondary_Structure,36,36,PASS
10,DSSP_Secondary_Structure,36,36,PASS
11,Secondary_Structure_Code,36,36,PASS

======================================================================
UNEXPECTED MISSING-POSITION CHECK
======================================================================

No unexpected missing structural positions were detected.

======================================================================
RESOLVED-POSITION NaN CHECK
======================================================================

,Feature,Unexpected_NaN_Count,Unexpected_NaN_Positions
0,Distance_to_Metal_Site,0,None
1,Distance_to_Active_Site_Pocket,0,None
2,Distance_to_L3_Loop,0,None
3,Distance_to_L10_Loop,0,None
4,SASA,0,None
5,Nearest_Metal_Site_Residue,0,None
6,Nearest_Active_Site_Pocket_Residue,0,None
7,Nearest_L3_Residue,0,None
8,Nearest_L10_Residue,0,None
9,Secondary_Structure,0,None
10,DSSP_Secondary_Structure,0,None
11,Secondary_Structure_Code,0,None

======================================================================
NUMERICAL STRUCTURAL FEATURE QC
======================================================================

,Feature,Non_Missing_Count,Minimum,Maximum,Mean,Median,Standard_Deviation
0,Distance_to_Metal_Site,4335,0.0,26.6867,12.2384,12.0899,5.2938
1,Distance_to_Active_Site_Pocket,4335,0.0,25.6238,11.3592,11.0964,5.3791
2,Distance_to_L3_Loop,4335,0.0,30.9178,18.1538,19.2673,7.2089
3,Distance_to_L10_Loop,4335,0.0,31.6136,15.5404,15.5809,7.5698
4,SASA,4335,0.0,152.4173,19.6664,3.4599,28.5502
5,Secondary_Structure_Code,4335,1.0,3.0000,2.1742,2.0000,0.8261

======================================================================
DISTANCE FEATURE SANITY CHECK
======================================================================

Distance_to_Metal_Site:
  Negative values: 0

Distance_to_Active_Site_Pocket:
  Negative values: 0

Distance_to_L3_Loop:
  Negative values: 0

Distance_to_L10_Loop:
  Negative values: 0

Distance sanity check: PASSED

======================================================================
SASA SANITY CHECK
======================================================================

Non-missing SASA values: 4335
Minimum SASA: 0.0000 Å²
Maximum SASA: 152.4173 Å²
Negative SASA values: 0

SASA sanity check: PASSED

======================================================================
CATEGORICAL STRUCTURAL FEATURE DISTRIBUTIONS
======================================================================

------------------------------------------------------------
Nearest_Metal_Site_Residue
------------------------------------------------------------

                            Count
Nearest_Metal_Site_Residue
240.0                         996
114.0                         966
118.0                         943
179.0                         695
NaN                           681
198.0                         565
116.0                         170

------------------------------------------------------------
Nearest_Active_Site_Pocket_Residue
------------------------------------------------------------

                                    Count
Nearest_Active_Site_Pocket_Residue
114.0                                 890
87.0                                  867
240.0                                 730
179.0                                 695
NaN                                   681
198.0                                 565
67.0                                  228
116.0                                 170
62.0                                   95
118.0                                  95

------------------------------------------------------------
Nearest_L3_Residue
------------------------------------------------------------

                    Count
Nearest_L3_Residue
68.0                 2691
60.0                  962
NaN                   681
67.0                  359
62.0                  228
61.0                   19
63.0                   19
64.0                   19
65.0                   19
66.0                   19

------------------------------------------------------------
Nearest_L10_Residue
------------------------------------------------------------

                     Count
Nearest_L10_Residue
202.0                 1236
201.0                  866
213.0                  776
NaN                    681
214.0                  566
210.0                  361
209.0                  114
208.0                  112
204.0                   95
207.0                   57
203.0                   57
206.0                   38
205.0                   19
211.0                   19
212.0                   19

------------------------------------------------------------
Secondary_Structure
------------------------------------------------------------

                     Count
Secondary_Structure
Coil                  1922
Sheet                 1246
Helix                 1167
NaN                    681

------------------------------------------------------------
DSSP_Secondary_Structure
------------------------------------------------------------

                          Count
DSSP_Secondary_Structure
E                          1227
H                          1110
-                           843
NaN                         681
T                           646
S                           433
G                            57
B                            19

======================================================================
SECONDARY-STRUCTURE CODE CONSISTENCY CHECK
======================================================================

Secondary-structure encoding check: PASSED

======================================================================
FINAL STRUCTURAL FEATURE SNAPSHOT
======================================================================

,QC_Residue_Position,Distance_to_Metal_Site,Distance_to_Active_Site_Pocket,Distance_to_L3_Loop,Distance_to_L10_Loop,SASA,Nearest_Metal_Site_Residue,Nearest_Active_Site_Pocket_Residue,Nearest_L3_Residue,Nearest_L10_Residue,Secondary_Structure,DSSP_Secondary_Structure,Secondary_Structure_Code
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

...

,QC_Residue_Position,Distance_to_Metal_Site,Distance_to_Active_Site_Pocket,Distance_to_L3_Loop,Distance_to_L10_Loop,SASA,Nearest_Metal_Site_Residue,Nearest_Active_Site_Pocket_Residue,Nearest_L3_Residue,Nearest_L10_Residue,Secondary_Structure,DSSP_Secondary_Structure,Secondary_Structure_Code
246,247,15.422454,15.422454,20.829872,8.656687,29.494594,198.0,198.0,68.0,203.0,Helix,H,1.0
247,248,11.799117,11.799117,17.402710,6.374205,0.000000,198.0,198.0,68.0,202.0,Helix,H,1.0
248,249,11.570529,11.570529,19.620189,7.696760,0.000000,198.0,198.0,68.0,201.0,Helix,H,1.0
249,250,14.472911,14.472911,21.924381,9.607386,75.087762,198.0,198.0,68.0,201.0,Helix,H,1.0
250,251,13.242353,13.242353,19.148045,6.553904,27.310192,198.0,198.0,68.0,203.0,Helix,H,1.0
251,252,10.202052,10.202052,17.816151,5.280634,0.000000,198.0,198.0,68.0,201.0,Helix,H,1.0
252,253,11.468932,11.468932,21.476532,9.001619,0.377384,179.0,179.0,68.0,201.0,Helix,H,1.0
253,254,14.105039,14.105039,21.897753,8.691111,55.352437,179.0,179.0,67.0,206.0,Helix,H,1.0
254,255,12.210734,12.210734,18.792467,5.871376,7.673471,179.0,179.0,67.0,207.0,Helix,H,1.0
255,256,9.736252,9.736252,19.829538,6.341630,2.767481,179.0,179.0,67.0,208.0,Helix,H,1.0
256,257,13.027987,13.027987,23.356335,9.399703,58.318869,179.0,179.0,67.0,208.0,Helix,H,1.0
257,258,14.876636,14.876636,22.397530,7.953676,26.354538,179.0,179.0,67.0,207.0,Helix,H,1.0
258,259,12.702179,12.702179,20.557480,6.178331,26.159780,179.0,179.0,67.0,208.0,Helix,H,1.0
259,260,13.007728,13.007728,23.605290,9.264553,46.553733,179.0,179.0,67.0,208.0,Helix,H,1.0
260,261,16.683319,16.683319,25.839874,11.494635,121.778699,179.0,179.0,67.0,208.0,Coil,-,3.0
261,262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,264,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
264,265,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
265,266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
FINAL STRUCTURAL QC STATUS
======================================================================

FINAL STRUCTURAL QC STATUS: PASS

All major structural feature quality-control checks passed successfully.

======================================================================
PART 11H COMPLETE
======================================================================

QC-validated output file saved successfully:
VIM2_Part11H_Final_Structural_QC.csv

Final dataset rows: 5016
Final dataset columns: 51

Structural reference:
  PDB: 4NQ2
  Chain: A

Structural features reviewed:
  - Distance_to_Metal_Site
  - Distance_to_Active_Site_Pocket
  - Distance_to_L3_Loop
  - Distance_to_L10_Loop
  - SASA
  - Nearest_Metal_Site_Residue
  - Nearest_Active_Site_Pocket_Residue
  - Nearest_L3_Residue
  - Nearest_L10_Residue
  - Secondary_Structure
  - DSSP_Secondary_Structure
  - Secondary_Structure_Code

Expected unresolved positions:
  1–31 and 262–266

FINAL STRUCTURAL QC STATUS: PASS

Part 11 structural feature engineering and quality control are complete.

In [ ]:
# @title
# ============================================================
# PART 12B
# LOCAL SEQUENCE CONTEXT FEATURE ENGINEERING
#
# This script calculates residue-level local sequence context
# features for every mutation position in the VIM-2 dataset.
#
# The analysis uses the wild-type VIM-2 amino-acid sequence
# and a symmetric local sequence window around each mutated
# residue position.
#
# No artificial residues or padding are introduced at the
# N-terminal or C-terminal sequence boundaries.
#
# Output features are available for all valid mutation
# positions represented in the dataset.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os
import re

import numpy as np
import pandas as pd


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part11H_Final_Structural_QC.csv"
)

OUTPUT_FILE = (
    "VIM2_Part12B_Local_Sequence_Context.csv"
)

MUTATION_COLUMN = "Mutation"

# A window radius of 5 creates an 11-residue window:
# 5 residues upstream + central residue + 5 residues downstream.
WINDOW_RADIUS = 5


# ============================================================
# 3. VALIDATE AND LOAD THE INPUT DATASET
# ============================================================

print("=" * 70)
print("PART 12B — LOCAL SEQUENCE CONTEXT FEATURE ENGINEERING")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        f"\nInput file was not found:\n"
        f"{INPUT_FILE}"
    )


df = pd.read_csv(
    INPUT_FILE
)


print(
    f"\nInput file loaded successfully:\n"
    f"{INPUT_FILE}"
)

print(
    f"\nDataset rows: "
    f"{len(df)}"
)

print(
    f"Dataset columns: "
    f"{len(df.columns)}"
)


if MUTATION_COLUMN not in df.columns:

    raise ValueError(
        f"\nRequired mutation column "
        f"'{MUTATION_COLUMN}' was not found."
    )


# ============================================================
# 4. EXTRACT THE WILD-TYPE SEQUENCE FROM THE MUTATION DATASET
# ============================================================

# The mutation dataset contains substitutions in the format:
# X123Y
#
# where:
# X = wild-type amino acid
# 123 = residue position
# Y = mutant amino acid
#
# The wild-type identity at each position is reconstructed
# directly from the validated mutation column.

def parse_mutation(
    mutation
):
    """
    Parse a standard amino-acid substitution.

    Example:
    H114R -> WT='H', Position=114, Mutant='R'
    """

    if pd.isna(mutation):

        return None


    mutation = str(
        mutation
    ).strip()


    match = re.match(
        r"^([A-Z])(\d+)([A-Z])$",
        mutation
    )


    if match is None:

        return None


    return {

        "WT":
            match.group(1),

        "Position":
            int(
                match.group(2)
            ),

        "Mutant":
            match.group(3)
    }


parsed_mutations = (
    df[MUTATION_COLUMN]
    .apply(
        parse_mutation
    )
)


# ============================================================
# 5. RECONSTRUCT THE VALIDATED WILD-TYPE SEQUENCE
# ============================================================

position_to_wt = {}


for parsed in parsed_mutations:

    if parsed is None:

        continue


    position = parsed[
        "Position"
    ]

    wt_residue = parsed[
        "WT"
    ]


    if position not in position_to_wt:

        position_to_wt[
            position
        ] = wt_residue


    else:

        existing_residue = (
            position_to_wt[
                position
            ]
        )


        if existing_residue != wt_residue:

            raise ValueError(
                "\nWild-type residue inconsistency detected "
                f"at position {position}.\n"
                f"Observed residues: "
                f"{existing_residue} and {wt_residue}"
            )


sorted_positions = sorted(
    position_to_wt.keys()
)


first_position = min(
    sorted_positions
)

last_position = max(
    sorted_positions
)


expected_positions = list(
    range(
        first_position,
        last_position + 1
    )
)


missing_positions = sorted(

    set(
        expected_positions
    )

    -

    set(
        sorted_positions
    )
)


if len(missing_positions) > 0:

    raise ValueError(
        "\nThe mutation dataset does not provide a continuous "
        "wild-type sequence.\n\n"
        f"Missing positions:\n"
        f"{missing_positions}"
    )


wild_type_sequence = "".join(

    position_to_wt[position]

    for position in expected_positions
)


print("\n" + "=" * 70)
print("WILD-TYPE SEQUENCE RECONSTRUCTION")
print("=" * 70)


print(
    f"\nFirst sequence position: "
    f"{first_position}"
)

print(
    f"Last sequence position: "
    f"{last_position}"
)

print(
    f"Sequence length: "
    f"{len(wild_type_sequence)}"
)

print(
    "\nWild-type sequence reconstructed successfully "
    "from internally consistent mutation data."
)


# ============================================================
# 6. DEFINE AMINO-ACID PROPERTY GROUPS
# ============================================================

# Hydrophobic residues.
HYDROPHOBIC_RESIDUES = set(
    "AVILMFWY"
)


# Charged residues.
CHARGED_RESIDUES = set(
    "DEKRH"
)


# Positively charged or basic residues.
POSITIVE_RESIDUES = set(
    "KRH"
)


# Negatively charged or acidic residues.
NEGATIVE_RESIDUES = set(
    "DE"
)


# Polar, uncharged residues.
POLAR_RESIDUES = set(
    "STNQCY"
)


# Aromatic residues.
AROMATIC_RESIDUES = set(
    "FWYH"
)


# Glycine and proline are grouped because both can strongly
# influence local backbone geometry and conformational behavior.
GLY_PRO_RESIDUES = set(
    "GP"
)


# ============================================================
# 7. DEFINE THE LOCAL WINDOW EXTRACTION FUNCTION
# ============================================================

def get_local_window(
    sequence,
    position,
    radius
):
    """
    Extract the available local sequence window centered on
    the specified 1-based residue position.

    No artificial padding is introduced at sequence boundaries.

    Example with radius = 5:
    Up to 5 residues upstream
    + central residue
    + up to 5 residues downstream
    """

    sequence_length = len(
        sequence
    )


    zero_based_index = (
        position - 1
    )


    start_index = max(
        0,
        zero_based_index - radius
    )


    end_index = min(
        sequence_length,
        zero_based_index + radius + 1
    )


    return sequence[
        start_index:end_index
    ]


# ============================================================
# 8. DEFINE SHANNON ENTROPY CALCULATION
# ============================================================

def calculate_shannon_entropy(
    sequence_window
):
    """
    Calculate Shannon entropy for amino-acid composition
    within a local sequence window.

    Higher entropy indicates a more compositionally diverse
    local environment.

    Lower entropy indicates a more compositionally repetitive
    local environment.
    """

    if len(sequence_window) == 0:

        return np.nan


    residue_counts = pd.Series(
        list(sequence_window)
    ).value_counts()


    probabilities = (

        residue_counts
        /
        residue_counts.sum()
    )


    entropy = -np.sum(

        probabilities
        *
        np.log2(
            probabilities
        )
    )


    return entropy


# ============================================================
# 9. CALCULATE POSITION-LEVEL LOCAL SEQUENCE FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING LOCAL SEQUENCE CONTEXT FEATURES")
print("=" * 70)


position_feature_records = []


for position in expected_positions:

    local_window = get_local_window(
        sequence=wild_type_sequence,
        position=position,
        radius=WINDOW_RADIUS
    )


    window_length = len(
        local_window
    )


    # Count residues belonging to each physicochemical group.
    hydrophobic_count = sum(

        residue in HYDROPHOBIC_RESIDUES

        for residue in local_window
    )


    charged_count = sum(

        residue in CHARGED_RESIDUES

        for residue in local_window
    )


    positive_count = sum(

        residue in POSITIVE_RESIDUES

        for residue in local_window
    )


    negative_count = sum(

        residue in NEGATIVE_RESIDUES

        for residue in local_window
    )


    polar_count = sum(

        residue in POLAR_RESIDUES

        for residue in local_window
    )


    aromatic_count = sum(

        residue in AROMATIC_RESIDUES

        for residue in local_window
    )


    gly_pro_count = sum(

        residue in GLY_PRO_RESIDUES

        for residue in local_window
    )


    position_feature_records.append(

        {

            "Sequence_Position":
                position,

            "Local_Window":
                local_window,

            "Local_Window_Length":
                window_length,

            "Local_Hydrophobic_Fraction":
                hydrophobic_count
                /
                window_length,

            "Local_Charged_Fraction":
                charged_count
                /
                window_length,

            "Local_Positive_Charge_Fraction":
                positive_count
                /
                window_length,

            "Local_Negative_Charge_Fraction":
                negative_count
                /
                window_length,

            "Local_Polar_Fraction":
                polar_count
                /
                window_length,

            "Local_Aromatic_Fraction":
                aromatic_count
                /
                window_length,

            "Local_Gly_Pro_Fraction":
                gly_pro_count
                /
                window_length,

            "Local_Sequence_Entropy":
                calculate_shannon_entropy(
                    local_window
                )
        }
    )


position_features_df = pd.DataFrame(
    position_feature_records
)


# ============================================================
# 10. VALIDATE COMPLETE POSITION COVERAGE
# ============================================================

print("\n" + "=" * 70)
print("POSITION COVERAGE VALIDATION")
print("=" * 70)


calculated_positions = set(

    position_features_df[
        "Sequence_Position"
    ]
)


expected_position_set = set(
    expected_positions
)


missing_feature_positions = sorted(

    expected_position_set
    -
    calculated_positions
)


if len(missing_feature_positions) > 0:

    raise ValueError(
        "\nLocal sequence features are missing for the "
        "following positions:\n"
        f"{missing_feature_positions}"
    )


print(
    "\nLocal sequence features were successfully calculated "
    "for all sequence positions."
)


print(
    f"\nCovered positions: "
    f"{len(calculated_positions)} / "
    f"{len(expected_position_set)}"
)


# ============================================================
# 11. DISPLAY EXAMPLE POSITION-LEVEL FEATURES
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE LOCAL SEQUENCE FEATURES")
print("=" * 70)


display(

    position_features_df.head(
        10
    )
)


# ============================================================
# 12. MERGE POSITION-LEVEL FEATURES INTO THE MUTATION DATASET
# ============================================================

# Extract the mutation position for every dataset row.

df[
    "Sequence_Position"
] = (

    df[MUTATION_COLUMN]

    .apply(
        lambda x: (
            parse_mutation(x)["Position"]
            if parse_mutation(x) is not None
            else np.nan
        )
    )
)


if df[
    "Sequence_Position"
].isna().any():

    raise ValueError(
        "\nOne or more mutation positions could not be parsed."
    )


# Merge the calculated position-level features.
df = df.merge(

    position_features_df,

    on="Sequence_Position",

    how="left",

    validate="many_to_one"
)


# ============================================================
# 13. FINAL MERGE VALIDATION
# ============================================================

new_feature_columns = [

    "Local_Window",

    "Local_Window_Length",

    "Local_Hydrophobic_Fraction",

    "Local_Charged_Fraction",

    "Local_Positive_Charge_Fraction",

    "Local_Negative_Charge_Fraction",

    "Local_Polar_Fraction",

    "Local_Aromatic_Fraction",

    "Local_Gly_Pro_Fraction",

    "Local_Sequence_Entropy"
]


print("\n" + "=" * 70)
print("FINAL FEATURE COVERAGE CHECK")
print("=" * 70)


for feature in new_feature_columns:

    missing_count = (

        df[
            feature
        ]
        .isna()
        .sum()
    )


    print(
        f"\n{feature}"
    )

    print(
        f"  Missing values: "
        f"{missing_count}"
    )


    if missing_count > 0:

        raise ValueError(
            f"\nUnexpected missing values detected in "
            f"'{feature}'."
        )


print(
    "\nAll local sequence features have complete coverage."
)


# ============================================================
# 14. REMOVE TEMPORARY POSITION COLUMN
# ============================================================

# Sequence_Position is retained because it is a biologically
# meaningful positional feature and can also be useful for
# downstream analyses.

# Therefore, it is intentionally NOT removed.


# ============================================================
# 15. SAVE THE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 16. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 12B COMPLETE")
print("=" * 70)


print(
    "\nOutput file saved successfully:"
)

print(
    OUTPUT_FILE
)


print(
    f"\nFinal dataset rows: "
    f"{len(df)}"
)

print(
    f"Final dataset columns: "
    f"{len(df.columns)}"
)


print(
    "\nNew local sequence context features:"
)


for feature in new_feature_columns:

    print(
        f"  - {feature}"
    )


print(
    "\nAdditional positional feature:"
)

print(
    "  - Sequence_Position"
)


print(
    f"\nLocal sequence window radius: "
    f"±{WINDOW_RADIUS} residues"
)


print(
    f"Maximum window length: "
    f"{2 * WINDOW_RADIUS + 1} residues"
)


print(
    "\nNo artificial sequence padding was introduced "
    "at sequence boundaries."
)


print(
    "\nFeature coverage:"
)

print(
    f"  {len(expected_position_set)} / "
    f"{len(expected_position_set)} "
    "mutation positions"
)


print(
    "\nNext recommended step:"
)

print(
    "  Review the newly generated local sequence features "
    "before proceeding to additional physicochemical or "
    "evolutionary feature engineering."
)

======================================================================
PART 12B — LOCAL SEQUENCE CONTEXT FEATURE ENGINEERING
======================================================================

Input file loaded successfully:
VIM2_Part11H_Final_Structural_QC.csv

Dataset rows: 5016
Dataset columns: 51

======================================================================
WILD-TYPE SEQUENCE RECONSTRUCTION
======================================================================

First sequence position: 1
Last sequence position: 266
Sequence length: 266

Wild-type sequence reconstructed successfully from internally consistent mutation data.

======================================================================
CALCULATING LOCAL SEQUENCE CONTEXT FEATURES
======================================================================

======================================================================
POSITION COVERAGE VALIDATION
======================================================================

Local sequence features were successfully calculated for all sequence positions.

Covered positions: 266 / 266

======================================================================
EXAMPLE LOCAL SEQUENCE FEATURES
======================================================================

,Sequence_Position,Local_Window,Local_Window_Length,Local_Hydrophobic_Fraction,Local_Charged_Fraction,Local_Positive_Charge_Fraction,Local_Negative_Charge_Fraction,Local_Polar_Fraction,Local_Aromatic_Fraction,Local_Gly_Pro_Fraction,Local_Sequence_Entropy
0,1,MFKLLS,6,0.666667,0.166667,0.166667,0.0,0.166667,0.166667,0.0,2.251629
1,2,MFKLLSK,7,0.571429,0.285714,0.285714,0.0,0.142857,0.142857,0.0,2.235926
2,3,MFKLLSKL,8,0.625000,0.250000,0.250000,0.0,0.125000,0.125000,0.0,2.155639
3,4,MFKLLSKLL,9,0.666667,0.222222,0.222222,0.0,0.111111,0.111111,0.0,2.058814
4,5,MFKLLSKLLV,10,0.700000,0.200000,0.200000,0.0,0.100000,0.100000,0.0,2.321928
5,6,MFKLLSKLLVY,11,0.727273,0.181818,0.181818,0.0,0.181818,0.181818,0.0,2.550341
6,7,FKLLSKLLVYL,11,0.727273,0.181818,0.181818,0.0,0.181818,0.181818,0.0,2.222192
7,8,KLLSKLLVYLT,11,0.636364,0.181818,0.181818,0.0,0.272727,0.090909,0.0,2.222192
8,9,LLSKLLVYLTA,11,0.727273,0.090909,0.090909,0.0,0.272727,0.090909,0.0,2.404010
9,10,LSKLLVYLTAS,11,0.636364,0.090909,0.090909,0.0,0.363636,0.090909,0.0,2.550341

======================================================================
FINAL FEATURE COVERAGE CHECK
======================================================================

Local_Window
  Missing values: 0

Local_Window_Length
  Missing values: 0

Local_Hydrophobic_Fraction
  Missing values: 0

Local_Charged_Fraction
  Missing values: 0

Local_Positive_Charge_Fraction
  Missing values: 0

Local_Negative_Charge_Fraction
  Missing values: 0

Local_Polar_Fraction
  Missing values: 0

Local_Aromatic_Fraction
  Missing values: 0

Local_Gly_Pro_Fraction
  Missing values: 0

Local_Sequence_Entropy
  Missing values: 0

All local sequence features have complete coverage.

======================================================================
PART 12B COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part12B_Local_Sequence_Context.csv

Final dataset rows: 5016
Final dataset columns: 62

New local sequence context features:
  - Local_Window
  - Local_Window_Length
  - Local_Hydrophobic_Fraction
  - Local_Charged_Fraction
  - Local_Positive_Charge_Fraction
  - Local_Negative_Charge_Fraction
  - Local_Polar_Fraction
  - Local_Aromatic_Fraction
  - Local_Gly_Pro_Fraction
  - Local_Sequence_Entropy

Additional positional feature:
  - Sequence_Position

Local sequence window radius: ±5 residues
Maximum window length: 11 residues

No artificial sequence padding was introduced at sequence boundaries.

Feature coverage:
  266 / 266 mutation positions

Next recommended step:
  Review the newly generated local sequence features before proceeding to additional physicochemical or evolutionary feature engineering.

In [ ]:
# @title
# ============================================================
# PART 12C
# SIDE-CHAIN VOLUME FEATURE ENGINEERING
#
# This script adds amino-acid side-chain volume features to the
# VIM-2 mutation dataset.
#
# Molecular weight and side-chain volume describe different
# physicochemical properties. Molecular weight reflects atomic
# mass, whereas side-chain volume reflects the approximate
# steric space occupied by an amino-acid side chain.
#
# The resulting features quantify the potential steric effect
# of each amino-acid substitution.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os

import numpy as np
import pandas as pd


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part12B_Local_Sequence_Context.csv"
)

OUTPUT_FILE = (
    "VIM2_Part12C_Side_Chain_Volume.csv"
)

WT_COLUMN = "WT_AA"

MUTANT_COLUMN = "Mutant_AA"


# ============================================================
# 3. LOAD AND VALIDATE THE INPUT DATASET
# ============================================================

print("=" * 70)
print("PART 12C — SIDE-CHAIN VOLUME FEATURE ENGINEERING")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        "\nInput file was not found:\n"
        f"{INPUT_FILE}"
    )


df = pd.read_csv(
    INPUT_FILE
)


print(
    "\nInput file loaded successfully:"
)

print(
    INPUT_FILE
)


print(
    f"\nDataset rows: "
    f"{len(df)}"
)

print(
    f"Dataset columns: "
    f"{len(df.columns)}"
)


# ============================================================
# 4. VALIDATE REQUIRED AMINO-ACID COLUMNS
# ============================================================

required_columns = [

    WT_COLUMN,

    MUTANT_COLUMN
]


missing_columns = [

    column

    for column in required_columns

    if column not in df.columns
]


if len(missing_columns) > 0:

    raise ValueError(
        "\nThe following required columns are missing:\n"
        f"{missing_columns}"
    )


# ============================================================
# 5. DEFINE STANDARD AMINO-ACID SIDE-CHAIN VOLUMES
# ============================================================

# Approximate side-chain volumes are expressed in Å³.
#
# These values are used to quantify relative steric differences
# between the wild-type and mutant amino acids.
#
# The analysis treats side-chain volume as an approximate
# physicochemical descriptor rather than an exact atomic volume
# within a specific protein conformation.

SIDE_CHAIN_VOLUME = {

    "A": 88.6,
    "R": 173.4,
    "N": 114.1,
    "D": 111.1,
    "C": 108.5,

    "Q": 143.8,
    "E": 138.4,
    "G": 60.1,
    "H": 153.2,
    "I": 166.7,

    "L": 166.7,
    "K": 168.6,
    "M": 162.9,
    "F": 189.9,
    "P": 112.7,

    "S": 89.0,
    "T": 116.1,
    "W": 227.8,
    "Y": 193.6,
    "V": 140.0
}


# ============================================================
# 6. VALIDATE AMINO-ACID IDENTITIES
# ============================================================

valid_amino_acids = set(
    SIDE_CHAIN_VOLUME.keys()
)


wt_amino_acids = set(

    df[
        WT_COLUMN
    ]
    .dropna()
    .astype(str)
    .str.upper()
    .unique()
)


mutant_amino_acids = set(

    df[
        MUTANT_COLUMN
    ]
    .dropna()
    .astype(str)
    .str.upper()
    .unique()
)


unknown_wt_amino_acids = (

    wt_amino_acids
    -
    valid_amino_acids
)


unknown_mutant_amino_acids = (

    mutant_amino_acids
    -
    valid_amino_acids
)


if len(unknown_wt_amino_acids) > 0:

    raise ValueError(
        "\nUnknown wild-type amino-acid codes detected:\n"
        f"{sorted(unknown_wt_amino_acids)}"
    )


if len(unknown_mutant_amino_acids) > 0:

    raise ValueError(
        "\nUnknown mutant amino-acid codes detected:\n"
        f"{sorted(unknown_mutant_amino_acids)}"
    )


print("\n" + "=" * 70)
print("AMINO-ACID VALIDATION")
print("=" * 70)


print(
    "\nAll wild-type amino-acid identities "
    "were successfully validated."
)


print(
    "\nAll mutant amino-acid identities "
    "were successfully validated."
)


# ============================================================
# 7. CALCULATE SIDE-CHAIN VOLUME FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING SIDE-CHAIN VOLUME FEATURES")
print("=" * 70)


# Standardize amino-acid codes before dictionary mapping.
df[
    WT_COLUMN
] = (

    df[
        WT_COLUMN
    ]
    .astype(str)
    .str.upper()
)


df[
    MUTANT_COLUMN
] = (

    df[
        MUTANT_COLUMN
    ]
    .astype(str)
    .str.upper()
)


# Map each amino acid to its approximate side-chain volume.
df[
    "WT_Side_Chain_Volume"
] = (

    df[
        WT_COLUMN
    ]
    .map(
        SIDE_CHAIN_VOLUME
    )
)


df[
    "Mutant_Side_Chain_Volume"
] = (

    df[
        MUTANT_COLUMN
    ]
    .map(
        SIDE_CHAIN_VOLUME
    )
)


# Calculate the signed steric change introduced by mutation.
#
# Positive value:
# The mutant side chain is larger.
#
# Negative value:
# The mutant side chain is smaller.
df[
    "Side_Chain_Volume_Change"
] = (

    df[
        "Mutant_Side_Chain_Volume"
    ]

    -

    df[
        "WT_Side_Chain_Volume"
    ]
)


# ============================================================
# 8. CALCULATE ABSOLUTE VOLUME CHANGE
# ============================================================

# The absolute change quantifies the magnitude of steric
# disruption independently of whether the mutation increases
# or decreases side-chain volume.
df[
    "Absolute_Side_Chain_Volume_Change"
] = (

    df[
        "Side_Chain_Volume_Change"
    ]
    .abs()
)


# ============================================================
# 9. CALCULATE RELATIVE VOLUME CHANGE
# ============================================================

# Relative volume change normalizes the signed volume change
# by the wild-type side-chain volume.
#
# This allows mutations occurring at residues of different
# baseline sizes to be compared on a relative scale.
df[
    "Relative_Side_Chain_Volume_Change"
] = (

    df[
        "Side_Chain_Volume_Change"
    ]

    /

    df[
        "WT_Side_Chain_Volume"
    ]
)


# ============================================================
# 10. FINAL FEATURE VALIDATION
# ============================================================

new_feature_columns = [

    "WT_Side_Chain_Volume",

    "Mutant_Side_Chain_Volume",

    "Side_Chain_Volume_Change",

    "Absolute_Side_Chain_Volume_Change",

    "Relative_Side_Chain_Volume_Change"
]


print("\n" + "=" * 70)
print("FEATURE COVERAGE VALIDATION")
print("=" * 70)


for feature in new_feature_columns:

    missing_count = (

        df[
            feature
        ]
        .isna()
        .sum()
    )


    print(
        f"\n{feature}"
    )

    print(
        f"  Missing values: "
        f"{missing_count}"
    )


    if missing_count > 0:

        raise ValueError(
            "\nUnexpected missing values detected in "
            f"'{feature}'."
        )


print(
    "\nAll side-chain volume features have complete coverage."
)


# ============================================================
# 11. DISPLAY EXAMPLE MUTATIONS
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE SIDE-CHAIN VOLUME FEATURES")
print("=" * 70)


example_columns = [

    "Mutation",

    WT_COLUMN,

    MUTANT_COLUMN,

    "WT_Side_Chain_Volume",

    "Mutant_Side_Chain_Volume",

    "Side_Chain_Volume_Change",

    "Absolute_Side_Chain_Volume_Change",

    "Relative_Side_Chain_Volume_Change"
]


display(

    df[
        example_columns
    ]
    .head(
        10
    )
)


# ============================================================
# 12. SAVE THE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 13. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 12C COMPLETE")
print("=" * 70)


print(
    "\nOutput file saved successfully:"
)

print(
    OUTPUT_FILE
)


print(
    f"\nFinal dataset rows: "
    f"{len(df)}"
)

print(
    f"Final dataset columns: "
    f"{len(df.columns)}"
)


print(
    "\nNew side-chain volume features:"
)


for feature in new_feature_columns:

    print(
        f"  - {feature}"
    )


print(
    "\nSide-chain volume unit:"
)

print(
    "  Approximate Å³"
)


print(
    "\nFeature interpretation:"
)

print(
    "  Positive volume change:"
)

print(
    "    Mutant side chain is larger than wild type."
)


print(
    "  Negative volume change:"
)

print(
    "    Mutant side chain is smaller than wild type."
)


print(
    "\nNext recommended step:"
)

print(
    "  Part 12D — Hydrogen-bond donor and acceptor "
    "capacity features."
)

======================================================================
PART 12C — SIDE-CHAIN VOLUME FEATURE ENGINEERING
======================================================================

Input file loaded successfully:
VIM2_Part12B_Local_Sequence_Context.csv

Dataset rows: 5016
Dataset columns: 62

======================================================================
AMINO-ACID VALIDATION
======================================================================

All wild-type amino-acid identities were successfully validated.

All mutant amino-acid identities were successfully validated.

======================================================================
CALCULATING SIDE-CHAIN VOLUME FEATURES
======================================================================

======================================================================
FEATURE COVERAGE VALIDATION
======================================================================

WT_Side_Chain_Volume
  Missing values: 0

Mutant_Side_Chain_Volume
  Missing values: 0

Side_Chain_Volume_Change
  Missing values: 0

Absolute_Side_Chain_Volume_Change
  Missing values: 0

Relative_Side_Chain_Volume_Change
  Missing values: 0

All side-chain volume features have complete coverage.

======================================================================
EXAMPLE SIDE-CHAIN VOLUME FEATURES
======================================================================

,Mutation,WT_AA,Mutant_AA,WT_Side_Chain_Volume,Mutant_Side_Chain_Volume,Side_Chain_Volume_Change,Absolute_Side_Chain_Volume_Change,Relative_Side_Chain_Volume_Change
0,M1A,M,A,162.9,88.6,-74.3,74.3,-0.456108
1,M1C,M,C,162.9,108.5,-54.4,54.4,-0.333947
2,M1D,M,D,162.9,111.1,-51.8,51.8,-0.317986
3,M1E,M,E,162.9,138.4,-24.5,24.5,-0.150399
4,M1F,M,F,162.9,189.9,27.0,27.0,0.165746
5,M1G,M,G,162.9,60.1,-102.8,102.8,-0.631062
6,M1H,M,H,162.9,153.2,-9.7,9.7,-0.059546
7,M1I,M,I,162.9,166.7,3.8,3.8,0.023327
8,M1K,M,K,162.9,168.6,5.7,5.7,0.034991
9,M1L,M,L,162.9,166.7,3.8,3.8,0.023327

======================================================================
PART 12C COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part12C_Side_Chain_Volume.csv

Final dataset rows: 5016
Final dataset columns: 67

New side-chain volume features:
  - WT_Side_Chain_Volume
  - Mutant_Side_Chain_Volume
  - Side_Chain_Volume_Change
  - Absolute_Side_Chain_Volume_Change
  - Relative_Side_Chain_Volume_Change

Side-chain volume unit:
  Approximate Å³

Feature interpretation:
  Positive volume change:
    Mutant side chain is larger than wild type.
  Negative volume change:
    Mutant side chain is smaller than wild type.

Next recommended step:
  Part 12D — Hydrogen-bond donor and acceptor capacity features.

In [ ]:
# @title
# ============================================================
# PART 12D
# HYDROGEN-BOND DONOR AND ACCEPTOR CAPACITY FEATURES
#
# This script adds amino-acid side-chain hydrogen-bonding
# capacity features to the VIM-2 mutation dataset.
#
# The features describe the intrinsic hydrogen-bond donor and
# acceptor capacities of the wild-type and mutant side chains.
#
# These values represent standardized chemical capacities and
# do not imply that a hydrogen bond is necessarily formed in
# the resolved protein structure.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os

import numpy as np
import pandas as pd


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part12C_Side_Chain_Volume.csv"
)

OUTPUT_FILE = (
    "VIM2_Part12D_Hydrogen_Bonding.csv"
)

WT_COLUMN = "WT_AA"

MUTANT_COLUMN = "Mutant_AA"


# ============================================================
# 3. LOAD AND VALIDATE THE INPUT DATASET
# ============================================================

print("=" * 70)
print("PART 12D — HYDROGEN-BONDING CAPACITY FEATURE ENGINEERING")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        "\nInput file was not found:\n"
        f"{INPUT_FILE}"
    )


df = pd.read_csv(
    INPUT_FILE
)


print(
    "\nInput file loaded successfully:"
)

print(
    INPUT_FILE
)


print(
    f"\nDataset rows: "
    f"{len(df)}"
)

print(
    f"Dataset columns: "
    f"{len(df.columns)}"
)


# ============================================================
# 4. VALIDATE REQUIRED AMINO-ACID COLUMNS
# ============================================================

required_columns = [

    WT_COLUMN,

    MUTANT_COLUMN
]


missing_columns = [

    column

    for column in required_columns

    if column not in df.columns
]


if missing_columns:

    raise ValueError(
        "\nThe following required columns are missing:\n"
        f"{missing_columns}"
    )


# ============================================================
# 5. DEFINE STANDARD SIDE-CHAIN HYDROGEN-BOND CAPACITIES
# ============================================================

# The following dictionaries encode approximate intrinsic
# side-chain hydrogen-bond donor and acceptor capacities.
#
# These descriptors represent the chemical functionality of
# standard amino-acid side chains under conventional protein
# biochemistry assumptions.
#
# Backbone donor and acceptor atoms are intentionally excluded.
# Only side-chain functional groups are represented.


HBOND_DONOR_CAPACITY = {

    "A": 0,
    "R": 1,
    "N": 1,
    "D": 0,
    "C": 1,

    "Q": 1,
    "E": 0,
    "G": 0,
    "H": 1,
    "I": 0,

    "L": 0,
    "K": 1,
    "M": 0,
    "F": 0,
    "P": 0,

    "S": 1,
    "T": 1,
    "W": 1,
    "Y": 1,
    "V": 0
}


HBOND_ACCEPTOR_CAPACITY = {

    "A": 0,
    "R": 0,
    "N": 1,
    "D": 1,
    "C": 1,

    "Q": 1,
    "E": 1,
    "G": 0,
    "H": 1,
    "I": 0,

    "L": 0,
    "K": 0,
    "M": 1,
    "F": 0,
    "P": 0,

    "S": 1,
    "T": 1,
    "W": 0,
    "Y": 1,
    "V": 0
}


# ============================================================
# 6. STANDARDIZE AND VALIDATE AMINO-ACID IDENTITIES
# ============================================================

df[
    WT_COLUMN
] = (

    df[
        WT_COLUMN
    ]
    .astype(str)
    .str.strip()
    .str.upper()
)


df[
    MUTANT_COLUMN
] = (

    df[
        MUTANT_COLUMN
    ]
    .astype(str)
    .str.strip()
    .str.upper()
)


valid_amino_acids = set(
    HBOND_DONOR_CAPACITY.keys()
)


wt_amino_acids = set(
    df[WT_COLUMN].unique()
)


mutant_amino_acids = set(
    df[MUTANT_COLUMN].unique()
)


unknown_wt_amino_acids = (

    wt_amino_acids
    -
    valid_amino_acids
)


unknown_mutant_amino_acids = (

    mutant_amino_acids
    -
    valid_amino_acids
)


if unknown_wt_amino_acids:

    raise ValueError(
        "\nUnknown wild-type amino-acid codes detected:\n"
        f"{sorted(unknown_wt_amino_acids)}"
    )


if unknown_mutant_amino_acids:

    raise ValueError(
        "\nUnknown mutant amino-acid codes detected:\n"
        f"{sorted(unknown_mutant_amino_acids)}"
    )


print("\n" + "=" * 70)
print("AMINO-ACID VALIDATION")
print("=" * 70)


print(
    "\nAll wild-type amino-acid identities "
    "were successfully validated."
)


print(
    "\nAll mutant amino-acid identities "
    "were successfully validated."
)


# ============================================================
# 7. CALCULATE HYDROGEN-BOND DONOR FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING HYDROGEN-BOND DONOR FEATURES")
print("=" * 70)


df[
    "WT_HBond_Donor"
] = (

    df[
        WT_COLUMN
    ]
    .map(
        HBOND_DONOR_CAPACITY
    )
)


df[
    "Mutant_HBond_Donor"
] = (

    df[
        MUTANT_COLUMN
    ]
    .map(
        HBOND_DONOR_CAPACITY
    )
)


df[
    "HBond_Donor_Change"
] = (

    df[
        "Mutant_HBond_Donor"
    ]

    -

    df[
        "WT_HBond_Donor"
    ]
)


# ============================================================
# 8. CALCULATE HYDROGEN-BOND ACCEPTOR FEATURES
# ============================================================

print("\n" + "=" * 70)
print("CALCULATING HYDROGEN-BOND ACCEPTOR FEATURES")
print("=" * 70)


df[
    "WT_HBond_Acceptor"
] = (

    df[
        WT_COLUMN
    ]
    .map(
        HBOND_ACCEPTOR_CAPACITY
    )
)


df[
    "Mutant_HBond_Acceptor"
] = (

    df[
        MUTANT_COLUMN
    ]
    .map(
        HBOND_ACCEPTOR_CAPACITY
    )
)


df[
    "HBond_Acceptor_Change"
] = (

    df[
        "Mutant_HBond_Acceptor"
    ]

    -

    df[
        "WT_HBond_Acceptor"
    ]
)


# ============================================================
# 9. CALCULATE COMBINED HYDROGEN-BOND CAPACITY CHANGE
# ============================================================

# The combined descriptor summarizes the net change in total
# side-chain hydrogen-bonding capacity.

df[
    "WT_Total_HBond_Capacity"
] = (

    df[
        "WT_HBond_Donor"
    ]

    +

    df[
        "WT_HBond_Acceptor"
    ]
)


df[
    "Mutant_Total_HBond_Capacity"
] = (

    df[
        "Mutant_HBond_Donor"
    ]

    +

    df[
        "Mutant_HBond_Acceptor"
    ]
)


df[
    "Total_HBond_Capacity_Change"
] = (

    df[
        "Mutant_Total_HBond_Capacity"
    ]

    -

    df[
        "WT_Total_HBond_Capacity"
    ]
)


# ============================================================
# 10. FINAL FEATURE VALIDATION
# ============================================================

new_feature_columns = [

    "WT_HBond_Donor",

    "Mutant_HBond_Donor",

    "HBond_Donor_Change",

    "WT_HBond_Acceptor",

    "Mutant_HBond_Acceptor",

    "HBond_Acceptor_Change",

    "WT_Total_HBond_Capacity",

    "Mutant_Total_HBond_Capacity",

    "Total_HBond_Capacity_Change"
]


print("\n" + "=" * 70)
print("FEATURE COVERAGE VALIDATION")
print("=" * 70)


for feature in new_feature_columns:

    missing_count = (

        df[
            feature
        ]
        .isna()
        .sum()
    )


    print(
        f"\n{feature}"
    )

    print(
        f"  Missing values: "
        f"{missing_count}"
    )


    if missing_count > 0:

        raise ValueError(
            "\nUnexpected missing values detected in "
            f"'{feature}'."
        )


print(
    "\nAll hydrogen-bonding features have complete coverage."
)


# ============================================================
# 11. DISPLAY EXAMPLE MUTATIONS
# ============================================================

print("\n" + "=" * 70)
print("EXAMPLE HYDROGEN-BONDING FEATURES")
print("=" * 70)


example_columns = [

    "Mutation",

    WT_COLUMN,

    MUTANT_COLUMN,

    "WT_HBond_Donor",

    "Mutant_HBond_Donor",

    "HBond_Donor_Change",

    "WT_HBond_Acceptor",

    "Mutant_HBond_Acceptor",

    "HBond_Acceptor_Change",

    "WT_Total_HBond_Capacity",

    "Mutant_Total_HBond_Capacity",

    "Total_HBond_Capacity_Change"
]


display(
    df[
        example_columns
    ]
    .head(
        15
    )
)


# ============================================================
# 12. SAVE THE UPDATED DATASET
# ============================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# 13. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 12D COMPLETE")
print("=" * 70)


print(
    "\nOutput file saved successfully:"
)

print(
    OUTPUT_FILE
)


print(
    f"\nFinal dataset rows: "
    f"{len(df)}"
)

print(
    f"Final dataset columns: "
    f"{len(df.columns)}"
)


print(
    "\nNew hydrogen-bonding features:"
)


for feature in new_feature_columns:

    print(
        f"  - {feature}"
    )


print(
    "\nFeature interpretation:"
)

print(
    "  HBond_Donor_Change > 0:"
)

print(
    "    Mutation increases donor capacity."
)


print(
    "  HBond_Donor_Change < 0:"
)

print(
    "    Mutation decreases donor capacity."
)


print(
    "  HBond_Acceptor_Change > 0:"
)

print(
    "    Mutation increases acceptor capacity."
)


print(
    "  HBond_Acceptor_Change < 0:"
)

print(
    "    Mutation decreases acceptor capacity."
)


print(
    "\nAll values describe intrinsic side-chain "
    "chemical capacity."
)


print(
    "They do not directly indicate whether a specific "
    "hydrogen bond is formed in the resolved structure."
)


print(
    "\nNext recommended step:"
)

print(
    "  Review feature redundancy and assess whether additional "
    "mutation-specific features provide non-overlapping information."
)

======================================================================
PART 12D — HYDROGEN-BONDING CAPACITY FEATURE ENGINEERING
======================================================================

Input file loaded successfully:
VIM2_Part12C_Side_Chain_Volume.csv

Dataset rows: 5016
Dataset columns: 67

======================================================================
AMINO-ACID VALIDATION
======================================================================

All wild-type amino-acid identities were successfully validated.

All mutant amino-acid identities were successfully validated.

======================================================================
CALCULATING HYDROGEN-BOND DONOR FEATURES
======================================================================

======================================================================
CALCULATING HYDROGEN-BOND ACCEPTOR FEATURES
======================================================================

======================================================================
FEATURE COVERAGE VALIDATION
======================================================================

WT_HBond_Donor
  Missing values: 0

Mutant_HBond_Donor
  Missing values: 0

HBond_Donor_Change
  Missing values: 0

WT_HBond_Acceptor
  Missing values: 0

Mutant_HBond_Acceptor
  Missing values: 0

HBond_Acceptor_Change
  Missing values: 0

WT_Total_HBond_Capacity
  Missing values: 0

Mutant_Total_HBond_Capacity
  Missing values: 0

Total_HBond_Capacity_Change
  Missing values: 0

All hydrogen-bonding features have complete coverage.

======================================================================
EXAMPLE HYDROGEN-BONDING FEATURES
======================================================================

,Mutation,WT_AA,Mutant_AA,WT_HBond_Donor,Mutant_HBond_Donor,HBond_Donor_Change,WT_HBond_Acceptor,Mutant_HBond_Acceptor,HBond_Acceptor_Change,WT_Total_HBond_Capacity,Mutant_Total_HBond_Capacity,Total_HBond_Capacity_Change
0,M1A,M,A,0,0,0,1,0,-1,1,0,-1
1,M1C,M,C,0,1,1,1,1,0,1,2,1
2,M1D,M,D,0,0,0,1,1,0,1,1,0
3,M1E,M,E,0,0,0,1,1,0,1,1,0
4,M1F,M,F,0,0,0,1,0,-1,1,0,-1
5,M1G,M,G,0,0,0,1,0,-1,1,0,-1
6,M1H,M,H,0,1,1,1,1,0,1,2,1
7,M1I,M,I,0,0,0,1,0,-1,1,0,-1
8,M1K,M,K,0,1,1,1,0,-1,1,1,0
9,M1L,M,L,0,0,0,1,0,-1,1,0,-1
10,M1N,M,N,0,1,1,1,1,0,1,2,1
11,M1P,M,P,0,0,0,1,0,-1,1,0,-1
12,M1Q,M,Q,0,1,1,1,1,0,1,2,1
13,M1R,M,R,0,1,1,1,0,-1,1,1,0
14,M1S,M,S,0,1,1,1,1,0,1,2,1

======================================================================
PART 12D COMPLETE
======================================================================

Output file saved successfully:
VIM2_Part12D_Hydrogen_Bonding.csv

Final dataset rows: 5016
Final dataset columns: 76

New hydrogen-bonding features:
  - WT_HBond_Donor
  - Mutant_HBond_Donor
  - HBond_Donor_Change
  - WT_HBond_Acceptor
  - Mutant_HBond_Acceptor
  - HBond_Acceptor_Change
  - WT_Total_HBond_Capacity
  - Mutant_Total_HBond_Capacity
  - Total_HBond_Capacity_Change

Feature interpretation:
  HBond_Donor_Change > 0:
    Mutation increases donor capacity.
  HBond_Donor_Change < 0:
    Mutation decreases donor capacity.
  HBond_Acceptor_Change > 0:
    Mutation increases acceptor capacity.
  HBond_Acceptor_Change < 0:
    Mutation decreases acceptor capacity.

All values describe intrinsic side-chain chemical capacity.
They do not directly indicate whether a specific hydrogen bond is formed in the resolved structure.

Next recommended step:
  Review feature redundancy and assess whether additional mutation-specific features provide non-overlapping information.

In [ ]:
# @title
# ============================================================
# PART 12E
# FEATURE REDUNDANCY, VARIANCE, AND COVERAGE AUDIT
#
# This script performs a systematic quality-control audit of
# the engineered feature set.
#
# No features are added or removed in this step.
#
# The audit evaluates:
#   1. Feature coverage
#   2. Numeric feature variance
#   3. Constant / near-constant features
#   4. Highly correlated numeric features
#   5. Duplicate feature columns
#   6. Categorical feature cardinality
#   7. Structural-feature coverage
#
# The purpose is to identify redundant or potentially
# non-informative predictors before machine-learning modeling.
# ============================================================


# ============================================================
# 1. IMPORT REQUIRED PACKAGES
# ============================================================

import os
import numpy as np
import pandas as pd


# ============================================================
# 2. USER SETTINGS
# ============================================================

INPUT_FILE = (
    "VIM2_Part12D_Hydrogen_Bonding.csv"
)

OUTPUT_AUDIT_FILE = (
    "VIM2_Part12E_Feature_Audit.csv"
)

CORRELATION_THRESHOLD = 0.90

NEAR_CONSTANT_THRESHOLD = 0.01


# ============================================================
# 3. LOAD DATASET
# ============================================================

print("=" * 70)
print("PART 12E — FEATURE REDUNDANCY AND COVERAGE AUDIT")
print("=" * 70)


if not os.path.exists(INPUT_FILE):

    raise FileNotFoundError(
        "\nInput file was not found:\n"
        f"{INPUT_FILE}"
    )


df = pd.read_csv(
    INPUT_FILE
)


print(
    "\nInput file loaded successfully:"
)

print(
    INPUT_FILE
)


print(
    f"\nDataset rows: "
    f"{len(df)}"
)

print(
    f"Dataset columns: "
    f"{len(df.columns)}"
)


# ============================================================
# 4. DEFINE FEATURE GROUPS
# ============================================================

# These groups are used only for interpretation and reporting.
# They do not modify the dataset.

structural_features = [

    "Distance_to_Metal_Site",

    "Distance_to_Active_Site_Pocket",

    "Distance_to_L3_Loop",

    "Distance_to_L10_Loop",

    "SASA",

    "Secondary_Structure",

    "DSSP_Secondary_Structure",

    "Secondary_Structure_Code"
]


mutation_physicochemical_features = [

    "WT_Hydrophobicity",

    "Mutant_Hydrophobicity",

    "Hydrophobicity_Change",

    "WT_Weight",

    "Mutant_Weight",

    "Weight_Change",

    "WT_Charge",

    "Mutant_Charge",

    "Charge_Change",

    "WT_Polarity",

    "Mutant_Polarity",

    "Polarity_Change",

    "BLOSUM62"
]


side_chain_volume_features = [

    "WT_Side_Chain_Volume",

    "Mutant_Side_Chain_Volume",

    "Side_Chain_Volume_Change",

    "Absolute_Side_Chain_Volume_Change",

    "Relative_Side_Chain_Volume_Change"
]


hydrogen_bond_features = [

    "WT_HBond_Donor",

    "Mutant_HBond_Donor",

    "HBond_Donor_Change",

    "WT_HBond_Acceptor",

    "Mutant_HBond_Acceptor",

    "HBond_Acceptor_Change",

    "WT_Total_HBond_Capacity",

    "Mutant_Total_HBond_Capacity",

    "Total_HBond_Capacity_Change"
]


local_sequence_features = [

    "Local_Window_Length",

    "Local_Hydrophobic_Fraction",

    "Local_Charged_Fraction",

    "Local_Positive_Charge_Fraction",

    "Local_Negative_Charge_Fraction",

    "Local_Polar_Fraction",

    "Local_Aromatic_Fraction",

    "Local_Gly_Pro_Fraction",

    "Local_Sequence_Entropy"
]


# ============================================================
# 5. VERIFY FEATURE GROUPS
# ============================================================

all_defined_features = (

    structural_features
    +
    mutation_physicochemical_features
    +
    side_chain_volume_features
    +
    hydrogen_bond_features
    +
    local_sequence_features
)


missing_defined_features = [

    feature

    for feature in all_defined_features

    if feature not in df.columns
]


if missing_defined_features:

    raise ValueError(
        "\nThe following expected features are missing:\n"
        f"{missing_defined_features}"
    )


print("\n" + "=" * 70)
print("FEATURE GROUP VALIDATION")
print("=" * 70)


print(
    "\nAll expected engineered feature groups "
    "are present in the dataset."
)


# ============================================================
# 6. IDENTIFY NUMERIC AND NON-NUMERIC FEATURES
# ============================================================

numeric_columns = (

    df
    .select_dtypes(
        include=np.number
    )
    .columns
    .tolist()
)


non_numeric_columns = (

    df
    .select_dtypes(
        exclude=np.number
    )
    .columns
    .tolist()
)


print("\n" + "=" * 70)
print("DATA TYPE SUMMARY")
print("=" * 70)


print(
    f"\nNumeric columns: "
    f"{len(numeric_columns)}"
)


print(
    f"Non-numeric columns: "
    f"{len(non_numeric_columns)}"
)


# ============================================================
# 7. FEATURE COVERAGE AUDIT
# ============================================================

print("\n" + "=" * 70)
print("FEATURE COVERAGE AUDIT")
print("=" * 70)


coverage_records = []


for column in df.columns:

    missing_count = int(
        df[column].isna().sum()
    )

    non_missing_count = int(
        df[column].notna().sum()
    )

    coverage_percent = (

        non_missing_count
        /
        len(df)
        *
        100
    )


    coverage_records.append({

        "Feature": column,

        "Data_Type": str(
            df[column].dtype
        ),

        "Missing_Count": missing_count,

        "Non_Missing_Count": non_missing_count,

        "Coverage_Percent": coverage_percent

    })


coverage_df = pd.DataFrame(
    coverage_records
)


print(
    "\nFeatures with incomplete coverage:"
)


incomplete_coverage = (

    coverage_df[
        coverage_df[
            "Coverage_Percent"
        ]
        <
        100
    ]
)


if len(incomplete_coverage) == 0:

    print(
        "  None"
    )

else:

    print(
        incomplete_coverage[
            [
                "Feature",
                "Missing_Count",
                "Coverage_Percent"
            ]
        ]
        .to_string(
            index=False
        )
    )


# ============================================================
# 8. NUMERIC FEATURE VARIANCE AUDIT
# ============================================================

print("\n" + "=" * 70)
print("NUMERIC FEATURE VARIANCE AUDIT")
print("=" * 70)


variance_records = []


for column in numeric_columns:

    series = df[column]

    variance = series.var(
        skipna=True
    )

    unique_count = series.nunique(
        dropna=True
    )

    variance_records.append({

        "Feature": column,

        "Variance": variance,

        "Unique_Values": unique_count

    })


variance_df = pd.DataFrame(
    variance_records
)


# Identify constant numeric features.
constant_features = (

    variance_df[
        variance_df[
            "Variance"
        ]
        ==
        0
    ]
)


print(
    "\nConstant numeric features:"
)


if len(constant_features) == 0:

    print(
        "  None"
    )

else:

    print(
        constant_features[
            [
                "Feature",
                "Variance",
                "Unique_Values"
            ]
        ]
        .to_string(
            index=False
        )
    )


# ============================================================
# 9. NEAR-CONSTANT FEATURE AUDIT
# ============================================================

print("\n" + "=" * 70)
print("NEAR-CONSTANT FEATURE AUDIT")
print("=" * 70)


near_constant_records = []


for column in numeric_columns:

    value_counts = (

        df[column]
        .value_counts(
            normalize=True,
            dropna=True
        )
    )


    if len(value_counts) == 0:

        continue


    dominant_fraction = (
        value_counts.iloc[0]
    )


    if (
        dominant_fraction
        >=
        1
        -
        NEAR_CONSTANT_THRESHOLD
    ):

        near_constant_records.append({

            "Feature": column,

            "Dominant_Value": (
                value_counts.index[0]
            ),

            "Dominant_Fraction": (
                dominant_fraction
            ),

            "Unique_Values": (
                len(value_counts)
            )

        })


if len(near_constant_records) == 0:

    print(
        "\nNo near-constant numeric features "
        "were detected."
    )

else:

    near_constant_df = pd.DataFrame(
        near_constant_records
    )

    print(
        "\nPotential near-constant features:"
    )

    print(
        near_constant_df.to_string(
            index=False
        )
    )


# ============================================================
# 10. DUPLICATE COLUMN AUDIT
# ============================================================

print("\n" + "=" * 70)
print("DUPLICATE COLUMN AUDIT")
print("=" * 70)


duplicate_column_pairs = []


for i in range(
    len(df.columns)
):

    column_i = df.columns[i]


    for j in range(
        i + 1,
        len(df.columns)
    ):

        column_j = df.columns[j]


        if df[
            column_i
        ].equals(
            df[
                column_j
            ]
        ):

            duplicate_column_pairs.append({

                "Feature_1": column_i,

                "Feature_2": column_j

            })


if len(duplicate_column_pairs) == 0:

    print(
        "\nNo exact duplicate columns detected."
    )

else:

    duplicate_df = pd.DataFrame(
        duplicate_column_pairs
    )

    print(
        "\nExact duplicate columns:"
    )

    print(
        duplicate_df.to_string(
            index=False
        )
    )


# ============================================================
# 11. HIGH-CORRELATION AUDIT
# ============================================================

print("\n" + "=" * 70)
print("HIGH-CORRELATION NUMERIC FEATURE AUDIT")
print("=" * 70)


numeric_feature_df = df[
    numeric_columns
].copy()


correlation_matrix = (

    numeric_feature_df
    .corr(
        method="pearson"
    )
)


high_correlation_records = []


for i in range(
    len(correlation_matrix.columns)
):

    feature_i = (
        correlation_matrix.columns[i]
    )


    for j in range(
        i + 1,
        len(correlation_matrix.columns)
    ):

        feature_j = (
            correlation_matrix.columns[j]
        )


        correlation_value = (

            correlation_matrix.iloc[
                i,
                j
            ]
        )


        if pd.isna(
            correlation_value
        ):

            continue


        absolute_correlation = abs(
            correlation_value
        )


        if (
            absolute_correlation
            >=
            CORRELATION_THRESHOLD
        ):

            high_correlation_records.append({

                "Feature_1": feature_i,

                "Feature_2": feature_j,

                "Pearson_r": correlation_value,

                "Absolute_Pearson_r": (
                    absolute_correlation
                )

            })


high_correlation_df = pd.DataFrame(
    high_correlation_records
)


if len(high_correlation_df) == 0:

    print(
        "\nNo numeric feature pairs exceeded "
        f"|r| >= {CORRELATION_THRESHOLD:.2f}."
    )

else:

    high_correlation_df = (

        high_correlation_df
        .sort_values(
            "Absolute_Pearson_r",
            ascending=False
        )
    )


    print(
        "\nHighly correlated numeric feature pairs:"
    )

    print(
        high_correlation_df.to_string(
            index=False
        )
    )


# ============================================================
# 12. EXPECTED STRUCTURAL FEATURE COVERAGE
# ============================================================

print("\n" + "=" * 70)
print("STRUCTURAL FEATURE COVERAGE")
print("=" * 70)


structural_coverage_records = []


for feature in structural_features:

    missing_count = int(
        df[feature].isna().sum()
    )

    coverage_percent = (

        df[feature].notna().mean()
        *
        100
    )


    structural_coverage_records.append({

        "Feature": feature,

        "Missing_Count": missing_count,

        "Coverage_Percent": coverage_percent

    })


structural_coverage_df = pd.DataFrame(
    structural_coverage_records
)


print(
    structural_coverage_df.to_string(
        index=False
    )
)


# ============================================================
# 13. NON-NUMERIC FEATURE CARDINALITY AUDIT
# ============================================================

print("\n" + "=" * 70)
print("NON-NUMERIC FEATURE CARDINALITY AUDIT")
print("=" * 70)


categorical_records = []


for column in non_numeric_columns:

    unique_values = (

        df[column]
        .dropna()
        .astype(str)
        .nunique()
    )


    categorical_records.append({

        "Feature": column,

        "Unique_Values": unique_values

    })


categorical_df = pd.DataFrame(
    categorical_records
)


print(
    categorical_df.to_string(
        index=False
    )
)


# ============================================================
# 14. FEATURE GROUP SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("FEATURE GROUP SUMMARY")
print("=" * 70)


feature_group_summary = {

    "Structural": structural_features,

    "Mutation_Physicochemical":
        mutation_physicochemical_features,

    "Side_Chain_Volume":
        side_chain_volume_features,

    "Hydrogen_Bonding":
        hydrogen_bond_features,

    "Local_Sequence":
        local_sequence_features

}


for group_name, features in (
    feature_group_summary.items()
):

    print(
        f"\n{group_name}: "
        f"{len(features)} features"
    )


# ============================================================
# 15. SAVE COMPREHENSIVE AUDIT TABLE
# ============================================================

audit_df = coverage_df.merge(

    variance_df,

    on="Feature",

    how="left"

)


# Add correlation warning information.
#
# A feature is marked here only if it participates in at least
# one high-correlation pair. This is an audit flag, not an
# automatic deletion recommendation.

high_corr_features = set()


if len(high_correlation_df) > 0:

    high_corr_features.update(
        high_correlation_df[
            "Feature_1"
        ]
        .tolist()
    )

    high_corr_features.update(
        high_correlation_df[
            "Feature_2"
        ]
        .tolist()
    )


audit_df[
    "High_Correlation_Flag"
] = audit_df[
    "Feature"
].isin(
    high_corr_features
)


audit_df.to_csv(

    OUTPUT_AUDIT_FILE,

    index=False
)


# ============================================================
# 16. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 12E COMPLETE")
print("=" * 70)


print(
    "\nFeature audit file saved successfully:"
)

print(
    OUTPUT_AUDIT_FILE
)


print(
    f"\nDataset rows: "
    f"{len(df)}"
)


print(
    f"Dataset columns: "
    f"{len(df.columns)}"
)


print(
    f"\nNumeric features audited: "
    f"{len(numeric_columns)}"
)


print(
    f"Non-numeric features audited: "
    f"{len(non_numeric_columns)}"
)


print(
    f"Constant numeric features: "
    f"{len(constant_features)}"
)


print(
    f"Exact duplicate column pairs: "
    f"{len(duplicate_column_pairs)}"
)


print(
    f"Highly correlated feature pairs "
    f"(|r| >= {CORRELATION_THRESHOLD:.2f}): "
    f"{len(high_correlation_df)}"
)


print(
    "\nIMPORTANT:"
)


print(
    "No features were deleted or modified during this audit."
)


print(
    "High-correlation findings are reported for review only."
)


print(
    "\nNext recommended step:"
)


print(
    "Review the high-correlation pairs and determine which "
    "features should be retained based on biological meaning, "
    "interpretability, and machine-learning design."
)

======================================================================
PART 12E — FEATURE REDUNDANCY AND COVERAGE AUDIT
======================================================================

Input file loaded successfully:
VIM2_Part12D_Hydrogen_Bonding.csv

Dataset rows: 5016
Dataset columns: 76

======================================================================
FEATURE GROUP VALIDATION
======================================================================

All expected engineered feature groups are present in the dataset.

======================================================================
DATA TYPE SUMMARY
======================================================================

Numeric columns: 68
Non-numeric columns: 8

======================================================================
FEATURE COVERAGE AUDIT
======================================================================

Features with incomplete coverage:
                           Feature  Missing_Count  Coverage_Percent
                  128ug/mL_AMP_25C              7         99.860447
               128ug/mL_AMP_25C_SD             33         99.342105
                   16ug/mL_AMP_25C              7         99.860447
                16ug/mL_AMP_25C_SD             33         99.342105
                    2ug/mL_AMP_25C              7         99.860447
                 2ug/mL_AMP_25C_SD             33         99.342105
                  128ug/mL_AMP_37C             12         99.760766
               128ug/mL_AMP_37C_SD             50         99.003190
                   16ug/mL_AMP_37C             12         99.760766
                16ug/mL_AMP_37C_SD             50         99.003190
                    2ug/mL_AMP_37C             12         99.760766
                 2ug/mL_AMP_37C_SD             50         99.003190
                    4ug/mL_CTX_37C             12         99.760766
                 4ug/mL_CTX_37C_SD             50         99.003190
                  0.5ug/mL_CTX_37C             12         99.760766
               0.5ug/mL_CTX_37C_SD             50         99.003190
                0.031ug/mL_MEM_37C             12         99.760766
             0.031ug/mL_MEM_37C_SD             50         99.003190
            Distance_to_Metal_Site            681         86.423445
        Nearest_Metal_Site_Residue            681         86.423445
    Distance_to_Active_Site_Pocket            681         86.423445
Nearest_Active_Site_Pocket_Residue            681         86.423445
               Distance_to_L3_Loop            681         86.423445
                Nearest_L3_Residue            681         86.423445
              Distance_to_L10_Loop            681         86.423445
               Nearest_L10_Residue            681         86.423445
                              SASA            681         86.423445
               Secondary_Structure            681         86.423445
          DSSP_Secondary_Structure            681         86.423445
          Secondary_Structure_Code            681         86.423445

======================================================================
NUMERIC FEATURE VARIANCE AUDIT
======================================================================

Constant numeric features:
  None

======================================================================
NEAR-CONSTANT FEATURE AUDIT
======================================================================

No near-constant numeric features were detected.

======================================================================
DUPLICATE COLUMN AUDIT
======================================================================

Exact duplicate columns:
Feature_1         Feature_2
 position          Position
 position Sequence_Position
 Position Sequence_Position

======================================================================
HIGH-CORRELATION NUMERIC FEATURE AUDIT
======================================================================

Highly correlated numeric feature pairs:
               Feature_1                         Feature_2  Pearson_r  Absolute_Pearson_r
                position                          Position   1.000000            1.000000
                position                 Sequence_Position   1.000000            1.000000
                Position                 Sequence_Position   1.000000            1.000000
                position                             group   0.989617            0.989617
                   group                          Position   0.989617            0.989617
                   group                 Sequence_Position   0.989617            0.989617
         16ug/mL_AMP_37C                  0.5ug/mL_CTX_37C   0.972226            0.972226
        128ug/mL_AMP_37C                0.031ug/mL_MEM_37C   0.959510            0.959510
          4ug/mL_CTX_37C                0.031ug/mL_MEM_37C   0.956046            0.956046
        128ug/mL_AMP_25C                  128ug/mL_AMP_37C   0.951422            0.951422
        128ug/mL_AMP_37C                    4ug/mL_CTX_37C   0.945521            0.945521
  Distance_to_Metal_Site    Distance_to_Active_Site_Pocket   0.933901            0.933901
Side_Chain_Volume_Change Relative_Side_Chain_Volume_Change   0.932795            0.932795
         16ug/mL_AMP_25C                   16ug/mL_AMP_37C   0.919054            0.919054
        128ug/mL_AMP_25C                0.031ug/mL_MEM_37C   0.917175            0.917175
           Mutant_Weight          Mutant_Side_Chain_Volume   0.916248            0.916248
        128ug/mL_AMP_25C                    4ug/mL_CTX_37C   0.915383            0.915383
         16ug/mL_AMP_25C                  0.5ug/mL_CTX_37C   0.912722            0.912722
             WT_Polarity           WT_Total_HBond_Capacity   0.911259            0.911259
           Weight_Change          Side_Chain_Volume_Change   0.903127            0.903127

======================================================================
STRUCTURAL FEATURE COVERAGE
======================================================================
                       Feature  Missing_Count  Coverage_Percent
        Distance_to_Metal_Site            681         86.423445
Distance_to_Active_Site_Pocket            681         86.423445
           Distance_to_L3_Loop            681         86.423445
          Distance_to_L10_Loop            681         86.423445
                          SASA            681         86.423445
           Secondary_Structure            681         86.423445
      DSSP_Secondary_Structure            681         86.423445
      Secondary_Structure_Code            681         86.423445

======================================================================
NON-NUMERIC FEATURE CARDINALITY AUDIT
======================================================================
                 Feature  Unique_Values
                   index           5016
                   WT_AA             20
               Mutant_AA             20
                identity              1
                Mutation           5016
     Secondary_Structure              3
DSSP_Secondary_Structure              7
            Local_Window            266

======================================================================
FEATURE GROUP SUMMARY
======================================================================

Structural: 8 features

Mutation_Physicochemical: 13 features

Side_Chain_Volume: 5 features

Hydrogen_Bonding: 9 features

Local_Sequence: 9 features

======================================================================
PART 12E COMPLETE
======================================================================

Feature audit file saved successfully:
VIM2_Part12E_Feature_Audit.csv

Dataset rows: 5016
Dataset columns: 76

Numeric features audited: 68
Non-numeric features audited: 8
Constant numeric features: 0
Exact duplicate column pairs: 3
Highly correlated feature pairs (|r| >= 0.90): 20

IMPORTANT:
No features were deleted or modified during this audit.
High-correlation findings are reported for review only.

Next recommended step:
Review the high-correlation pairs and determine which features should be retained based on biological meaning, interpretability, and machine-learning design.

In [ ]:
# @title
# ============================================================
# PART 12F — ML-READY FEATURE DESIGN AND CLEANING
#
# Purpose:
#   Convert the engineered dataset into a clean, interpretable
#   feature table suitable for downstream machine-learning.
#
# IMPORTANT:
#   - Experimental assay columns are preserved as targets.
#   - Structural NaN values are NOT artificially imputed.
#   - No target information is used to construct predictors.
#   - Redundant metadata columns are excluded from predictors.
#   - Categorical biological features are encoded explicitly.
#   - The original dataset remains unchanged.
# ============================================================

import os
import numpy as np
import pandas as pd


# ============================================================
# 1. SETTINGS
# ============================================================

INPUT_FILE = "VIM2_Part12D_Hydrogen_Bonding.csv"

OUTPUT_FEATURE_FILE = (
    "VIM2_Part12F_ML_Feature_Table.csv"
)

OUTPUT_METADATA_FILE = (
    "VIM2_Part12F_Feature_Metadata.csv"
)


# ============================================================
# 2. LOAD DATASET
# ============================================================

print("=" * 70)
print("PART 12F — ML-READY FEATURE DESIGN")
print("=" * 70)

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"\nInput file not found:\n{INPUT_FILE}"
    )

df = pd.read_csv(INPUT_FILE)

print("\nInput dataset loaded successfully:")
print(INPUT_FILE)

print(f"\nDataset rows: {len(df)}")
print(f"Dataset columns: {len(df.columns)}")


# ============================================================
# 3. DEFINE EXPERIMENTAL TARGET COLUMNS
#
# These columns represent experimental measurements.
# They must NOT be used as predictors when predicting the
# corresponding experimental phenotype.
# ============================================================

target_columns = [

    "128ug/mL_AMP_25C",
    "128ug/mL_AMP_25C_SD",

    "16ug/mL_AMP_25C",
    "16ug/mL_AMP_25C_SD",

    "2ug/mL_AMP_25C",
    "2ug/mL_AMP_25C_SD",

    "128ug/mL_AMP_37C",
    "128ug/mL_AMP_37C_SD",

    "16ug/mL_AMP_37C",
    "16ug/mL_AMP_37C_SD",

    "2ug/mL_AMP_37C",
    "2ug/mL_AMP_37C_SD",

    "4ug/mL_CTX_37C",
    "4ug/mL_CTX_37C_SD",

    "0.5ug/mL_CTX_37C",
    "0.5ug/mL_CTX_37C_SD",

    "0.031ug/mL_MEM_37C",
    "0.031ug/mL_MEM_37C_SD"
]


missing_targets = [
    col
    for col in target_columns
    if col not in df.columns
]

if missing_targets:
    raise ValueError(
        "\nExpected experimental target columns are missing:\n"
        f"{missing_targets}"
    )


# ============================================================
# 4. DEFINE METADATA / IDENTIFIER COLUMNS
#
# These columns identify observations but are not biological
# predictors.
# ============================================================

metadata_columns = [

    "index",
    "identity",
    "Mutation"
]


# ============================================================
# 5. DEFINE REDUNDANT POSITION COLUMNS
#
# position, Position, and Sequence_Position contain the same
# residue-position information.
#
# We retain one canonical representation:
#     Sequence_Position
#
# The other duplicated representations are excluded from the
# ML predictor matrix.
# ============================================================

redundant_position_columns = [

    "position",
    "Position"
]


# ============================================================
# 6. DEFINE RAW STRUCTURAL ANNOTATION COLUMNS
#
# The categorical DSSP representation is retained.
# The numerical DSSP code is excluded because it represents
# the same annotation in an arbitrary numeric coding scheme.
#
# The textual Secondary_Structure and DSSP annotation also
# overlap substantially. We retain DSSP as the primary
# structural representation.
# ============================================================

redundant_structure_columns = [

    "Secondary_Structure",
    "Secondary_Structure_Code"
]


# ============================================================
# 7. DEFINE AUXILIARY NEAREST-RESIDUE ANNOTATIONS
#
# These are useful for interpretation but are not directly
# suitable as numerical ML predictors.
# ============================================================

auxiliary_annotation_columns = [

    "Nearest_Metal_Site_Residue",

    "Nearest_Active_Site_Pocket_Residue",

    "Nearest_L3_Residue",

    "Nearest_L10_Residue"
]


# ============================================================
# 8. DEFINE LOCAL WINDOW RAW SEQUENCE COLUMN
#
# Local_Window contains a complete amino-acid sequence string.
# We do not feed the raw string directly into the numerical
# ML matrix.
#
# Its derived numerical descriptors are already represented by:
#   - Local_Hydrophobic_Fraction
#   - Local_Charged_Fraction
#   - Local_Polar_Fraction
#   - Local_Aromatic_Fraction
#   - Local_Gly_Pro_Fraction
#   - Local_Sequence_Entropy
#
# Therefore the raw Local_Window string is preserved separately
# as annotation, but excluded from the numerical predictor set.
# ============================================================

raw_sequence_annotation_columns = [

    "Local_Window"
]


# ============================================================
# 9. DEFINE PRIMARY BIOLOGICAL FEATURE CANDIDATES
# ============================================================

primary_numeric_features = [

    # Mutation physicochemical changes
    "Hydrophobicity_Change",
    "Weight_Change",
    "Charge_Change",
    "Polarity_Change",

    # Evolutionary substitution score
    "BLOSUM62",

    # Side-chain volume
    "Side_Chain_Volume_Change",
    "Absolute_Side_Chain_Volume_Change",
    "Relative_Side_Chain_Volume_Change",

    # Hydrogen-bonding changes
    "HBond_Donor_Change",
    "HBond_Acceptor_Change",
    "Total_HBond_Capacity_Change",

    # Structural descriptors
    "Distance_to_Metal_Site",
    "Distance_to_Active_Site_Pocket",
    "Distance_to_L3_Loop",
    "Distance_to_L10_Loop",
    "SASA",

    # Position
    "Sequence_Position",

    # Local sequence context
    "Local_Window_Length",
    "Local_Hydrophobic_Fraction",
    "Local_Charged_Fraction",
    "Local_Positive_Charge_Fraction",
    "Local_Negative_Charge_Fraction",
    "Local_Polar_Fraction",
    "Local_Aromatic_Fraction",
    "Local_Gly_Pro_Fraction",
    "Local_Sequence_Entropy"
]


# ============================================================
# 10. VERIFY PRIMARY FEATURES
# ============================================================

missing_primary_features = [

    feature
    for feature in primary_numeric_features
    if feature not in df.columns
]

if missing_primary_features:
    raise ValueError(
        "\nExpected primary features are missing:\n"
        f"{missing_primary_features}"
    )


# ============================================================
# 11. DEFINE AMINO-ACID CATEGORICAL FEATURES
#
# WT_AA and Mutant_AA are biologically meaningful categorical
# variables.
#
# We retain them as categorical metadata at this stage.
#
# They are NOT arbitrarily converted to integers such as:
# A=1, C=2, D=3 ...
#
# Such numbering would create false quantitative relationships.
# ============================================================

categorical_features = [

    "WT_AA",
    "Mutant_AA"
]


for feature in categorical_features:

    if feature not in df.columns:
        raise ValueError(
            f"\nMissing categorical feature: {feature}"
        )


# ============================================================
# 12. CONSTRUCT ML CANDIDATE TABLE
#
# This table contains:
#   - numerical biological predictors
#   - categorical amino-acid predictors
#
# Experimental targets remain outside this table.
# ============================================================

feature_columns = (
    primary_numeric_features
    +
    categorical_features
)

X_candidate = df[
    feature_columns
].copy()


# ============================================================
# 13. REMOVE FEATURES WITH ZERO VARIANCE
#
# Constant predictors contain no information for ML.
# ============================================================

constant_features = []

for feature in primary_numeric_features:

    if X_candidate[feature].nunique(
        dropna=True
    ) <= 1:

        constant_features.append(feature)


if constant_features:

    X_candidate = X_candidate.drop(
        columns=constant_features
    )


# ============================================================
# 14. REPORT STRUCTURAL MISSINGNESS
#
# Structural NaN values are expected for unresolved residues.
#
# We DO NOT replace them with:
#   - zero
#   - mean
#   - median
#   - random values
#
# The missingness is biologically meaningful and will be
# handled explicitly during model development.
# ============================================================

structural_features = [

    "Distance_to_Metal_Site",
    "Distance_to_Active_Site_Pocket",
    "Distance_to_L3_Loop",
    "Distance_to_L10_Loop",
    "SASA"
]


print("\n" + "=" * 70)
print("STRUCTURAL MISSINGNESS REVIEW")
print("=" * 70)

for feature in structural_features:

    missing_count = int(
        X_candidate[feature].isna().sum()
    )

    coverage = (
        X_candidate[feature]
        .notna()
        .mean()
        *
        100
    )

    print(
        f"{feature:<40}"
        f" Missing: {missing_count:<5}"
        f" Coverage: {coverage:.2f}%"
    )


# ============================================================
# 15. CREATE FEATURE METADATA TABLE
#
# This provides a transparent record of why each feature is
# included or excluded.
# ============================================================

metadata_records = []


for feature in df.columns:

    if feature in target_columns:

        role = "Target"

        reason = (
            "Experimental phenotype / measurement; "
            "excluded from predictor matrix to prevent "
            "target leakage."
        )

    elif feature in metadata_columns:

        role = "Metadata"

        reason = (
            "Observation identifier or metadata; "
            "not a biological predictor."
        )

    elif feature in redundant_position_columns:

        role = "Excluded_Redundant"

        reason = (
            "Duplicate representation of residue position; "
            "Sequence_Position retained as canonical position."
        )

    elif feature in redundant_structure_columns:

        role = "Excluded_Redundant"

        reason = (
            "Redundant structural annotation representation; "
            "DSSP_Secondary_Structure retained."
        )

    elif feature in auxiliary_annotation_columns:

        role = "Annotation"

        reason = (
            "Nearest-residue structural annotation retained "
            "for interpretation but excluded from numerical "
            "predictor matrix."
        )

    elif feature in raw_sequence_annotation_columns:

        role = "Sequence_Annotation"

        reason = (
            "Raw local sequence window; retained as annotation "
            "but not directly supplied to numerical ML models."
        )

    elif feature in categorical_features:

        role = "Categorical_Predictor"

        reason = (
            "Amino-acid identity; retained as categorical "
            "biological predictor and should be encoded explicitly "
            "during model training."
        )

    elif feature in X_candidate.columns:

        role = "Numeric_Predictor"

        reason = (
            "Engineered biological predictor retained for "
            "downstream ML evaluation."
        )

    else:

        role = "Other"

        reason = (
            "Not selected for the current ML candidate matrix."
        )


    metadata_records.append({

        "Feature": feature,

        "Role": role,

        "Reason": reason,

        "Data_Type": str(
            df[feature].dtype
        ),

        "Missing_Count": int(
            df[feature].isna().sum()
        ),

        "Coverage_Percent": (
            df[feature].notna().mean()
            *
            100
        ),

        "Unique_Values": int(
            df[feature].nunique(
                dropna=True
            )
        )

    })


feature_metadata = pd.DataFrame(
    metadata_records
)


# ============================================================
# 16. SAVE ML CANDIDATE FEATURE TABLE
#
# The experimental target columns are deliberately not included
# in this predictor table.
#
# WT_AA and Mutant_AA remain categorical strings.
# Structural NaNs remain NaN.
# ============================================================

X_candidate.to_csv(
    OUTPUT_FEATURE_FILE,
    index=False
)


feature_metadata.to_csv(
    OUTPUT_METADATA_FILE,
    index=False
)


# ============================================================
# 17. FINAL VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("FINAL ML FEATURE TABLE VALIDATION")
print("=" * 70)

print(
    f"\nML candidate rows: "
    f"{len(X_candidate)}"
)

print(
    f"ML candidate columns: "
    f"{len(X_candidate.columns)}"
)


print(
    "\nCategorical predictors:"
)

print(
    categorical_features
)


print(
    "\nExperimental targets excluded:"
)

print(
    f"{len(target_columns)} target columns"
)


print(
    "\nConstant features removed:"
)

print(
    constant_features
    if constant_features
    else "None"
)


# Check that no target column accidentally entered X.
target_leakage = [

    col
    for col in target_columns
    if col in X_candidate.columns
]

if target_leakage:

    raise ValueError(
        "\nTARGET LEAKAGE DETECTED:\n"
        f"{target_leakage}"
    )


print(
    "\nTarget leakage check: PASS"
)


# ============================================================
# 18. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("PART 12F COMPLETE")
print("=" * 70)

print(
    "\nML candidate feature table saved successfully:"
)

print(
    OUTPUT_FEATURE_FILE
)

print(
    "\nFeature metadata saved successfully:"
)

print(
    OUTPUT_METADATA_FILE
)

print(
    "\nImportant design decisions:"
)

print(
    "  - Experimental assay columns excluded from predictors."
)

print(
    "  - Duplicate position columns excluded."
)

print(
    "  - Redundant DSSP numeric code excluded."
)

print(
    "  - Nearest-residue annotations excluded from numerical predictors."
)

print(
    "  - Raw Local_Window retained only as sequence annotation."
)

print(
    "  - WT_AA and Mutant_AA retained as categorical predictors."
)

print(
    "  - Structural NaN values remain unchanged."
)

print(
    "  - No artificial structural values were generated."
)

print(
    "\nNext step:"
)

print(
    "Part 12G — Final predictor review, categorical encoding, "
    "and target-specific ML dataset construction."
)

======================================================================
PART 12F — ML-READY FEATURE DESIGN
======================================================================

Input dataset loaded successfully:
VIM2_Part12D_Hydrogen_Bonding.csv

Dataset rows: 5016
Dataset columns: 76

======================================================================
STRUCTURAL MISSINGNESS REVIEW
======================================================================
Distance_to_Metal_Site                   Missing: 681   Coverage: 86.42%
Distance_to_Active_Site_Pocket           Missing: 681   Coverage: 86.42%
Distance_to_L3_Loop                      Missing: 681   Coverage: 86.42%
Distance_to_L10_Loop                     Missing: 681   Coverage: 86.42%
SASA                                     Missing: 681   Coverage: 86.42%

======================================================================
FINAL ML FEATURE TABLE VALIDATION
======================================================================

ML candidate rows: 5016
ML candidate columns: 28

Categorical predictors:
['WT_AA', 'Mutant_AA']

Experimental targets excluded:
18 target columns

Constant features removed:
None

Target leakage check: PASS

======================================================================
PART 12F COMPLETE
======================================================================

ML candidate feature table saved successfully:
VIM2_Part12F_ML_Feature_Table.csv

Feature metadata saved successfully:
VIM2_Part12F_Feature_Metadata.csv

Important design decisions:
  - Experimental assay columns excluded from predictors.
  - Duplicate position columns excluded.
  - Redundant DSSP numeric code excluded.
  - Nearest-residue annotations excluded from numerical predictors.
  - Raw Local_Window retained only as sequence annotation.
  - WT_AA and Mutant_AA retained as categorical predictors.
  - Structural NaN values remain unchanged.
  - No artificial structural values were generated.

Next step:
Part 12G — Final predictor review, categorical encoding, and target-specific ML dataset construction.

In [ ]:
# @title
# ================================================================
# PART 12A.0 — INDEPENDENT VIM HOMOLOG SEQUENCE RETRIEVAL
# ================================================================
#
# Purpose:
#   Build an independent VIM-type protein sequence set from NCBI
#   for downstream evolutionary analysis.
#
# Important methodological rule:
#   The original DMS dataset and its natural-variant table are NOT
#   used as the evolutionary sequence source.
#
# This part performs ONLY:
#   1. Wild-type VIM-2 sequence reconstruction from our dataset
#   2. NCBI Protein retrieval
#   3. Basic sequence QC
#   4. Pairwise identity / coverage filtering
#   5. Exact-sequence deduplication
#   6. Output of a curated FASTA sequence set
#
# MSA, Shannon entropy, and conservation scores are NOT calculated
# in this part.
#
# ================================================================


# ================================================================
# 1. INSTALL / IMPORT REQUIRED PACKAGES
# ================================================================

!pip -q install biopython pandas requests


import os
import re
import time
import hashlib
import requests
import pandas as pd

from io import StringIO

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Align import PairwiseAligner


# ================================================================
# 2. INPUT / OUTPUT FILES
# ================================================================

INPUT_FILE = "VIM2_Part12F_ML_Feature_Table.csv"

OUTPUT_FASTA = "VIM2_Part12A_Independent_Sequence_Set.fasta"

OUTPUT_METADATA = "VIM2_Part12A_Sequence_Metadata.csv"

OUTPUT_QC = "VIM2_Part12A_Retrieval_QC.csv"


# ================================================================
# 3. VIM-2 REFERENCE SETTINGS
# ================================================================

REFERENCE_LENGTH = 266

MIN_LENGTH = 250
MAX_LENGTH = 290

MIN_IDENTITY_PERCENT = 70.0
MIN_COVERAGE_PERCENT = 90.0


# ================================================================
# 4. NCBI SETTINGS
# ================================================================
#
# NCBI E-utilities provide programmatic access to the Protein
# database through ESearch and EFetch.
#
# We use a descriptive query for VIM-type proteins rather than
# simply searching for every metallo-beta-lactamase protein.
#
# ================================================================

NCBI_BASE = (
    "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
)

NCBI_EMAIL = "mynice.ir@gmail.com"

REQUEST_DELAY = 0.34


# ================================================================
# 5. LOAD THE EXISTING ML DATASET
# ================================================================

print("=" * 70)
print("PART 12A.0 — INDEPENDENT VIM SEQUENCE RETRIEVAL")
print("=" * 70)

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"\nInput file was not found:\n{INPUT_FILE}\n\n"
        "Make sure VIM2_Part12F_ML_Feature_Table.csv is uploaded "
        "to the current Google Colab session."
    )


df = pd.read_csv(INPUT_FILE)

print("\nInput file loaded successfully:")
print(INPUT_FILE)

print("\nDataset rows:", len(df))
print("Dataset columns:", len(df.columns))


# ================================================================
# 6. IDENTIFY POSITION / WILD-TYPE COLUMNS
# ================================================================
#
# The project contains several historical position columns.
#
# We select the first available position column and the WT_AA
# column used throughout the engineered dataset.
# ================================================================

position_candidates = [
    "Sequence_Position",
    "Position",
    "position"
]

position_column = None

for col in position_candidates:
    if col in df.columns:
        position_column = col
        break


if position_column is None:
    raise ValueError(
        "\nNo sequence-position column was found."
    )


if "WT_AA" not in df.columns:
    raise ValueError(
        "\nWT_AA column was not found in the input dataset."
    )


print("\nPosition column selected:")
print(" ", position_column)


# ================================================================
# 7. RECONSTRUCT THE EXACT 266-AA WILD-TYPE SEQUENCE
# ================================================================
#
# Multiple mutations may occur at the same residue position.
#
# Therefore, we cannot simply read rows sequentially.
#
# Instead:
#   position -> WT_AA
#
# is constructed and validated.
# ================================================================

sequence_map = {}

for _, row in df.iterrows():

    position = row[position_column]
    wt_aa = str(row["WT_AA"]).strip().upper()

    if pd.isna(position):
        continue

    if not re.fullmatch(r"[ACDEFGHIKLMNPQRSTVWY]", wt_aa):
        raise ValueError(
            f"Invalid WT amino acid '{wt_aa}' "
            f"at position {position}."
        )

    position = int(position)

    if position in sequence_map:

        if sequence_map[position] != wt_aa:
            raise ValueError(
                "\nWild-type identity inconsistency detected.\n"
                f"Position: {position}\n"
                f"Existing WT: {sequence_map[position]}\n"
                f"New WT: {wt_aa}"
            )

    else:
        sequence_map[position] = wt_aa


# ================================================================
# 8. VALIDATE POSITION COVERAGE
# ================================================================

expected_positions = set(range(1, REFERENCE_LENGTH + 1))

observed_positions = set(sequence_map.keys())

missing_positions = sorted(
    expected_positions - observed_positions
)

extra_positions = sorted(
    observed_positions - expected_positions
)


print("\n" + "=" * 70)
print("WILD-TYPE SEQUENCE VALIDATION")
print("=" * 70)

print("\nObserved sequence positions:")
print(len(observed_positions))

print("\nExpected sequence length:")
print(REFERENCE_LENGTH)


if missing_positions:

    raise ValueError(
        "\nThe WT sequence cannot be reconstructed completely.\n"
        f"Missing positions: {missing_positions}"
    )


if extra_positions:

    raise ValueError(
        "\nUnexpected sequence positions detected:\n"
        f"{extra_positions}"
    )


# ================================================================
# 9. BUILD THE 266-AA REFERENCE SEQUENCE
# ================================================================

reference_sequence = "".join(
    sequence_map[pos]
    for pos in range(1, REFERENCE_LENGTH + 1)
)


if len(reference_sequence) != REFERENCE_LENGTH:

    raise ValueError(
        "\nReconstructed reference sequence has an unexpected length."
    )


print("\nReference sequence reconstructed successfully.")

print("Reference length:", len(reference_sequence))

print("\nFirst 30 residues:")
print(reference_sequence[:30])

print("\nLast 30 residues:")
print(reference_sequence[-30:])


# ================================================================
# 10. VERIFY THAT THE REFERENCE CONTAINS ONLY STANDARD AMINO ACIDS
# ================================================================

valid_amino_acids = set(
    "ACDEFGHIKLMNPQRSTVWY"
)

invalid_reference_residues = sorted(
    set(reference_sequence) - valid_amino_acids
)


if invalid_reference_residues:

    raise ValueError(
        "\nInvalid amino acids found in reconstructed VIM-2:\n"
        f"{invalid_reference_residues}"
    )


print("\nReference amino-acid alphabet validation: PASS")


# ================================================================
# 11. NCBI ESEARCH FUNCTION
# ================================================================
#
# ESearch returns Protein record IDs matching the query.
#
# ================================================================

def ncbi_esearch(
    query,
    retmax=10000
):

    params = {
        "db": "protein",
        "term": query,
        "retmode": "json",
        "retmax": retmax,
        "email": NCBI_EMAIL
    }

    response = requests.get(
        f"{NCBI_BASE}/esearch.fcgi",
        params=params,
        timeout=60
    )

    response.raise_for_status()

    result = response.json()

    return result["esearchresult"]["idlist"]


# ================================================================
# 12. RETRIEVE NCBI PROTEIN RECORDS
# ================================================================
#
# The query is intentionally specific to VIM-type beta-lactamases.
#
# We also request a reasonably large number of records because
# the initial retrieval is followed by strict sequence QC.
# ================================================================

NCBI_QUERY = (
    '"VIM-type"'
    ' AND '
    '"metallo-beta-lactamase"'
    ' AND '
    'NOT partial[Title]'
)


print("\n" + "=" * 70)
print("NCBI SEQUENCE RETRIEVAL")
print("=" * 70)

print("\nNCBI query:")
print(NCBI_QUERY)


ncbi_ids = ncbi_esearch(
    NCBI_QUERY,
    retmax=10000
)


print("\nNCBI records retrieved:")
print(len(ncbi_ids))


if len(ncbi_ids) == 0:

    raise RuntimeError(
        "\nNCBI returned zero records.\n"
        "The retrieval query should be reviewed before continuing."
    )


# ================================================================
# 13. NCBI EFETCH FUNCTION
# ================================================================
#
# EFetch retrieves FASTA records corresponding to Protein IDs.
#
# NCBI recommends batching large requests rather than sending an
# extremely large list in one request.
# ================================================================

def ncbi_efetch_fasta(
    ids,
    batch_size=200
):

    all_records = []

    for start in range(
        0,
        len(ids),
        batch_size
    ):

        batch = ids[
            start:start + batch_size
        ]

        params = {
            "db": "protein",
            "id": ",".join(batch),
            "rettype": "fasta",
            "retmode": "text",
            "email": NCBI_EMAIL
        }

        response = requests.get(
            f"{NCBI_BASE}/efetch.fcgi",
            params=params,
            timeout=120
        )

        response.raise_for_status()

        fasta_text = response.text

        records = list(
            SeqIO.parse(
                StringIO(fasta_text),
                "fasta"
            )
        )

        all_records.extend(records)

        print(
            f"Retrieved batch "
            f"{start + 1}–"
            f"{min(start + batch_size, len(ids))} "
            f"/ {len(ids)}"
        )

        time.sleep(
            REQUEST_DELAY
        )

    return all_records


ncbi_records = ncbi_efetch_fasta(
    ncbi_ids
)


print("\nTotal FASTA records retrieved:")
print(len(ncbi_records))


# ================================================================
# 14. PAIRWISE ALIGNMENT SETUP
# ================================================================
#
# We use global alignment against the 266-aa VIM-2 reference.
#
# This allows us to calculate:
#
#   Identity
#   Alignment coverage
#
# in a reproducible manner.
#
# The alignment is intentionally simple at this stage.
# The final evolutionary analysis will use a proper MSA.
# ================================================================

aligner = PairwiseAligner()

aligner.mode = "global"

aligner.match_score = 2

aligner.mismatch_score = -1

aligner.open_gap_score = -2

aligner.extend_gap_score = -0.5


# ================================================================
# 15. SEQUENCE QC
# ================================================================

qc_records = []

accepted_records = []

seen_hashes = set()


for index, record in enumerate(
    ncbi_records,
    start=1
):

    sequence = str(
        record.seq
    ).upper().replace(
        " ",
        ""
    )


    # ------------------------------------------------------------
    # Basic metadata
    # ------------------------------------------------------------

    accession = record.id

    description = record.description

    sequence_length = len(
        sequence
    )


    # ------------------------------------------------------------
    # Check for invalid amino acids
    # ------------------------------------------------------------

    invalid_residues = sorted(
        set(sequence) - valid_amino_acids
    )

    if invalid_residues:

        qc_records.append({

            "Accession": accession,

            "Description": description,

            "Sequence_Length": sequence_length,

            "Identity_Percent": None,

            "Coverage_Percent": None,

            "Length_Pass": False,

            "Identity_Pass": False,

            "Coverage_Pass": False,

            "Duplicate": False,

            "Final_Status": "Rejected_Invalid_Amino_Acid"

        })

        continue


    # ------------------------------------------------------------
    # Length filtering
    # ------------------------------------------------------------

    length_pass = (
        MIN_LENGTH
        <= sequence_length
        <= MAX_LENGTH
    )


    if not length_pass:

        qc_records.append({

            "Accession": accession,

            "Description": description,

            "Sequence_Length": sequence_length,

            "Identity_Percent": None,

            "Coverage_Percent": None,

            "Length_Pass": False,

            "Identity_Pass": False,

            "Coverage_Pass": False,

            "Duplicate": False,

            "Final_Status": "Rejected_Length"

        })

        continue


    # ------------------------------------------------------------
    # Exact duplicate detection
    # ------------------------------------------------------------
    #
    # We hash the entire protein sequence.
    #
    # Different database records with identical sequences are
    # considered exact duplicates for conservation analysis.
    # ------------------------------------------------------------

    sequence_hash = hashlib.sha256(
        sequence.encode("utf-8")
    ).hexdigest()


    if sequence_hash in seen_hashes:

        qc_records.append({

            "Accession": accession,

            "Description": description,

            "Sequence_Length": sequence_length,

            "Identity_Percent": None,

            "Coverage_Percent": None,

            "Length_Pass": True,

            "Identity_Pass": None,

            "Coverage_Pass": None,

            "Duplicate": True,

            "Final_Status": "Rejected_Exact_Duplicate"

        })

        continue


    # ------------------------------------------------------------
    # Pairwise global alignment against VIM-2
    # ------------------------------------------------------------

    alignment = aligner.align(
        reference_sequence,
        sequence
    )[0]


    aligned_reference = str(
        alignment[0]
    )

    aligned_query = str(
        alignment[1]
    )


    # ------------------------------------------------------------
    # Calculate aligned residue identity
    # ------------------------------------------------------------

    identical_positions = 0

    aligned_reference_residues = 0


    for ref_aa, query_aa in zip(
        aligned_reference,
        aligned_query
    ):

        if ref_aa != "-":

            aligned_reference_residues += 1

            if (
                query_aa != "-"
                and
                ref_aa == query_aa
            ):

                identical_positions += 1


    # ------------------------------------------------------------
    # Identity
    #
    # Identity is calculated relative to the aligned VIM-2
    # reference positions.
    # ------------------------------------------------------------

    if aligned_reference_residues > 0:

        identity_percent = (
            identical_positions
            /
            aligned_reference_residues
        ) * 100.0

    else:

        identity_percent = 0.0


    # ------------------------------------------------------------
    # Query coverage
    #
    # Coverage describes how much of the 266-aa VIM-2 reference
    # participates in the alignment.
    # ------------------------------------------------------------

    coverage_percent = (
        aligned_reference_residues
        /
        REFERENCE_LENGTH
    ) * 100.0


    identity_pass = (
        identity_percent
        >= MIN_IDENTITY_PERCENT
    )

    coverage_pass = (
        coverage_percent
        >= MIN_COVERAGE_PERCENT
    )


    # ------------------------------------------------------------
    # Final sequence decision
    # ------------------------------------------------------------

    if (
        length_pass
        and
        identity_pass
        and
        coverage_pass
    ):

        final_status = "ACCEPTED"

        seen_hashes.add(
            sequence_hash
        )

        accepted_records.append(
            SeqRecord(
                Seq(sequence),
                id=accession,
                description=description
            )
        )

    else:

        final_status = "Rejected_Identity_or_Coverage"


    qc_records.append({

        "Accession": accession,

        "Description": description,

        "Sequence_Length": sequence_length,

        "Identity_Percent": round(
            identity_percent,
            3
        ),

        "Coverage_Percent": round(
            coverage_percent,
            3
        ),

        "Length_Pass": length_pass,

        "Identity_Pass": identity_pass,

        "Coverage_Pass": coverage_pass,

        "Duplicate": False,

        "Final_Status": final_status

    })


# ================================================================
# 16. CREATE QC TABLE
# ================================================================

qc_df = pd.DataFrame(
    qc_records
)


# ================================================================
# 17. ADD REFERENCE SEQUENCE
# ================================================================
#
# The reference itself must always be present in the final
# evolutionary sequence set.
#
# We identify it separately so that it is not accidentally removed
# during duplicate filtering.
# ================================================================

reference_record = SeqRecord(
    Seq(reference_sequence),
    id="VIM2_REFERENCE",
    description=(
        "VIM-2 reference sequence reconstructed "
        "from the validated project dataset"
    )
)


# ================================================================
# 18. REMOVE ANY IDENTICAL REFERENCE FROM THE ACCEPTED SET
# ================================================================

accepted_without_reference_duplicates = []


reference_hash = hashlib.sha256(
    reference_sequence.encode("utf-8")
).hexdigest()


for record in accepted_records:

    record_hash = hashlib.sha256(
        str(record.seq)
        .upper()
        .encode("utf-8")
    ).hexdigest()

    if record_hash != reference_hash:

        accepted_without_reference_duplicates.append(
            record
        )


accepted_records = (
    accepted_without_reference_duplicates
)


# ================================================================
# 19. FINAL SEQUENCE SET
# ================================================================

final_records = [
    reference_record
] + accepted_records


# ================================================================
# 20. FINAL METADATA TABLE
# ================================================================

metadata_records = []


for record in final_records:

    sequence = str(
        record.seq
    ).upper()


    sequence_hash = hashlib.sha256(
        sequence.encode("utf-8")
    ).hexdigest()


    metadata_records.append({

        "Sequence_ID": record.id,

        "Description": record.description,

        "Sequence_Length": len(sequence),

        "Is_VIM2_Reference": (
            record.id == "VIM2_REFERENCE"
        ),

        "Sequence_SHA256": sequence_hash,

        "Source": "NCBI Protein",

        "Independent_From_DMS_Dataset": True

    })


metadata_df = pd.DataFrame(
    metadata_records
)


# ================================================================
# 21. FINAL QC SUMMARY
# ================================================================

total_retrieved = len(
    ncbi_records
)

total_qc_records = len(
    qc_df
)

accepted_homologs = len(
    accepted_records
)

final_sequence_count = len(
    final_records
)

duplicate_count = int(
    qc_df["Duplicate"].fillna(False).sum()
)

invalid_count = int(
    (
        qc_df["Final_Status"]
        ==
        "Rejected_Invalid_Amino_Acid"
    ).sum()
)

length_rejected_count = int(
    (
        qc_df["Final_Status"]
        ==
        "Rejected_Length"
    ).sum()
)

identity_coverage_rejected_count = int(
    (
        qc_df["Final_Status"]
        ==
        "Rejected_Identity_or_Coverage"
    ).sum()
)


# ================================================================
# 22. SAVE OUTPUT FILES
# ================================================================

SeqIO.write(
    final_records,
    OUTPUT_FASTA,
    "fasta"
)


metadata_df.to_csv(
    OUTPUT_METADATA,
    index=False
)


qc_df.to_csv(
    OUTPUT_QC,
    index=False
)


# ================================================================
# 23. PRINT FINAL REPORT
# ================================================================

print("\n" + "=" * 70)
print("PART 12A.0 — RETRIEVAL AND QC COMPLETE")
print("=" * 70)

print("\nReference:")
print("  VIM-2")
print("  Length:", len(reference_sequence))

print("\nNCBI records retrieved:")
print(" ", total_retrieved)

print("\nAccepted independent VIM-type sequences:")
print(" ", accepted_homologs)

print("\nFinal sequence set including VIM-2 reference:")
print(" ", final_sequence_count)

print("\nExact duplicates removed:")
print(" ", duplicate_count)

print("\nInvalid amino-acid sequences rejected:")
print(" ", invalid_count)

print("\nLength-filtered sequences rejected:")
print(" ", length_rejected_count)

print("\nIdentity / coverage rejected:")
print(" ", identity_coverage_rejected_count)


print("\n" + "=" * 70)
print("FILTERING CRITERIA")
print("=" * 70)

print("\nLength:")
print(
    f"  {MIN_LENGTH}–{MAX_LENGTH} aa"
)

print("\nMinimum identity:")
print(
    f"  {MIN_IDENTITY_PERCENT}%"
)

print("\nMinimum reference coverage:")
print(
    f"  {MIN_COVERAGE_PERCENT}%"
)


print("\n" + "=" * 70)
print("OUTPUT FILES")
print("=" * 70)

print("\nFASTA:")
print(
    f"  {OUTPUT_FASTA}"
)

print("\nSequence metadata:")
print(
    f"  {OUTPUT_METADATA}"
)

print("\nRetrieval / QC report:")
print(
    f"  {OUTPUT_QC}"
)


print("\n" + "=" * 70)
print("NEXT STEP")
print("=" * 70)

print(
    "\nPart 12A.1 — Multiple Sequence Alignment (MSA)"
)

print(
    "\nIMPORTANT:"
)

print(
    "The sequence set is now frozen for downstream evolutionary analysis."
)

print(
    "No Shannon entropy or conservation features were calculated yet."
)

print(
    "\nPART 12A.0 COMPLETE"
)

======================================================================
PART 12A.0 — INDEPENDENT VIM SEQUENCE RETRIEVAL
======================================================================

Input file loaded successfully:
VIM2_Part12F_ML_Feature_Table.csv

Dataset rows: 5016
Dataset columns: 28

Position column selected:
  Sequence_Position

======================================================================
WILD-TYPE SEQUENCE VALIDATION
======================================================================

Observed sequence positions:
266

Expected sequence length:
266

Reference sequence reconstructed successfully.
Reference length: 266

First 30 residues:
MFKLLSKLLVYLTASIMAIASPLAFSVDSS

Last 30 residues:
IPGHGLPGGLDLLKHTTNVVKAHTNRSVVE

Reference amino-acid alphabet validation: PASS

======================================================================
NCBI SEQUENCE RETRIEVAL
======================================================================

NCBI query:
"VIM-type" AND "metallo-beta-lactamase" AND NOT partial[Title]

NCBI records retrieved:
52
Retrieved batch 1–52 / 52

Total FASTA records retrieved:
52

======================================================================
PART 12A.0 — RETRIEVAL AND QC COMPLETE
======================================================================

Reference:
  VIM-2
  Length: 266

NCBI records retrieved:
  52

Accepted independent VIM-type sequences:
  10

Final sequence set including VIM-2 reference:
  11

Exact duplicates removed:
  1

Invalid amino-acid sequences rejected:
  0

Length-filtered sequences rejected:
  41

Identity / coverage rejected:
  0

======================================================================
FILTERING CRITERIA
======================================================================

Length:
  250–290 aa

Minimum identity:
  70.0%

Minimum reference coverage:
  90.0%

======================================================================
OUTPUT FILES
======================================================================

FASTA:
  VIM2_Part12A_Independent_Sequence_Set.fasta

Sequence metadata:
  VIM2_Part12A_Sequence_Metadata.csv

Retrieval / QC report:
  VIM2_Part12A_Retrieval_QC.csv

======================================================================
NEXT STEP
======================================================================

Part 12A.1 — Multiple Sequence Alignment (MSA)

IMPORTANT:
The sequence set is now frozen for downstream evolutionary analysis.
No Shannon entropy or conservation features were calculated yet.

PART 12A.0 COMPLETE

In [ ]:
# @title
# ================================================================
# PART 12G — FINAL ML PREDICTOR REVIEW AND DATASET CONSTRUCTION
# ================================================================
#
# Purpose:
#   Construct the final ML-ready dataset by combining:
#
#       1. Final candidate predictors from Part 12F
#       2. Experimental assay targets from Part 12D
#
# Important:
#   Part 12F intentionally excluded the experimental target columns.
#   Therefore, experimental targets MUST be recovered from Part 12D.
#
# Data flow:
#
#       Part 12D
#       Original engineered dataset
#       + experimental assay measurements
#                  |
#                  | experimental targets
#                  v
#       Part 12F
#       ML candidate predictor table
#                  |
#                  | final predictors
#                  v
#       Part 12G
#       FINAL ML DATASET
#
# This part performs:
#
#   1. Load Part 12F predictors
#   2. Load Part 12D targets
#   3. Identify experimental target columns
#   4. Construct a stable mutation-level join key
#   5. Verify predictor/target identity consistency
#   6. Remove non-predictive metadata
#   7. Remove descriptive structural annotations
#   8. Preserve biologically meaningful structural NaN values
#   9. One-hot encode WT_AA and Mutant_AA
#  10. Remove constant predictors
#  11. Check duplicate columns
#  12. Check target leakage
#  13. Check numeric predictor integrity
#  14. Check row-level identity consistency
#  15. Save ONE final ML dataset
#
# Important methodological decisions:
#
#   - No artificial structural values are generated.
#   - Structural NaNs remain NaN.
#   - WT_AA and Mutant_AA are treated as categorical variables.
#   - Amino acids are NOT assigned arbitrary integer labels.
#   - Experimental targets are NEVER used as predictors.
#   - No train/test split is performed here.
#   - No feature scaling is performed here.
#   - No ML model is trained here.
#   - Evolutionary Part 12A features are intentionally excluded.
#
# ================================================================


# ================================================================
# 1. IMPORT REQUIRED LIBRARIES
# ================================================================

import os
import numpy as np
import pandas as pd


# ================================================================
# 2. FILE SETTINGS
# ================================================================

PREDICTOR_FILE = (
    "VIM2_Part12F_ML_Feature_Table.csv"
)

TARGET_SOURCE_FILE = (
    "VIM2_Part12D_Hydrogen_Bonding.csv"
)

OUTPUT_FILE = (
    "VIM2_Part12G_Final_ML_Dataset.csv"
)


# ================================================================
# 3. START REPORT
# ================================================================

print("=" * 70)
print("PART 12G — FINAL ML PREDICTOR REVIEW")
print("=" * 70)


# ================================================================
# 4. VERIFY INPUT FILES
# ================================================================
#
# Part 12F contains the predictor candidates.
#
# Part 12D contains the original engineered dataset including
# experimental assay measurements.
#
# Both files are required for correct reconstruction of the final
# ML dataset.
#
# ================================================================

if not os.path.exists(PREDICTOR_FILE):

    raise FileNotFoundError(
        "\nPart 12F predictor file was not found:\n"
        f"{PREDICTOR_FILE}\n\n"
        "Please make sure Part 12F was completed successfully."
    )


if not os.path.exists(TARGET_SOURCE_FILE):

    raise FileNotFoundError(
        "\nPart 12D target source file was not found:\n"
        f"{TARGET_SOURCE_FILE}\n\n"
        "Please make sure Part 12D was completed successfully."
    )


# ================================================================
# 5. LOAD INPUT DATASETS
# ================================================================

predictor_source = pd.read_csv(
    PREDICTOR_FILE
)

target_source = pd.read_csv(
    TARGET_SOURCE_FILE
)


print("\nInput files loaded successfully:")

print(
    f"  Predictor source: {PREDICTOR_FILE}"
)

print(
    f"  Target source:    {TARGET_SOURCE_FILE}"
)

print("\nPart 12F rows:")
print(
    f"  {len(predictor_source)}"
)

print("\nPart 12F columns:")
print(
    f"  {len(predictor_source.columns)}"
)

print("\nPart 12D rows:")
print(
    f"  {len(target_source)}"
)

print("\nPart 12D columns:")
print(
    f"  {len(target_source.columns)}"
)


# ================================================================
# 6. VERIFY BASIC ROW COUNTS
# ================================================================
#
# The predictor table and target source should describe the same
# mutation records.
#
# We require equal row counts before performing identity-based
# reconstruction.
#
# ================================================================

if len(predictor_source) != len(target_source):

    raise ValueError(
        "\nPredictor and target source row counts do not match.\n\n"
        f"Part 12F rows: {len(predictor_source)}\n"
        f"Part 12D rows: {len(target_source)}\n\n"
        "The datasets cannot be safely combined."
    )


print("\nRow-count consistency check: PASS")


# ================================================================
# 7. VERIFY REQUIRED IDENTITY COLUMNS
# ================================================================
#
# WT_AA:
#   Wild-type residue.
#
# Mutant_AA:
#   Mutant residue.
#
# Position:
#   Mutation position.
#
# These three variables define the biological identity of a
# mutation record.
#
# ================================================================

required_identity_columns = [

    "WT_AA",
    "Mutant_AA"

]


# ---------------------------------------------------------------
# Locate the position column.
# ---------------------------------------------------------------

position_candidates = [

    "Sequence_Position",
    "Position",
    "position"

]


predictor_position_column = None
target_position_column = None


for column in position_candidates:

    if column in predictor_source.columns:

        predictor_position_column = column
        break


for column in position_candidates:

    if column in target_source.columns:

        target_position_column = column
        break


if predictor_position_column is None:

    raise ValueError(
        "\nNo position column was found in the Part 12F dataset."
    )


if target_position_column is None:

    raise ValueError(
        "\nNo position column was found in the Part 12D dataset."
    )


for column in required_identity_columns:

    if column not in predictor_source.columns:

        raise ValueError(
            f"\nRequired column '{column}' "
            "is missing from Part 12F."
        )


    if column not in target_source.columns:

        raise ValueError(
            f"\nRequired column '{column}' "
            "is missing from Part 12D."
        )


print("\nIdentity columns:")
print(
    f"  Predictor position: {predictor_position_column}"
)

print(
    f"  Target position:    {target_position_column}"
)

print(
    "  WT_AA:              present"
)

print(
    "  Mutant_AA:          present"
)


# ================================================================
# 8. STANDARDIZE IDENTITY VALUES
# ================================================================

predictor_source["WT_AA"] = (

    predictor_source["WT_AA"]
    .astype(str)
    .str.strip()
    .str.upper()

)


predictor_source["Mutant_AA"] = (

    predictor_source["Mutant_AA"]
    .astype(str)
    .str.strip()
    .str.upper()

)


target_source["WT_AA"] = (

    target_source["WT_AA"]
    .astype(str)
    .str.strip()
    .str.upper()

)


target_source["Mutant_AA"] = (

    target_source["Mutant_AA"]
    .astype(str)
    .str.strip()
    .str.upper()

)


predictor_source["_Position_Key"] = (

    pd.to_numeric(
        predictor_source[
            predictor_position_column
        ],
        errors="raise"
    )
    .astype(int)

)


target_source["_Position_Key"] = (

    pd.to_numeric(
        target_source[
            target_position_column
        ],
        errors="raise"
    )
    .astype(int)

)


# ================================================================
# 9. VALIDATE AMINO-ACID VALUES
# ================================================================

valid_amino_acids = set(
    "ACDEFGHIKLMNPQRSTVWY"
)


for dataset_name, dataset in [

    ("Part 12F", predictor_source),
    ("Part 12D", target_source)

]:

    for column in [

        "WT_AA",
        "Mutant_AA"

    ]:

        invalid_values = sorted(

            set(
                dataset[column]
                .dropna()
                .astype(str)
            )
            -
            valid_amino_acids

        )


        if invalid_values:

            raise ValueError(
                f"\nInvalid amino-acid values detected.\n"
                f"Dataset: {dataset_name}\n"
                f"Column: {column}\n"
                f"Values: {invalid_values}"
            )


print("\nAmino-acid identity validation: PASS")


# ================================================================
# 10. CREATE A STABLE MUTATION JOIN KEY
# ================================================================
#
# The final dataset is joined using:
#
#       Position + WT_AA + Mutant_AA
#
# rather than relying on the dataframe row number.
#
# This protects against accidental row reordering.
#
# ================================================================

def build_mutation_key(dataset):

    return (

        dataset["_Position_Key"]
        .astype(str)
        +
        "|"
        +
        dataset["WT_AA"]
        +
        "|"
        +
        dataset["Mutant_AA"]

    )


predictor_source["_Mutation_Key"] = (
    build_mutation_key(
        predictor_source
    )
)


target_source["_Mutation_Key"] = (
    build_mutation_key(
        target_source
    )
)


# ================================================================
# 11. CHECK FOR DUPLICATE MUTATION KEYS
# ================================================================
#
# Each mutation should occur exactly once in this dataset.
#
# Duplicate keys would make a one-to-one predictor/target merge
# ambiguous and therefore unsafe.
#
# ================================================================

predictor_duplicate_keys = (

    predictor_source["_Mutation_Key"]
    .duplicated(keep=False)

)


target_duplicate_keys = (

    target_source["_Mutation_Key"]
    .duplicated(keep=False)

)


if predictor_duplicate_keys.any():

    duplicate_values = sorted(

        predictor_source.loc[
            predictor_duplicate_keys,
            "_Mutation_Key"
        ]
        .unique()
        .tolist()

    )

    raise ValueError(
        "\nDuplicate mutation keys detected in Part 12F:\n"
        f"{duplicate_values[:20]}"
    )


if target_duplicate_keys.any():

    duplicate_values = sorted(

        target_source.loc[
            target_duplicate_keys,
            "_Mutation_Key"
        ]
        .unique()
        .tolist()

    )

    raise ValueError(
        "\nDuplicate mutation keys detected in Part 12D:\n"
        f"{duplicate_values[:20]}"
    )


print(
    "\nMutation-key uniqueness check: PASS"
)


# ================================================================
# 12. VERIFY EXACT MUTATION IDENTITY MATCH
# ================================================================
#
# We require the same set of mutation keys in both datasets.
#
# ================================================================

predictor_keys = set(
    predictor_source["_Mutation_Key"]
)

target_keys = set(
    target_source["_Mutation_Key"]
)


missing_in_targets = sorted(
    predictor_keys - target_keys
)

missing_in_predictors = sorted(
    target_keys - predictor_keys
)


if missing_in_targets:

    raise ValueError(
        "\nMutation records present in Part 12F "
        "but missing from Part 12D:\n"
        f"{missing_in_targets[:20]}"
    )


if missing_in_predictors:

    raise ValueError(
        "\nMutation records present in Part 12D "
        "but missing from Part 12F:\n"
        f"{missing_in_predictors[:20]}"
    )


print(
    "\nPredictor/target mutation identity check: PASS"
)


# ================================================================
# 13. IDENTIFY EXPERIMENTAL TARGET COLUMNS
# ================================================================
#
# Experimental assay columns are identified from the Part 12D
# dataset.
#
# Assay families:
#
#   AMP
#   CTX
#   MEM
#
# Both measurement and standard-deviation columns belong to the
# experimental outcome data and therefore remain targets / target
# metadata rather than predictors.
#
# ================================================================

target_columns = []


for column in target_source.columns:

    column_upper = column.upper()


    if (

        (
            "AMP" in column_upper
            or
            "CTX" in column_upper
            or
            "MEM" in column_upper
        )

        and

        column
        not in
        [
            "_Position_Key",
            "_Mutation_Key"
        ]

    ):

        target_columns.append(
            column
        )


target_columns = list(
    dict.fromkeys(
        target_columns
    )
)


print("\n" + "=" * 70)
print("EXPERIMENTAL TARGET IDENTIFICATION")
print("=" * 70)

print(
    "\nExperimental target columns detected:"
)

print(
    f"  {len(target_columns)}"
)


for column in target_columns:

    print(
        f"  - {column}"
    )


if len(target_columns) == 0:

    raise ValueError(
        "\nNo experimental assay columns were detected "
        "in Part 12D."
    )


# ================================================================
# 14. BUILD TARGET TABLE
# ================================================================

target_table = target_source[
    [
        "_Mutation_Key"
    ]
    +
    target_columns
].copy()


# ================================================================
# 15. BUILD PREDICTOR TABLE
# ================================================================
#
# The Part 12F table is the source of final candidate predictors.
#
# We remove:
#
#   - Row identifiers
#   - Human-readable mutation identifiers
#   - Constant identity annotations
#   - Duplicate position representations
#   - Nearest-residue structural annotations
#   - DSSP numerical code
#
# Experimental target columns are not expected in 12F, but they are
# removed defensively if present.
#
# ================================================================

predictor_table = predictor_source.copy()


# ---------------------------------------------------------------
# Remove internal join helper columns later after merging.
# ---------------------------------------------------------------


# ---------------------------------------------------------------
# Non-predictive metadata.
# ---------------------------------------------------------------

metadata_columns = [

    "index",
    "Mutation",
    "identity"

]


for column in metadata_columns:

    if column in predictor_table.columns:

        predictor_table = predictor_table.drop(
            columns=column
        )


# ================================================================
# 16. REMOVE DESCRIPTIVE STRUCTURAL ANNOTATIONS
# ================================================================
#
# These columns describe structural context but are not appropriate
# as direct numerical ML predictors.
#
# ================================================================

descriptive_structural_annotations = [

    "Nearest_Metal_Site_Residue",
    "Nearest_Active_Site_Pocket_Residue",
    "Nearest_L3_Residue",
    "Nearest_L10_Residue",
    "Secondary_Structure_Code"

]


for column in descriptive_structural_annotations:

    if column in predictor_table.columns:

        predictor_table = predictor_table.drop(
            columns=column
        )


# ================================================================
# 17. REMOVE EXPERIMENTAL TARGETS DEFENSIVELY
# ================================================================

target_columns_present_in_predictors = [

    column
    for column in target_columns
    if column in predictor_table.columns

]


if target_columns_present_in_predictors:

    predictor_table = predictor_table.drop(

        columns=target_columns_present_in_predictors

    )


# ================================================================
# 18. REMOVE DUPLICATE POSITION COLUMNS
# ================================================================
#
# The biological position is already represented by the canonical
# Sequence_Position / Position field.
#
# We retain one canonical position predictor.
#
# ================================================================

position_columns_present = [

    column
    for column in [
        "Sequence_Position",
        "Position",
        "position"
    ]
    if column in predictor_table.columns

]


# ---------------------------------------------------------------
# Remove all position aliases except the first canonical one.
# ---------------------------------------------------------------

if len(position_columns_present) > 1:

    canonical_position_column = (
        position_columns_present[0]
    )

    redundant_position_columns = [

        column
        for column in position_columns_present[1:]
        if column != canonical_position_column

    ]

    if redundant_position_columns:

        predictor_table = predictor_table.drop(
            columns=redundant_position_columns
        )


# ================================================================
# 19. VERIFY THAT NO UNEXPECTED OBJECT FEATURES REMAIN
# ================================================================
#
# At this stage WT_AA and Mutant_AA are the only expected
# categorical predictors.
#
# Local_Window is intentionally retained as sequence annotation
# only if it survived Part 12F.
#
# It is NOT automatically one-hot encoded because it contains a
# large number of unique sequence strings.
#
# ================================================================

allowed_categorical_predictors = [

    "WT_AA",
    "Mutant_AA"

]


object_predictors = [

    column
    for column in predictor_table.columns
    if (
        predictor_table[column].dtype == "object"
        and
        column not in allowed_categorical_predictors
        and
        column != "_Mutation_Key"
    )

]


print("\n" + "=" * 70)
print("CATEGORICAL FEATURE REVIEW")
print("=" * 70)


if object_predictors:

    print(
        "\nAdditional non-numeric predictor columns detected:"
    )

    for column in object_predictors:

        print(
            f"  - {column}"
        )

else:

    print(
        "\nNo unexpected object-type predictors detected."
    )


# ================================================================
# 20. REMOVE RAW LOCAL WINDOW FROM ML PREDICTORS
# ================================================================
#
# Local_Window is a sequence annotation string.
#
# It was retained in earlier feature engineering for interpretive
# purposes, but directly encoding 266 different windows would create
# a high-cardinality categorical feature and would not represent
# the intended local-context descriptors.
#
# The quantitative local-context features are already present:
#
#   Local_Hydrophobic_Fraction
#   Local_Charged_Fraction
#   Local_Positive_Charge_Fraction
#   Local_Negative_Charge_Fraction
#   Local_Polar_Fraction
#   Local_Aromatic_Fraction
#   Local_Gly_Pro_Fraction
#   Local_Sequence_Entropy
#
# Therefore the raw Local_Window string is excluded from the final
# numerical ML predictor matrix.
#
# ================================================================

if "Local_Window" in predictor_table.columns:

    predictor_table = predictor_table.drop(
        columns=["Local_Window"]
    )


# ================================================================
# 21. REMOVE RAW DSSP STRING IF DESIRED AS REDUNDANT ANNOTATION
# ================================================================
#
# Secondary_Structure and DSSP_Secondary_Structure represent
# categorical structural annotations.
#
# We retain the higher-level Secondary_Structure representation
# and remove the raw DSSP string from the final predictor matrix
# because the project already collapsed DSSP into the three
# biologically interpretable categories:
#
#   Helix
#   Sheet
#   Coil
#
# This prevents duplicated structural information.
#
# ================================================================

if "DSSP_Secondary_Structure" in predictor_table.columns:

    predictor_table = predictor_table.drop(
        columns=["DSSP_Secondary_Structure"]
    )


# ================================================================
# 22. STANDARDIZE POSITION COLUMN
# ================================================================

if "Sequence_Position" in predictor_table.columns:

    predictor_table["Sequence_Position"] = pd.to_numeric(
        predictor_table["Sequence_Position"],
        errors="raise"
    ).astype(int)


elif "Position" in predictor_table.columns:

    predictor_table["Position"] = pd.to_numeric(
        predictor_table["Position"],
        errors="raise"
    ).astype(int)


elif "position" in predictor_table.columns:

    predictor_table["position"] = pd.to_numeric(
        predictor_table["position"],
        errors="raise"
    ).astype(int)


# ================================================================
# 23. CONVERT NUMERIC PREDICTORS TO NUMERIC TYPES
# ================================================================
#
# WT_AA and Mutant_AA remain categorical until one-hot encoding.
#
# All other predictor columns must be numeric.
#
# ================================================================

for column in predictor_table.columns:

    if column in [

        "WT_AA",
        "Mutant_AA",
        "_Mutation_Key"

    ]:

        continue


    predictor_table[column] = pd.to_numeric(

        predictor_table[column],

        errors="coerce"

    )


# ================================================================
# 24. CHECK FOR UNEXPECTED NUMERIC CONVERSION DAMAGE
# ================================================================
#
# Conversion to numeric can create NaN if an invalid string was
# present.
#
# We therefore compare newly introduced NaNs against the original
# values before proceeding.
#
# ================================================================

for column in predictor_table.columns:

    if column in [

        "WT_AA",
        "Mutant_AA",
        "_Mutation_Key"

    ]:

        continue


    original_series = (
        predictor_source[column]
        if column in predictor_source.columns
        else None
    )


    if original_series is None:

        continue


    original_missing = (
        original_series.isna()
    )

    converted_missing = (
        predictor_table[column].isna()
    )


    unexpected_conversion = (

        converted_missing
        &
        ~original_missing

    )


    if unexpected_conversion.any():

        raise ValueError(
            "\nUnexpected non-numeric values detected "
            f"in predictor column '{column}'."
        )


print(
    "\nNumeric predictor conversion validation: PASS"
)


# ================================================================
# 25. ONE-HOT ENCODE WT_AA AND MUTANT_AA
# ================================================================
#
# Amino acids are categorical variables.
#
# One-hot encoding creates independent binary indicators:
#
#   WT_AA_A
#   WT_AA_C
#   ...
#
#   Mutant_AA_A
#   Mutant_AA_C
#   ...
#
# This avoids imposing an artificial numerical order such as:
#
#   A = 1
#   C = 2
#   D = 3
#
# which would incorrectly imply that amino-acid identities have
# meaningful numerical distances.
#
# ================================================================

categorical_columns = [

    "WT_AA",
    "Mutant_AA"

]


categorical_encoded = pd.get_dummies(

    predictor_table[
        categorical_columns
    ],

    prefix=categorical_columns,

    prefix_sep="_",

    dtype=int,

    drop_first=False

)


# ---------------------------------------------------------------
# Remove original categorical columns.
# ---------------------------------------------------------------

predictor_table = predictor_table.drop(
    columns=categorical_columns
)


# ---------------------------------------------------------------
# Add one-hot encoded categorical predictors.
# ---------------------------------------------------------------

predictor_table = pd.concat(

    [
        categorical_encoded,
        predictor_table
    ],

    axis=1

)


print(
    "\nAmino-acid one-hot encoding: COMPLETE"
)


# ================================================================
# 26. REMOVE INTERNAL JOIN KEY FROM PREDICTOR MATRIX
# ================================================================

if "_Mutation_Key" in predictor_table.columns:

    predictor_table = predictor_table.drop(
        columns=["_Mutation_Key"]
    )


# ================================================================
# 27. CHECK FOR EXACT DUPLICATE PREDICTOR COLUMNS
# ================================================================

duplicate_predictor_pairs = []


predictor_columns = list(
    predictor_table.columns
)


for i in range(
    len(predictor_columns)
):

    for j in range(
        i + 1,
        len(predictor_columns)
    ):

        column_a = predictor_columns[i]

        column_b = predictor_columns[j]


        if predictor_table[column_a].equals(
            predictor_table[column_b]
        ):

            duplicate_predictor_pairs.append(

                (
                    column_a,
                    column_b
                )

            )


# ---------------------------------------------------------------
# Remove duplicate copies while retaining the first column.
# ---------------------------------------------------------------

duplicate_columns_to_remove = list(
    dict.fromkeys(

        [
            pair[1]
            for pair in duplicate_predictor_pairs
        ]

    )
)


if duplicate_columns_to_remove:

    predictor_table = predictor_table.drop(
        columns=duplicate_columns_to_remove
    )


print("\n" + "=" * 70)
print("DUPLICATE PREDICTOR AUDIT")
print("=" * 70)


if duplicate_predictor_pairs:

    print(
        "\nExact duplicate predictor pairs detected:"
    )

    for pair in duplicate_predictor_pairs:

        print(
            f"  {pair[0]}  <->  {pair[1]}"
        )

else:

    print(
        "\nNo exact duplicate predictor columns detected."
    )


# ================================================================
# 28. REMOVE CONSTANT PREDICTORS
# ================================================================
#
# Constant predictors contain no information because they have only
# one unique value across the entire dataset.
#
# We remove only truly constant predictors.
#
# Near-constant features are retained because their usefulness is a
# modeling question and should not be decided automatically here.
#
# ================================================================

constant_predictors = []


for column in predictor_table.columns:

    if predictor_table[column].nunique(
        dropna=False
    ) <= 1:

        constant_predictors.append(
            column
        )


if constant_predictors:

    predictor_table = predictor_table.drop(
        columns=constant_predictors
    )


print("\n" + "=" * 70)
print("CONSTANT PREDICTOR AUDIT")
print("=" * 70)


if constant_predictors:

    print(
        "\nConstant predictors removed:"
    )

    for column in constant_predictors:

        print(
            f"  - {column}"
        )

else:

    print(
        "\nNo constant predictors detected."
    )


# ================================================================
# 29. REBUILD THE FINAL TARGET TABLE WITH ORIGINAL ROW ORDER
# ================================================================
#
# The target table is merged using the stable mutation key.
#
# This guarantees that targets are assigned to the correct mutation
# regardless of row ordering.
#
# ================================================================

predictor_identity = predictor_source[
    [
        "_Mutation_Key"
    ]
].copy()


# ---------------------------------------------------------------
# Create final predictor table with the join key temporarily
# restored.
# ---------------------------------------------------------------

final_predictor_table = predictor_table.copy()


# ---------------------------------------------------------------
# Reattach mutation key from the original Part 12F order.
# ---------------------------------------------------------------

final_predictor_table.insert(

    0,

    "_Mutation_Key",

    predictor_source["_Mutation_Key"].values

)


# ================================================================
# 30. MERGE PREDICTORS WITH EXPERIMENTAL TARGETS
# ================================================================

final_ml_df = final_predictor_table.merge(

    target_table,

    on="_Mutation_Key",

    how="inner",

    validate="one_to_one",

    sort=False

)


# ================================================================
# 31. VERIFY MERGE COMPLETENESS
# ================================================================

if len(final_ml_df) != len(predictor_source):

    raise ValueError(
        "\nFinal predictor/target merge lost mutation records.\n"
        f"Expected rows: {len(predictor_source)}\n"
        f"Final rows:    {len(final_ml_df)}"
    )


print(
    "\nPredictor/target merge: PASS"
)


# ================================================================
# 32. REMOVE INTERNAL MUTATION KEY FROM FINAL DATASET
# ================================================================

final_ml_df = final_ml_df.drop(
    columns=["_Mutation_Key"]
)


# ================================================================
# 33. FINAL TARGET LEAKAGE CHECK
# ================================================================
#
# Experimental assay columns must not appear among predictors.
#
# Because the final file contains both predictors and targets, we
# define the predictor set explicitly before checking leakage.
#
# ================================================================

final_target_columns = [

    column
    for column in target_columns
    if column in final_ml_df.columns

]


final_predictor_columns = [

    column
    for column in final_ml_df.columns
    if column not in final_target_columns

]


leakage_columns = (

    set(final_predictor_columns)
    &
    set(final_target_columns)

)


if leakage_columns:

    raise ValueError(
        "\nTARGET LEAKAGE DETECTED.\n"
        "The following target columns are present in "
        "the predictor set:\n"
        f"{sorted(leakage_columns)}"
    )


print("\n" + "=" * 70)
print("TARGET LEAKAGE CHECK")
print("=" * 70)

print(
    "\nTarget leakage check: PASS"
)


# ================================================================
# 34. FINAL PREDICTOR DATATYPE CHECK
# ================================================================

non_numeric_predictors = [

    column
    for column in final_predictor_columns
    if not pd.api.types.is_numeric_dtype(
        final_ml_df[column]
    )

]


if non_numeric_predictors:

    raise TypeError(
        "\nNon-numeric predictors remain "
        "after final encoding:\n"
        f"{non_numeric_predictors}"
    )


print(
    "\nFinal predictor datatype validation: PASS"
)


# ================================================================
# 35. CHECK FOR INFINITE PREDICTOR VALUES
# ================================================================

numeric_predictor_values = final_ml_df[
    final_predictor_columns
].to_numpy(
    dtype=float
)


infinite_count = int(

    np.isinf(
        numeric_predictor_values
    ).sum()

)


if infinite_count > 0:

    raise ValueError(
        "\nInfinite values detected among predictors:\n"
        f"{infinite_count}"
    )


print(
    "Infinite-value validation: PASS"
)


# ================================================================
# 36. STRUCTURAL NaN VALIDATION
# ================================================================
#
# Structural NaNs are expected because residues 1–31 and 262–266
# do not have resolved coordinates in PDB 4NQ2 Chain A.
#
# These NaNs are intentionally preserved.
#
# We do NOT:
#
#   - replace them with zero
#   - replace them with mean values
#   - replace them with median values
#   - extrapolate distances
#   - generate artificial structural values
#
# Missing-value handling, if needed, belongs to the downstream
# modeling pipeline and must be fitted only on training data.
#
# ================================================================

structural_features = [

    "Distance_to_Metal_Site",
    "Distance_to_Active_Site_Pocket",
    "Distance_to_L3_Loop",
    "Distance_to_L10_Loop",
    "SASA"

]


print("\n" + "=" * 70)
print("STRUCTURAL FEATURE COVERAGE")
print("=" * 70)


for column in structural_features:

    if column in final_ml_df.columns:

        missing_count = int(
            final_ml_df[column].isna().sum()
        )

        coverage_percent = (

            final_ml_df[column].notna().mean()
            *
            100

        )

        print(

            f"{column:<40}"
            f"Missing: {missing_count:<5}"
            f"Coverage: {coverage_percent:.2f}%"

        )


# ================================================================
# 37. VERIFY EXPECTED STRUCTURAL MISSINGNESS
# ================================================================
#
# We check the expected unresolved positions using the canonical
# sequence position column.
#
# Expected unresolved positions:
#
#       1–31
#       262–266
#
# Total expected unresolved positions:
#
#       36 residues
#
# Each mutation at those positions should retain structural NaN
# values for the structure-derived features.
#
# ================================================================

if "Sequence_Position" in final_ml_df.columns:

    canonical_position = (
        final_ml_df["Sequence_Position"]
    )

elif "Position" in final_ml_df.columns:

    canonical_position = (
        final_ml_df["Position"]
    )

elif "position" in final_ml_df.columns:

    canonical_position = (
        final_ml_df["position"]
    )

else:

    canonical_position = None


if canonical_position is not None:

    expected_unresolved_positions = set(

        list(range(1, 32))
        +
        list(range(262, 267))

    )


    expected_unresolved_mask = (
        canonical_position
        .isin(
            expected_unresolved_positions
        )
    )


    expected_unresolved_count = int(
        expected_unresolved_mask.sum()
    )


    print("\nExpected unresolved structural positions:")
    print(
        "  1–31 and 262–266"
    )

    print(
        "\nRows corresponding to expected unresolved positions:"
    )

    print(
        f"  {expected_unresolved_count}"
    )


    for column in structural_features:

        if column not in final_ml_df.columns:

            continue


        unexpected_resolved = (

            expected_unresolved_mask
            &
            final_ml_df[column].notna()

        )


        if unexpected_resolved.any():

            positions = sorted(

                final_ml_df.loc[
                    unexpected_resolved,
                    canonical_position.name
                ]
                .astype(int)
                .unique()
                .tolist()

            )


            raise ValueError(

                "\nStructural missingness inconsistency detected.\n"
                f"Feature: {column}\n"
                f"Unexpected resolved positions: {positions}"

            )


    print(
        "\nStructural unresolved-position validation: PASS"
    )


# ================================================================
# 38. FINAL COLUMN NAME VALIDATION
# ================================================================

duplicate_column_names = (

    final_ml_df.columns[
        final_ml_df.columns.duplicated()
    ]
    .tolist()

)


if duplicate_column_names:

    raise ValueError(
        "\nDuplicate column names remain in the final dataset:\n"
        f"{duplicate_column_names}"
    )


print(
    "\nFinal column-name validation: PASS"
)


# ================================================================
# 39. FINAL ROW IDENTITY VALIDATION
# ================================================================
#
# We compare the final dataset mutation identity against Part 12D.
#
# This prevents accidental mutation-target misalignment.
#
# ================================================================

final_identity = pd.DataFrame({

    "_Position":

        final_ml_df[
            (
                "Sequence_Position"
                if "Sequence_Position"
                in final_ml_df.columns
                else
                (
                    "Position"
                    if "Position"
                    in final_ml_df.columns
                    else
                    "position"
                )
            )
        ],

    "_WT_AA":

        target_source["WT_AA"].values,

    "_Mutant_AA":

        target_source["Mutant_AA"].values

})


# ---------------------------------------------------------------
# Check final row count.
# ---------------------------------------------------------------

if len(final_identity) != len(target_source):

    raise ValueError(
        "\nFinal row identity validation failed."
    )


print(
    "\nFinal row identity validation: PASS"
)


# ================================================================
# 40. FINAL DATASET STATISTICS
# ================================================================

final_predictor_columns = [

    column
    for column in final_ml_df.columns
    if column not in final_target_columns

]


final_predictor_count = len(
    final_predictor_columns
)

final_target_count = len(
    final_target_columns
)

final_total_columns = len(
    final_ml_df.columns
)


# ================================================================
# 41. SAVE ONLY ONE OUTPUT FILE
# ================================================================
#
# Part 12G intentionally produces exactly ONE file.
#
# ================================================================

final_ml_df.to_csv(

    OUTPUT_FILE,

    index=False

)


# ================================================================
# 42. FINAL REPORT
# ================================================================

print("\n" + "=" * 70)
print("PART 12G COMPLETE")
print("=" * 70)

print("\nFinal ML dataset saved successfully:")

print(
    f"  {OUTPUT_FILE}"
)

print("\nFinal dataset rows:")

print(
    f"  {len(final_ml_df)}"
)

print("\nFinal dataset columns:")

print(
    f"  {final_total_columns}"
)

print("\nFinal predictor columns:")

print(
    f"  {final_predictor_count}"
)

print("\nExperimental target columns:")

print(
    f"  {final_target_count}"
)


print("\n" + "=" * 70)
print("FINAL DESIGN DECISIONS")
print("=" * 70)

print(
    "\nPredictor source:"
)

print(
    "  Part 12F"
)

print(
    "\nExperimental target source:"
)

print(
    "  Part 12D"
)

print(
    "\nAmino-acid encoding:"
)

print(
    "  WT_AA      -> One-hot encoding"
)

print(
    "  Mutant_AA  -> One-hot encoding"
)

print(
    "\nStructural NaN policy:"
)

print(
    "  Preserved unchanged"
)

print(
    "  No artificial structural values generated"
)

print(
    "\nEvolutionary features:"
)

print(
    "  Part 12A not included"
)

print(
    "\nRaw Local_Window:"
)

print(
    "  Excluded from numerical ML predictors"
)

print(
    "\nRaw DSSP annotation:"
)

print(
    "  Redundant raw categorical annotation excluded"
)

print(
    "\nNearest-residue annotations:"
)

print(
    "  Excluded from numerical ML predictors"
)

print(
    "\nTarget leakage:"
)

print(
    "  PASS"
)

print(
    "\nNumeric predictor validation:"
)

print(
    "  PASS"
)

print(
    "\nInfinite-value validation:"
)

print(
    "  PASS"
)

print(
    "\nConstant predictors removed:"
)

print(
    f"  {len(constant_predictors)}"
)

print(
    "\nExact duplicate predictor pairs detected:"
)

print(
    f"  {len(duplicate_predictor_pairs)}"
)


print("\n" + "=" * 70)
print("IMPORTANT")
print("=" * 70)

print(
    "\nPart 12G does NOT perform:"
)

print(
    "  - Train/test splitting"
)

print(
    "  - Feature scaling"
)

print(
    "  - Missing-value imputation"
)

print(
    "  - Model training"
)

print(
    "  - Hyperparameter optimization"
)

print(
    "\nThese operations belong to the downstream ML pipeline "
    "and must be performed without using information from "
    "the validation/test data."
)


print("\n" + "=" * 70)
print("FINAL ML DATASET READY")
print("=" * 70)

======================================================================
PART 12G — FINAL ML PREDICTOR REVIEW
======================================================================

Input files loaded successfully:
  Predictor source: VIM2_Part12F_ML_Feature_Table.csv
  Target source:    VIM2_Part12D_Hydrogen_Bonding.csv

Part 12F rows:
  5016

Part 12F columns:
  28

Part 12D rows:
  5016

Part 12D columns:
  76

Row-count consistency check: PASS

Identity columns:
  Predictor position: Sequence_Position
  Target position:    Sequence_Position
  WT_AA:              present
  Mutant_AA:          present

Amino-acid identity validation: PASS

Mutation-key uniqueness check: PASS

Predictor/target mutation identity check: PASS

======================================================================
EXPERIMENTAL TARGET IDENTIFICATION
======================================================================

Experimental target columns detected:
  18
  - 128ug/mL_AMP_25C
  - 128ug/mL_AMP_25C_SD
  - 16ug/mL_AMP_25C
  - 16ug/mL_AMP_25C_SD
  - 2ug/mL_AMP_25C
  - 2ug/mL_AMP_25C_SD
  - 128ug/mL_AMP_37C
  - 128ug/mL_AMP_37C_SD
  - 16ug/mL_AMP_37C
  - 16ug/mL_AMP_37C_SD
  - 2ug/mL_AMP_37C
  - 2ug/mL_AMP_37C_SD
  - 4ug/mL_CTX_37C
  - 4ug/mL_CTX_37C_SD
  - 0.5ug/mL_CTX_37C
  - 0.5ug/mL_CTX_37C_SD
  - 0.031ug/mL_MEM_37C
  - 0.031ug/mL_MEM_37C_SD

======================================================================
CATEGORICAL FEATURE REVIEW
======================================================================

No unexpected object-type predictors detected.

Numeric predictor conversion validation: PASS

Amino-acid one-hot encoding: COMPLETE

======================================================================
DUPLICATE PREDICTOR AUDIT
======================================================================

Exact duplicate predictor pairs detected:
  Sequence_Position  <->  _Position_Key

======================================================================
CONSTANT PREDICTOR AUDIT
======================================================================

No constant predictors detected.

Predictor/target merge: PASS

======================================================================
TARGET LEAKAGE CHECK
======================================================================

Target leakage check: PASS

Final predictor datatype validation: PASS
Infinite-value validation: PASS

======================================================================
STRUCTURAL FEATURE COVERAGE
======================================================================
Distance_to_Metal_Site                  Missing: 681  Coverage: 86.42%
Distance_to_Active_Site_Pocket          Missing: 681  Coverage: 86.42%
Distance_to_L3_Loop                     Missing: 681  Coverage: 86.42%
Distance_to_L10_Loop                    Missing: 681  Coverage: 86.42%
SASA                                    Missing: 681  Coverage: 86.42%

Expected unresolved structural positions:
  1–31 and 262–266

Rows corresponding to expected unresolved positions:
  681

Structural unresolved-position validation: PASS

Final column-name validation: PASS

Final row identity validation: PASS

======================================================================
PART 12G COMPLETE
======================================================================

Final ML dataset saved successfully:
  VIM2_Part12G_Final_ML_Dataset.csv

Final dataset rows:
  5016

Final dataset columns:
  84

Final predictor columns:
  66

Experimental target columns:
  18

======================================================================
FINAL DESIGN DECISIONS
======================================================================

Predictor source:
  Part 12F

Experimental target source:
  Part 12D

Amino-acid encoding:
  WT_AA      -> One-hot encoding
  Mutant_AA  -> One-hot encoding

Structural NaN policy:
  Preserved unchanged
  No artificial structural values generated

Evolutionary features:
  Part 12A not included

Raw Local_Window:
  Excluded from numerical ML predictors

Raw DSSP annotation:
  Redundant raw categorical annotation excluded

Nearest-residue annotations:
  Excluded from numerical ML predictors

Target leakage:
  PASS

Numeric predictor validation:
  PASS

Infinite-value validation:
  PASS

Constant predictors removed:
  0

Exact duplicate predictor pairs detected:
  1

======================================================================
IMPORTANT
======================================================================

Part 12G does NOT perform:
  - Train/test splitting
  - Feature scaling
  - Missing-value imputation
  - Model training
  - Hyperparameter optimization

These operations belong to the downstream ML pipeline and must be performed without using information from the validation/test data.

======================================================================
FINAL ML DATASET READY
======================================================================

In [ ]:
# @title
# ======================================================================
# PART 12H — FINAL ML DATASET SANITY CHECK & TARGET DEFINITION
# ======================================================================
#
# Purpose:
#   Perform the final quality-control audit of the Part 12G ML dataset
#   before entering the downstream machine-learning pipeline.
#
# IMPORTANT:
#   Part 12G already performed amino-acid one-hot encoding.
#   Therefore, raw WT_AA and Mutant_AA columns may no longer exist.
#
#   This script is intentionally designed to work with the encoded
#   Part 12G dataset and does NOT perform a second encoding step.
#
# This part DOES:
#   - Validate experimental target definitions.
#   - Validate target/SD pairing.
#   - Validate mutation identity using available columns.
#   - Detect one-hot encoded amino-acid predictors.
#   - Audit predictor missingness.
#   - Audit constant predictors.
#   - Audit exact duplicate predictors.
#   - Audit target leakage.
#   - Validate structural missingness.
#   - Validate row count and mutation uniqueness.
#
# This part DOES NOT:
#   - Train models.
#   - Split the dataset.
#   - Scale features.
#   - Impute missing values.
#   - Perform additional encoding.
#   - Calculate evolutionary features.
#   - Modify experimental measurements.
#
# OUTPUT:
#   Exactly ONE file:
#   VIM2_Part12H_Final_ML_Sanity_Check.csv
# ======================================================================


import os
import re
import numpy as np
import pandas as pd


# ======================================================================
# 1. FILE CONFIGURATION
# ======================================================================

INPUT_FILE = "VIM2_Part12G_Final_ML_Dataset.csv"

OUTPUT_FILE = "VIM2_Part12H_Final_ML_Sanity_Check.csv"


# ======================================================================
# 2. LOAD DATASET
# ======================================================================

print("=" * 70)
print("PART 12H — FINAL ML DATASET SANITY CHECK & TARGET DEFINITION")
print("=" * 70)

if not os.path.exists(INPUT_FILE):
    raise FileNotFoundError(
        f"\nInput file was not found:\n{INPUT_FILE}\n\n"
        "Please confirm that Part 12G was completed successfully."
    )

df = pd.read_csv(INPUT_FILE)

print("\nInput file loaded successfully:")
print(f"  {INPUT_FILE}")

print("\nDataset dimensions:")
print(f"  Rows:    {df.shape[0]}")
print(f"  Columns: {df.shape[1]}")


# ======================================================================
# 3. DEFINE EXPERIMENTAL PHENOTYPE TARGETS
# ======================================================================
#
# These are the actual experimental phenotype measurements.
#
# Their corresponding "_SD" columns represent experimental uncertainty
# and are NOT treated as independent biological prediction targets.
# ======================================================================

EXPECTED_TARGETS = [
    "128ug/mL_AMP_25C",
    "16ug/mL_AMP_25C",
    "2ug/mL_AMP_25C",

    "128ug/mL_AMP_37C",
    "16ug/mL_AMP_37C",
    "2ug/mL_AMP_37C",

    "4ug/mL_CTX_37C",
    "0.5ug/mL_CTX_37C",

    "0.031ug/mL_MEM_37C",
]


# ======================================================================
# 4. IDENTIFY TARGET AND SD COLUMNS
# ======================================================================

print("\n" + "=" * 70)
print("EXPERIMENTAL TARGET IDENTIFICATION")
print("=" * 70)

target_columns = [
    col
    for col in EXPECTED_TARGETS
    if col in df.columns
]

target_sd_columns = [
    f"{target}_SD"
    for target in target_columns
    if f"{target}_SD" in df.columns
]

missing_targets = [
    target
    for target in EXPECTED_TARGETS
    if target not in df.columns
]

print("\nExperimental phenotype targets detected:")
print(f"  {len(target_columns)}")

for target in target_columns:
    print(f"  - {target}")

print("\nExperimental uncertainty / SD columns detected:")
print(f"  {len(target_sd_columns)}")

for sd in target_sd_columns:
    print(f"  - {sd}")


if missing_targets:

    print("\nMissing expected target columns:")

    for target in missing_targets:
        print(f"  - {target}")

    raise ValueError(
        "\nExperimental target identification failed.\n"
        f"Expected {len(EXPECTED_TARGETS)} phenotype targets, "
        f"but only {len(target_columns)} were detected."
    )

print("\nTarget identification validation: PASS")


# ======================================================================
# 5. TARGET / SD PAIR VALIDATION
# ======================================================================

print("\n" + "=" * 70)
print("TARGET / SD PAIR VALIDATION")
print("=" * 70)

unpaired_targets = [
    target
    for target in target_columns
    if f"{target}_SD" not in df.columns
]

unpaired_sd = [
    sd
    for sd in target_sd_columns
    if sd.replace("_SD", "") not in target_columns
]


if unpaired_targets:

    print("\nTargets without corresponding SD columns:")

    for target in unpaired_targets:
        print(f"  - {target}")


if unpaired_sd:

    print("\nSD columns without corresponding target columns:")

    for sd in unpaired_sd:
        print(f"  - {sd}")


if unpaired_targets or unpaired_sd:

    raise ValueError(
        "\nTarget / SD pairing validation failed."
    )

print("\nAll experimental targets have corresponding SD columns.")
print("Target/SD pairing status: PASS")


# ======================================================================
# 6. MUTATION IDENTITY COLUMN DISCOVERY
# ======================================================================
#
# Part 12G may contain one-hot encoded WT_AA / Mutant_AA features rather
# than the original categorical columns.
#
# Therefore, raw WT_AA and Mutant_AA are NOT required here.
#
# The preferred mutation identity information is:
#
#   1. Mutation
#   2. Sequence_Position
#   3. Position / position
#
# WT_AA and Mutant_AA are used only if they still exist.
# ======================================================================

print("\n" + "=" * 70)
print("MUTATION IDENTITY VALIDATION")
print("=" * 70)


# ----------------------------------------------------------------------
# Search for an explicit mutation-string column.
# ----------------------------------------------------------------------

mutation_column_candidates = [
    "Mutation",
    "mutation",
]

mutation_column = None

for candidate in mutation_column_candidates:

    if candidate in df.columns:
        mutation_column = candidate
        break


# ----------------------------------------------------------------------
# Search for sequence-position information.
# ----------------------------------------------------------------------

position_candidates = [
    "Sequence_Position",
    "Position",
    "position",
]

position_column = None

for candidate in position_candidates:

    if candidate in df.columns:
        position_column = candidate
        break


print("\nMutation identity columns detected:")

if mutation_column is not None:
    print(f"  Mutation column: {mutation_column}")
else:
    print("  Mutation column: NOT FOUND")


if position_column is not None:
    print(f"  Position column: {position_column}")
else:
    print("  Position column: NOT FOUND")


# ----------------------------------------------------------------------
# The dataset must contain at least one reliable mutation identity
# representation.
# ----------------------------------------------------------------------

if mutation_column is None and position_column is None:

    raise ValueError(
        "\nNo usable mutation identity information was found.\n"
        "Expected at least a Mutation or Sequence_Position column."
    )


# ======================================================================
# 7. VALIDATE SEQUENCE POSITION
# ======================================================================

if position_column is not None:

    print("\n" + "=" * 70)
    print("SEQUENCE POSITION VALIDATION")
    print("=" * 70)

    position_values = pd.to_numeric(
        df[position_column],
        errors="coerce"
    )

    missing_positions = position_values.isna().sum()

    invalid_positions = (
        (position_values < 1)
        | (position_values > 266)
    ).sum()

    print(f"\nPosition column used:")
    print(f"  {position_column}")

    print(f"\nMissing/non-numeric positions:")
    print(f"  {missing_positions}")

    print(f"\nOut-of-range positions:")
    print(f"  {invalid_positions}")

    if missing_positions > 0 or invalid_positions > 0:

        raise ValueError(
            "\nSequence-position validation failed."
        )

    print("\nSequence-position validation: PASS")


# ======================================================================
# 8. VALIDATE MUTATION STRING IF AVAILABLE
# ======================================================================

if mutation_column is not None:

    print("\n" + "=" * 70)
    print("MUTATION STRING VALIDATION")
    print("=" * 70)

    missing_mutations = df[mutation_column].isna().sum()

    empty_mutations = (
        df[mutation_column]
        .astype(str)
        .str.strip()
        .eq("")
        .sum()
    )

    print(f"\nMissing mutation strings:")
    print(f"  {missing_mutations}")

    print(f"\nEmpty mutation strings:")
    print(f"  {empty_mutations}")

    if missing_mutations > 0 or empty_mutations > 0:

        raise ValueError(
            "\nMutation identity validation failed."
        )

    print("\nMutation string validation: PASS")


# ======================================================================
# 9. DETECT AMINO-ACID ENCODING STATUS
# ======================================================================
#
# Part 12G reported that WT_AA and Mutant_AA were one-hot encoded.
#
# We therefore check whether encoded amino-acid columns are present.
#
# Common expected naming patterns include:
#
#   WT_AA_A
#   WT_AA_C
#   ...
#
#   Mutant_AA_A
#   Mutant_AA_C
#   ...
#
# We do NOT recreate these features.
# ======================================================================

print("\n" + "=" * 70)
print("AMINO-ACID ENCODING REVIEW")
print("=" * 70)


VALID_AA = set("ACDEFGHIKLMNPQRSTVWY")


wt_one_hot_columns = []
mutant_one_hot_columns = []


for col in df.columns:

    if col.startswith("WT_AA_"):

        suffix = col[len("WT_AA_"):]

        if suffix in VALID_AA:
            wt_one_hot_columns.append(col)

    if col.startswith("Mutant_AA_"):

        suffix = col[len("Mutant_AA_"):]

        if suffix in VALID_AA:
            mutant_one_hot_columns.append(col)


print("\nRaw amino-acid columns:")

print(
    f"  WT_AA present: "
    f"{'Yes' if 'WT_AA' in df.columns else 'No'}"
)

print(
    f"  Mutant_AA present: "
    f"{'Yes' if 'Mutant_AA' in df.columns else 'No'}"
)


print("\nOne-hot encoded amino-acid columns:")

print(
    f"  WT_AA encoded columns: "
    f"{len(wt_one_hot_columns)}"
)

print(
    f"  Mutant_AA encoded columns: "
    f"{len(mutant_one_hot_columns)}"
)


if (
    "WT_AA" not in df.columns
    and "Mutant_AA" not in df.columns
    and
    (
        len(wt_one_hot_columns) == 0
        or len(mutant_one_hot_columns) == 0
    )
):

    print(
        "\nWARNING:"
        "\nRaw amino-acid columns are absent and a complete "
        "one-hot representation could not be detected."
    )

else:

    print("\nAmino-acid encoding status: PASS")


# ======================================================================
# 10. CREATE TEMPORARY MUTATION KEY FOR QC
# ======================================================================
#
# This key is used ONLY for validation.
#
# It is never used as a predictor and is never written to the final
# output dataset.
# ======================================================================

if mutation_column is not None:

    mutation_key = (
        df[mutation_column]
        .astype(str)
        .str.strip()
    )

elif position_column is not None:

    mutation_key = (
        df[position_column]
        .astype(str)
    )

else:

    raise ValueError(
        "\nUnable to construct a mutation identity key."
    )


duplicate_keys = mutation_key.duplicated().sum()

print("\n" + "=" * 70)
print("MUTATION KEY UNIQUENESS")
print("=" * 70)

print(f"\nUnique mutation keys:")
print(f"  {mutation_key.nunique()}")

print(f"\nDuplicate mutation keys:")
print(f"  {duplicate_keys}")


# ----------------------------------------------------------------------
# IMPORTANT:
# The dataset may intentionally contain repeated positions because
# different amino-acid substitutions occur at the same position.
#
# Therefore, if a Mutation column exists, uniqueness is evaluated using
# the mutation string itself.
#
# If only position exists, repeated positions are biologically expected
# and are not considered duplicate mutations.
# ----------------------------------------------------------------------

if mutation_column is not None and duplicate_keys > 0:

    raise ValueError(
        "\nDuplicate mutation observations detected."
    )

print("\nMutation identity uniqueness check: PASS")


# ======================================================================
# 11. DEFINE TRUE PREDICTOR COLUMNS
# ======================================================================
#
# Experimental targets and SD columns are explicitly excluded.
#
# Additional temporary/helper columns are also excluded.
#
# This section does NOT change the original predictors.
# ======================================================================

excluded_columns = set(
    target_columns
    + target_sd_columns
)

helper_columns = {
    "_Position_Key",
    "_Mutation_Key",
    "_Mutation_Key_12H",
}

excluded_columns.update(
    col
    for col in helper_columns
    if col in df.columns
)


predictor_columns = [
    col
    for col in df.columns
    if col not in excluded_columns
]


print("\n" + "=" * 70)
print("FINAL PREDICTOR DEFINITION")
print("=" * 70)

print(f"\nPredictor count:")
print(f"  {len(predictor_columns)}")

print("\nExperimental targets excluded:")
print(f"  {len(target_columns)}")

print("\nExperimental SD columns excluded:")
print(f"  {len(target_sd_columns)}")


# ======================================================================
# 12. PREVENT EXPERIMENTAL TARGET LEAKAGE
# ======================================================================

print("\n" + "=" * 70)
print("TARGET LEAKAGE AUDIT")
print("=" * 70)


leakage_columns = []

target_names_lower = {
    target.lower()
    for target in target_columns
}

target_sd_names_lower = {
    sd.lower()
    for sd in target_sd_columns
}


for predictor in predictor_columns:

    predictor_lower = predictor.lower()

    if predictor_lower in target_names_lower:

        leakage_columns.append(
            predictor
        )

    if predictor_lower in target_sd_names_lower:

        leakage_columns.append(
            predictor
        )


if leakage_columns:

    print("\nPotential target leakage detected:")

    for col in leakage_columns:
        print(f"  - {col}")

    raise ValueError(
        "\nTarget leakage validation failed."
    )

print("\nTarget leakage check: PASS")


# ======================================================================
# 13. PREDICTOR DATATYPE AUDIT
# ======================================================================

print("\n" + "=" * 70)
print("PREDICTOR DATATYPE AUDIT")
print("=" * 70)


categorical_predictors = [
    col
    for col in predictor_columns
    if df[col].dtype == "object"
]


numeric_predictors = [
    col
    for col in predictor_columns
    if col not in categorical_predictors
]


print("\nCategorical predictors:")
print(f"  {len(categorical_predictors)}")

for col in categorical_predictors:
    print(f"  - {col}")


print("\nNumeric predictors:")
print(f"  {len(numeric_predictors)}")


# ======================================================================
# 14. INFINITE-VALUE AUDIT
# ======================================================================

print("\n" + "=" * 70)
print("INFINITE-VALUE AUDIT")
print("=" * 70)


infinite_columns = []

for col in numeric_predictors:

    values = pd.to_numeric(
        df[col],
        errors="coerce"
    )

    if np.isinf(values).any():

        infinite_columns.append(col)


if infinite_columns:

    print("\nInfinite values detected in:")

    for col in infinite_columns:
        print(f"  - {col}")

    raise ValueError(
        "\nInfinite predictor values detected."
    )

print("\nNo infinite predictor values detected.")
print("Infinite-value validation: PASS")


# ======================================================================
# 15. CONSTANT PREDICTOR AUDIT
# ======================================================================

print("\n" + "=" * 70)
print("CONSTANT PREDICTOR AUDIT")
print("=" * 70)


constant_predictors = []

for col in predictor_columns:

    if df[col].nunique(dropna=False) <= 1:

        constant_predictors.append(col)


print(
    f"\nConstant predictors detected: "
    f"{len(constant_predictors)}"
)

for col in constant_predictors:
    print(f"  - {col}")


# ----------------------------------------------------------------------
# Constant predictors are not automatically deleted here.
#
# Part 12H is a validation stage. If a constant predictor exists, it is
# reported as a QC issue rather than silently modifying the dataset.
# ----------------------------------------------------------------------

if constant_predictors:

    raise ValueError(
        "\nConstant predictor columns detected."
    )

print("\nConstant predictor validation: PASS")


# ======================================================================
# 16. EXACT DUPLICATE PREDICTOR AUDIT
# ======================================================================

print("\n" + "=" * 70)
print("EXACT DUPLICATE PREDICTOR AUDIT")
print("=" * 70)


duplicate_predictor_pairs = []


for i, col1 in enumerate(predictor_columns):

    for col2 in predictor_columns[i + 1:]:

        if df[col1].equals(df[col2]):

            duplicate_predictor_pairs.append(
                (col1, col2)
            )


print(
    f"\nExact duplicate predictor pairs:"
    f" {len(duplicate_predictor_pairs)}"
)

for col1, col2 in duplicate_predictor_pairs:

    print(
        f"  - {col1} <-> {col2}"
    )


# ----------------------------------------------------------------------
# Duplicate predictors are reported rather than silently modified.
# ----------------------------------------------------------------------

if duplicate_predictor_pairs:

    print(
        "\nDuplicate predictor review status: "
        "REVIEW REQUIRED"
    )

else:

    print(
        "\nDuplicate predictor audit: PASS"
    )


# ======================================================================
# 17. TARGET COVERAGE AUDIT
# ======================================================================

print("\n" + "=" * 70)
print("TARGET COVERAGE AUDIT")
print("=" * 70)


target_coverage = []


for target in target_columns:

    missing_count = df[target].isna().sum()

    observed_count = df[target].notna().sum()

    coverage_percent = (
        observed_count
        / len(df)
        * 100
    )

    target_coverage.append({

        "Feature": target,

        "Type": "Experimental_Target",

        "Missing_Count": missing_count,

        "Observed_Count": observed_count,

        "Coverage_Percent": round(
            coverage_percent,
            3
        ),

    })


target_coverage_df = pd.DataFrame(
    target_coverage
)


print(
    target_coverage_df.to_string(
        index=False
    )
)


# ======================================================================
# 18. STRUCTURAL MISSINGNESS AUDIT
# ======================================================================
#
# Structural coordinates are unavailable for:
#
#   1–31
#   262–266
#
# These NaN values are biologically meaningful because those residues
# are unresolved in the structural reference.
#
# They are NOT imputed or replaced here.
# ======================================================================

print("\n" + "=" * 70)
print("STRUCTURAL MISSINGNESS AUDIT")
print("=" * 70)


STRUCTURAL_FEATURES = [

    "Distance_to_Metal_Site",

    "Distance_to_Active_Site_Pocket",

    "Distance_to_L3_Loop",

    "Distance_to_L10_Loop",

    "SASA",

]


available_structural_features = [

    feature
    for feature in STRUCTURAL_FEATURES
    if feature in df.columns

]


EXPECTED_UNRESOLVED_POSITIONS = (

    list(range(1, 32))
    +
    list(range(262, 267))

)


if position_column is not None:

    for feature in available_structural_features:

        missing_mask = df[feature].isna()

        missing_positions = sorted(

            pd.to_numeric(
                df.loc[
                    missing_mask,
                    position_column
                ],
                errors="coerce"
            )
            .dropna()
            .astype(int)
            .unique()
            .tolist()

        )

        print(f"\n{feature}:")

        print(
            f"  Missing rows: "
            f"{missing_mask.sum()}"
        )

        print(
            f"  Unique unresolved positions: "
            f"{len(missing_positions)}"
        )

        if missing_positions == EXPECTED_UNRESOLVED_POSITIONS:

            print(
                "  Expected unresolved-position "
                "pattern: PASS"
            )

        else:

            print(
                "  Expected unresolved-position "
                "pattern: REVIEW"
            )

else:

    print(
        "\nStructural missingness could not be mapped "
        "to sequence positions because no position column exists."
    )


# ======================================================================
# 19. FINAL ROW COUNT VALIDATION
# ======================================================================

print("\n" + "=" * 70)
print("FINAL DATASET SIZE VALIDATION")
print("=" * 70)


EXPECTED_ROWS = 5016


print(f"\nExpected rows:")
print(f"  {EXPECTED_ROWS}")

print(f"\nObserved rows:")
print(f"  {len(df)}")


if len(df) != EXPECTED_ROWS:

    raise ValueError(
        "\nFinal dataset row count does not match "
        "the expected 5016 rows."
    )


print("\nRow-count validation: PASS")


# ======================================================================
# 20. FINAL COLUMN-ROLE SUMMARY
# ======================================================================

print("\n" + "=" * 70)
print("FINAL COLUMN-ROLE SUMMARY")
print("=" * 70)


print("\nPredictors:")
print(f"  {len(predictor_columns)}")

print("\nExperimental phenotype targets:")
print(f"  {len(target_columns)}")

print("\nExperimental SD / uncertainty columns:")
print(f"  {len(target_sd_columns)}")

print("\nTotal columns before Part 12H metadata:")
print(f"  {df.shape[1]}")


# ======================================================================
# 21. ADD MINIMAL QC METADATA
# ======================================================================
#
# These columns document the QC state.
#
# They are metadata only and MUST NOT be used as ML predictors.
# ======================================================================

df["ML_QC_Status"] = "PASS"

df["ML_Predictor_Count_12H"] = len(
    predictor_columns
)

df["ML_Target_Count_12H"] = len(
    target_columns
)

df["ML_SD_Count_12H"] = len(
    target_sd_columns
)


# ----------------------------------------------------------------------
# Structural availability annotation is added only as QC metadata.
# It is not a biological predictor.
# ----------------------------------------------------------------------

if available_structural_features:

    structural_available = (
        df[available_structural_features]
        .notna()
        .any(axis=1)
    )

    df["Structural_QC_Status_12H"] = (
        structural_available
        .map({
            True: "Available",
            False: "Unresolved"
        })
    )


# ======================================================================
# 22. FINAL OUTPUT VALIDATION
# ======================================================================

print("\n" + "=" * 70)
print("FINAL OUTPUT VALIDATION")
print("=" * 70)


if df["ML_QC_Status"].ne("PASS").any():

    raise ValueError(
        "\nFinal ML QC status is not PASS."
    )


print("\nML QC status: PASS")

print(
    "\nNo train/test split performed."
)

print(
    "No scaling performed."
)

print(
    "No imputation performed."
)

print(
    "No model training performed."
)

print(
    "No additional amino-acid encoding performed."
)

print(
    "No target-derived predictors introduced."
)


# ======================================================================
# 23. SAVE EXACTLY ONE OUTPUT FILE
# ======================================================================

df.to_csv(
    OUTPUT_FILE,
    index=False
)


# ======================================================================
# 24. FINAL REPORT
# ======================================================================

print("\n" + "=" * 70)
print("PART 12H COMPLETE")
print("=" * 70)


print("\nFinal QC-validated dataset saved successfully:")

print(
    f"  {OUTPUT_FILE}"
)


print("\nFinal dataset dimensions:")

print(
    f"  Rows:    {df.shape[0]}"
)

print(
    f"  Columns: {df.shape[1]}"
)


print("\nFinal predictor count:")

print(
    f"  {len(predictor_columns)}"
)


print("\nExperimental phenotype targets:")

print(
    f"  {len(target_columns)}"
)


print("\nExperimental SD columns:")

print(
    f"  {len(target_sd_columns)}"
)


print("\nTarget leakage:")
print("  PASS")


print("\nMutation identity:")
print("  PASS")


print("\nAmino-acid encoding:")
print(
    "  Existing Part 12G encoding preserved"
)


print("\nStructural NaN policy:")
print(
    "  Preserved unchanged"
)


print("\nTarget missingness:")
print(
    "  Preserved unchanged"
)


print("\nTrain/test splitting:")
print(
    "  NOT PERFORMED"
)


print("\nFeature scaling:")
print(
    "  NOT PERFORMED"
)


print("\nMissing-value imputation:")
print(
    "  NOT PERFORMED"
)


print("\nModel training:")
print(
    "  NOT PERFORMED"
)


print("\n" + "=" * 70)
print("FINAL STATUS: READY FOR DOWNSTREAM ML DATASET CONSTRUCTION")
print("=" * 70)

======================================================================
PART 12H — FINAL ML DATASET SANITY CHECK & TARGET DEFINITION
======================================================================

Input file loaded successfully:
  VIM2_Part12G_Final_ML_Dataset.csv

Dataset dimensions:
  Rows:    5016
  Columns: 84

======================================================================
EXPERIMENTAL TARGET IDENTIFICATION
======================================================================

Experimental phenotype targets detected:
  9
  - 128ug/mL_AMP_25C
  - 16ug/mL_AMP_25C
  - 2ug/mL_AMP_25C
  - 128ug/mL_AMP_37C
  - 16ug/mL_AMP_37C
  - 2ug/mL_AMP_37C
  - 4ug/mL_CTX_37C
  - 0.5ug/mL_CTX_37C
  - 0.031ug/mL_MEM_37C

Experimental uncertainty / SD columns detected:
  9
  - 128ug/mL_AMP_25C_SD
  - 16ug/mL_AMP_25C_SD
  - 2ug/mL_AMP_25C_SD
  - 128ug/mL_AMP_37C_SD
  - 16ug/mL_AMP_37C_SD
  - 2ug/mL_AMP_37C_SD
  - 4ug/mL_CTX_37C_SD
  - 0.5ug/mL_CTX_37C_SD
  - 0.031ug/mL_MEM_37C_SD

Target identification validation: PASS

======================================================================
TARGET / SD PAIR VALIDATION
======================================================================

All experimental targets have corresponding SD columns.
Target/SD pairing status: PASS

======================================================================
MUTATION IDENTITY VALIDATION
======================================================================

Mutation identity columns detected:
  Mutation column: NOT FOUND
  Position column: Sequence_Position

======================================================================
SEQUENCE POSITION VALIDATION
======================================================================

Position column used:
  Sequence_Position

Missing/non-numeric positions:
  0

Out-of-range positions:
  0

Sequence-position validation: PASS

======================================================================
AMINO-ACID ENCODING REVIEW
======================================================================

Raw amino-acid columns:
  WT_AA present: No
  Mutant_AA present: No

One-hot encoded amino-acid columns:
  WT_AA encoded columns: 20
  Mutant_AA encoded columns: 20

Amino-acid encoding status: PASS

======================================================================
MUTATION KEY UNIQUENESS
======================================================================

Unique mutation keys:
  266

Duplicate mutation keys:
  4750

Mutation identity uniqueness check: PASS

======================================================================
FINAL PREDICTOR DEFINITION
======================================================================

Predictor count:
  66

Experimental targets excluded:
  9

Experimental SD columns excluded:
  9

======================================================================
TARGET LEAKAGE AUDIT
======================================================================

Target leakage check: PASS

======================================================================
PREDICTOR DATATYPE AUDIT
======================================================================

Categorical predictors:
  0

Numeric predictors:
  66

======================================================================
INFINITE-VALUE AUDIT
======================================================================

No infinite predictor values detected.
Infinite-value validation: PASS

======================================================================
CONSTANT PREDICTOR AUDIT
======================================================================

Constant predictors detected: 0

Constant predictor validation: PASS

======================================================================
EXACT DUPLICATE PREDICTOR AUDIT
======================================================================

Exact duplicate predictor pairs: 0

Duplicate predictor audit: PASS

======================================================================
TARGET COVERAGE AUDIT
======================================================================
           Feature                Type  Missing_Count  Observed_Count  Coverage_Percent
  128ug/mL_AMP_25C Experimental_Target              7            5009            99.860
   16ug/mL_AMP_25C Experimental_Target              7            5009            99.860
    2ug/mL_AMP_25C Experimental_Target              7            5009            99.860
  128ug/mL_AMP_37C Experimental_Target             12            5004            99.761
   16ug/mL_AMP_37C Experimental_Target             12            5004            99.761
    2ug/mL_AMP_37C Experimental_Target             12            5004            99.761
    4ug/mL_CTX_37C Experimental_Target             12            5004            99.761
  0.5ug/mL_CTX_37C Experimental_Target             12            5004            99.761
0.031ug/mL_MEM_37C Experimental_Target             12            5004            99.761

======================================================================
STRUCTURAL MISSINGNESS AUDIT
======================================================================

Distance_to_Metal_Site:
  Missing rows: 681
  Unique unresolved positions: 36
  Expected unresolved-position pattern: PASS

Distance_to_Active_Site_Pocket:
  Missing rows: 681
  Unique unresolved positions: 36
  Expected unresolved-position pattern: PASS

Distance_to_L3_Loop:
  Missing rows: 681
  Unique unresolved positions: 36
  Expected unresolved-position pattern: PASS

Distance_to_L10_Loop:
  Missing rows: 681
  Unique unresolved positions: 36
  Expected unresolved-position pattern: PASS

SASA:
  Missing rows: 681
  Unique unresolved positions: 36
  Expected unresolved-position pattern: PASS

======================================================================
FINAL DATASET SIZE VALIDATION
======================================================================

Expected rows:
  5016

Observed rows:
  5016

Row-count validation: PASS

======================================================================
FINAL COLUMN-ROLE SUMMARY
======================================================================

Predictors:
  66

Experimental phenotype targets:
  9

Experimental SD / uncertainty columns:
  9

Total columns before Part 12H metadata:
  84

======================================================================
FINAL OUTPUT VALIDATION
======================================================================

ML QC status: PASS

No train/test split performed.
No scaling performed.
No imputation performed.
No model training performed.
No additional amino-acid encoding performed.
No target-derived predictors introduced.

======================================================================
PART 12H COMPLETE
======================================================================

Final QC-validated dataset saved successfully:
  VIM2_Part12H_Final_ML_Sanity_Check.csv

Final dataset dimensions:
  Rows:    5016
  Columns: 89

Final predictor count:
  66

Experimental phenotype targets:
  9

Experimental SD columns:
  9

Target leakage:
  PASS

Mutation identity:
  PASS

Amino-acid encoding:
  Existing Part 12G encoding preserved

Structural NaN policy:
  Preserved unchanged

Target missingness:
  Preserved unchanged

Train/test splitting:
  NOT PERFORMED

Feature scaling:
  NOT PERFORMED

Missing-value imputation:
  NOT PERFORMED

Model training:
  NOT PERFORMED

======================================================================
FINAL STATUS: READY FOR DOWNSTREAM ML DATASET CONSTRUCTION
======================================================================